INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Horde Pandaren Warrior
(@HordePandarenMask, @WarriorMask, '668', 'Language Common'),
(@HordePandarenMask, @WarriorMask, '68975', 'Viciousness'),
(@HordePandarenMask, @WarriorMask, '68976', 'Aberration'),
(@HordePandarenMask, @WarriorMask, '68978', 'Flayer'),
(@HordePandarenMask, @WarriorMask, '68992', 'Darkflight'),
(@HordePandarenMask, @WarriorMask, '78', 'Heroic Strike'),
(@HordePandarenMask, @WarriorMask, '81', 'Dodge'),
(@HordePandarenMask, @WarriorMask, '107', 'Block'),
(@HordePandarenMask, @WarriorMask, '196', 'One-Handed Axes'),
(@HordePandarenMask, @WarriorMask, '198', 'One-Handed Maces'),
(@HordePandarenMask, @WarriorMask, '201', 'One-Handed Swords'),
(@HordePandarenMask, @WarriorMask, '203', 'Unarmed'),
(@HordePandarenMask, @WarriorMask, '204', 'Defense'),
(@HordePandarenMask, @WarriorMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @WarriorMask, '2382', 'Generic'),
(@HordePandarenMask, @WarriorMask, '2457', 'Battle Stance'),
(@HordePandarenMask, @WarriorMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @WarriorMask, '3050', 'Detect'),
(@HordePandarenMask, @WarriorMask, '3365', 'Opening'),
(@HordePandarenMask, @WarriorMask, '5301', 'Defensive State(DND)'),
(@HordePandarenMask, @WarriorMask, '6233', 'Closing'),
(@HordePandarenMask, @WarriorMask, '6246', 'Closing'),
(@HordePandarenMask, @WarriorMask, '6247', 'Opening'),
(@HordePandarenMask, @WarriorMask, '6477', 'Opening'),
(@HordePandarenMask, @WarriorMask, '6478', 'Opening'),
(@HordePandarenMask, @WarriorMask, '6603', 'Attack'),
(@HordePandarenMask, @WarriorMask, '7266', 'Duel'),
(@HordePandarenMask, @WarriorMask, '7267', 'Grovel'),
(@HordePandarenMask, @WarriorMask, '7355', 'Stuck'),
(@HordePandarenMask, @WarriorMask, '7376', 'Defensive Stance Passive'),
(@HordePandarenMask, @WarriorMask, '7381', 'Berserker Stance Passive'),
(@HordePandarenMask, @WarriorMask, '8386', 'Attacking'),
(@HordePandarenMask, @WarriorMask, '8737', 'Mail'),
(@HordePandarenMask, @WarriorMask, '9077', 'Leather'),
(@HordePandarenMask, @WarriorMask, '9078', 'Cloth'),
(@HordePandarenMask, @WarriorMask, '9116', 'Shield'),
(@HordePandarenMask, @WarriorMask, '9125', 'Generic'),
(@HordePandarenMask, @WarriorMask, '21156', 'Battle Stance Passive'),
(@HordePandarenMask, @WarriorMask, '21651', 'Opening'),
(@HordePandarenMask, @WarriorMask, '21652', 'Closing'),
(@HordePandarenMask, @WarriorMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @WarriorMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @WarriorMask, '32215', 'Victorious State'),
(@HordePandarenMask, @WarriorMask, '2048', 'Battle Shout'),
(@HordePandarenMask, @WarriorMask, '30324', 'Heroic Strike'),
(@HordePandarenMask, @WarriorMask, '11578', 'Charge'),
(@HordePandarenMask, @WarriorMask, '25208', 'Rend'),
(@HordePandarenMask, @WarriorMask, '25264', 'Thunder Clap'),
(@HordePandarenMask, @WarriorMask, '2687', 'Bloodrage'),
(@HordePandarenMask, @WarriorMask, '71', 'Defensive Stance'),
(@HordePandarenMask, @WarriorMask, '25225', 'Sunder Armor'),
(@HordePandarenMask, @WarriorMask, '355', 'Taunt'),
(@HordePandarenMask, @WarriorMask, '11585', 'Overpower'),
(@HordePandarenMask, @WarriorMask, '29704', 'Shield Bash'),
(@HordePandarenMask, @WarriorMask, '25203', 'Demoralizing Shout'),
(@HordePandarenMask, @WarriorMask, '30357', 'Revenge'),
(@HordePandarenMask, @WarriorMask, '25266', 'Mocking Blow'),
(@HordePandarenMask, @WarriorMask, '2565', 'Shield Block'),
(@HordePandarenMask, @WarriorMask, '676', 'Disarm'),
(@HordePandarenMask, @WarriorMask, '25231', 'Cleave'),
(@HordePandarenMask, @WarriorMask, '20230', 'Retaliation'),
(@HordePandarenMask, @WarriorMask, '5246', 'Intimidating Shout'),
(@HordePandarenMask, @WarriorMask, '25236', 'Execute'),
(@HordePandarenMask, @WarriorMask, '1161', 'Challenging Shout'),
(@HordePandarenMask, @WarriorMask, '871', 'Shield Wall'),
(@HordePandarenMask, @WarriorMask, '2458', 'Berserker Stance'),
(@HordePandarenMask, @WarriorMask, '25275', 'Intercept'),
(@HordePandarenMask, @WarriorMask, '25242', 'Slam'),
(@HordePandarenMask, @WarriorMask, '18499', 'Berserker Rage'),
(@HordePandarenMask, @WarriorMask, '1680', 'Whirlwind'),
(@HordePandarenMask, @WarriorMask, '6554', 'Pummel'),
(@HordePandarenMask, @WarriorMask, '1719', 'Recklessness'),
(@HordePandarenMask, @WarriorMask, '34428', 'Victory Rush'),
(@HordePandarenMask, @WarriorMask, '23920', 'Spell Reflection'),
(@HordePandarenMask, @WarriorMask, '469', 'Commanding Shout'),
(@HordePandarenMask, @WarriorMask, '3411', 'Intervene'),
(@HordePandarenMask, @WarriorMask, '25212', 'Hamstring'), -- Only 9?
(@HordePandarenMask, @WarriorMask, '674', 'Dual Wield'),
(@HordePandarenMask, @WarriorMask, '750', 'Plate Armor'), -- Only 19?
(@HordePandarenMask, @WarriorMask, '12678', 'Stance Mastery'), -- Only 9?

-- Horde Pandaren Hunter
(@HordePandarenMask, @HunterMask, '668', 'Language Common'),
(@HordePandarenMask, @HunterMask, '68975', 'Viciousness'),
(@HordePandarenMask, @HunterMask, '68976', 'Aberration'),
(@HordePandarenMask, @HunterMask, '68978', 'Flayer'),
(@HordePandarenMask, @HunterMask, '68992', 'Darkflight'),
(@HordePandarenMask, @HunterMask, '75', 'Auto Shot'),
(@HordePandarenMask, @HunterMask, '81', 'Dodge'),
(@HordePandarenMask, @HunterMask, '196', 'One-Handed Axes'),
(@HordePandarenMask, @HunterMask, '203', 'Unarmed'),
(@HordePandarenMask, @HunterMask, '204', 'Defense'),
(@HordePandarenMask, @HunterMask, '264', 'Bows'),
(@HordePandarenMask, @HunterMask, '266', 'Guns'),
(@HordePandarenMask, @HunterMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @HunterMask, '883', 'Call Pet'),
(@HordePandarenMask, @HunterMask, '982', 'Revive Pet'),
(@HordePandarenMask, @HunterMask, '1002', 'Eyes of the Beast'),
(@HordePandarenMask, @HunterMask, '1462', 'Beast Lore'),
(@HordePandarenMask, @HunterMask, '1494', 'Track Beasts'),
(@HordePandarenMask, @HunterMask, '1515', 'Tame Beast'),
(@HordePandarenMask, @HunterMask, '1543', 'Flare'),
(@HordePandarenMask, @HunterMask, '2382', 'Generic'),
(@HordePandarenMask, @HunterMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @HunterMask, '2641', 'Dismiss Pet'),
(@HordePandarenMask, @HunterMask, '2973', 'Raptor Strike'),
(@HordePandarenMask, @HunterMask, '3043', 'Scorpid Sting'),
(@HordePandarenMask, @HunterMask, '3045', 'Rapid Fire'),
(@HordePandarenMask, @HunterMask, '3050', 'Detect'),
(@HordePandarenMask, @HunterMask, '3365', 'Opening'),
(@HordePandarenMask, @HunterMask, '5116', 'Concussive Shot'),
(@HordePandarenMask, @HunterMask, '5118', 'Aspect of the Cheetah'),
(@HordePandarenMask, @HunterMask, '5384', 'Feign Death'),
(@HordePandarenMask, @HunterMask, '6197', 'Eagle Eye'),
(@HordePandarenMask, @HunterMask, '6233', 'Closing'),
(@HordePandarenMask, @HunterMask, '6246', 'Closing'),
(@HordePandarenMask, @HunterMask, '6247', 'Opening'),
(@HordePandarenMask, @HunterMask, '6477', 'Opening'),
(@HordePandarenMask, @HunterMask, '6478', 'Opening'),
(@HordePandarenMask, @HunterMask, '6603', 'Attack'),
(@HordePandarenMask, @HunterMask, '6991', 'Feed Pet'),
(@HordePandarenMask, @HunterMask, '7266', 'Duel'),
(@HordePandarenMask, @HunterMask, '7267', 'Grovel'),
(@HordePandarenMask, @HunterMask, '7355', 'Stuck'),
(@HordePandarenMask, @HunterMask, '8386', 'Attacking'),
(@HordePandarenMask, @HunterMask, '9077', 'Leather'),
(@HordePandarenMask, @HunterMask, '9078', 'Cloth'),
(@HordePandarenMask, @HunterMask, '9125', 'Generic'),
(@HordePandarenMask, @HunterMask, '13159', 'Aspect of the Pack'),
(@HordePandarenMask, @HunterMask, '13161', 'Aspect of the Beast'),
(@HordePandarenMask, @HunterMask, '13163', 'Aspect of the Monkey'),
(@HordePandarenMask, @HunterMask, '13358', 'Defensive State(DND)'),
(@HordePandarenMask, @HunterMask, '13809', 'Frost Trap'),
(@HordePandarenMask, @HunterMask, '14268', 'Alliance Flag'), -- What?
(@HordePandarenMask, @HunterMask, '14311', 'Freezing Trap'),
(@HordePandarenMask, @HunterMask, '14325', 'Hunters Mark'),
(@HordePandarenMask, @HunterMask, '14327', 'Scare Beast'),
(@HordePandarenMask, @HunterMask, '19801', 'Tranquilizing Shot'),
(@HordePandarenMask, @HunterMask, '19878', 'Track Demons'),
(@HordePandarenMask, @HunterMask, '19879', 'Track Dragonkin'),
(@HordePandarenMask, @HunterMask, '19880', 'Track Elementals'),
(@HordePandarenMask, @HunterMask, '19882', 'Track Giants'),
(@HordePandarenMask, @HunterMask, '19883', 'Track Humanoids'),
(@HordePandarenMask, @HunterMask, '19884', 'Track Undead'),
(@HordePandarenMask, @HunterMask, '19885', 'Track Hidden'),
(@HordePandarenMask, @HunterMask, '21651', 'Opening'),
(@HordePandarenMask, @HunterMask, '21652', 'Closing'),
(@HordePandarenMask, @HunterMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @HunterMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @HunterMask, '24949', 'Defensive State 2(DND)'),
(@HordePandarenMask, @HunterMask, '27014', 'Raptor Strike'),
-- (@HordePandarenMask, @HunterMask, '27015', 'Disengage'), -- Removed?
(@HordePandarenMask, @HunterMask, '27016', 'Serpent Sting'),
-- (@HordePandarenMask, @HunterMask, '27018', 'Viper Sting'), -- Removed?
(@HordePandarenMask, @HunterMask, '27019', 'Arcane Shot'),
-- (@HordePandarenMask, @HunterMask, '27020', 'Distracting Shot'), -- Removed?
(@HordePandarenMask, @HunterMask, '27021', 'Multi-Shot'),
(@HordePandarenMask, @HunterMask, '27022', 'Volley'),
(@HordePandarenMask, @HunterMask, '27023', 'Immolation Trap'),
(@HordePandarenMask, @HunterMask, '27025', 'Explosive Trap'),
(@HordePandarenMask, @HunterMask, '27044', 'Aspect of the Hawk'),
(@HordePandarenMask, @HunterMask, '27045', 'Aspect of the Wild'),
(@HordePandarenMask, @HunterMask, '27046', 'Mend Pet'),
(@HordePandarenMask, @HunterMask, '34026', 'Kill Command'),
(@HordePandarenMask, @HunterMask, '34074', 'Aspect of the Viper'),
(@HordePandarenMask, @HunterMask, '34082', 'Advantaged State(DND)'),
(@HordePandarenMask, @HunterMask, '34120', 'Steady Shot'),
(@HordePandarenMask, @HunterMask, '34477', 'Misdirection'),
(@HordePandarenMask, @HunterMask, '34600', 'Snake Trap'),
(@HordePandarenMask, @HunterMask, '36916', 'Mongoose Bite'),

-- Horde Pandaren Rogue
(@HordePandarenMask, @RogueMask, '668', 'Language Common'),
(@HordePandarenMask, @RogueMask, '68975', 'Viciousness'),
(@HordePandarenMask, @RogueMask, '68976', 'Aberration'),
(@HordePandarenMask, @RogueMask, '68978', 'Flayer'),
(@HordePandarenMask, @RogueMask, '68992', 'Darkflight'),
(@HordePandarenMask, @RogueMask, '81', 'Dodge'),
(@HordePandarenMask, @RogueMask, '203', 'Unarmed'),
(@HordePandarenMask, @RogueMask, '204', 'Defense'),
(@HordePandarenMask, @RogueMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @RogueMask, '1180', 'Daggers'),
(@HordePandarenMask, @RogueMask, '1752', 'Sinister Strike'),
(@HordePandarenMask, @RogueMask, '2098', 'Eviscerate'),
(@HordePandarenMask, @RogueMask, '2382', 'Generic'),
(@HordePandarenMask, @RogueMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @RogueMask, '2567', 'Thrown'),
(@HordePandarenMask, @RogueMask, '2764', 'Throw'),
(@HordePandarenMask, @RogueMask, '3050', 'Detect'),
(@HordePandarenMask, @RogueMask, '3365', 'Opening'),
(@HordePandarenMask, @RogueMask, '6233', 'Closing'),
(@HordePandarenMask, @RogueMask, '6246', 'Closing'),
(@HordePandarenMask, @RogueMask, '6247', 'Opening'),
(@HordePandarenMask, @RogueMask, '6477', 'Opening'),
(@HordePandarenMask, @RogueMask, '6478', 'Opening'),
(@HordePandarenMask, @RogueMask, '6603', 'Attack'),
(@HordePandarenMask, @RogueMask, '7266', 'Duel'),
(@HordePandarenMask, @RogueMask, '7267', 'Grovel'),
(@HordePandarenMask, @RogueMask, '7355', 'Stuck'),
(@HordePandarenMask, @RogueMask, '8386', 'Attacking'),
(@HordePandarenMask, @RogueMask, '9077', 'Leather'),
(@HordePandarenMask, @RogueMask, '9078', 'Cloth'),
(@HordePandarenMask, @RogueMask, '9125', 'Generic'),
(@HordePandarenMask, @RogueMask, '16092', 'Defensive State(DND)'),
(@HordePandarenMask, @RogueMask, '21184', 'Rogue Passive(DND)'),
(@HordePandarenMask, @RogueMask, '21651', 'Opening'),
(@HordePandarenMask, @RogueMask, '21652', 'Closing'),
(@HordePandarenMask, @RogueMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @RogueMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @RogueMask, '26865', 'Eviscerate'), -- Only 9?
(@HordePandarenMask, @RogueMask, '26862', 'Sinister Strike'), -- Only 9?
(@HordePandarenMask, @RogueMask, '1787', 'Stealth'), -- Only 9?
(@HordePandarenMask, @RogueMask, '26863', 'Backstab'),
(@HordePandarenMask, @RogueMask, '921', 'Pick Pocket'),
(@HordePandarenMask, @RogueMask, '38764', 'Gouge'),
(@HordePandarenMask, @RogueMask, '26669', 'Evasion'),
(@HordePandarenMask, @RogueMask, '11297', 'Sap'),
(@HordePandarenMask, @RogueMask, '6774', 'Slice and Dice'),
(@HordePandarenMask, @RogueMask, '11305', 'Sprint'),
(@HordePandarenMask, @RogueMask, '38768', 'Kick'),
(@HordePandarenMask, @RogueMask, '26866', 'Expose Armor'),
(@HordePandarenMask, @RogueMask, '26884', 'Garrote'),
(@HordePandarenMask, @RogueMask, '27448', 'Feint'), -- Only 8?
(@HordePandarenMask, @RogueMask, '1804', 'Pick Lock'),
(@HordePandarenMask, @RogueMask, '27441', 'Ambush'),
(@HordePandarenMask, @RogueMask, '2842', 'Poisons'),
(@HordePandarenMask, @RogueMask, '1725', 'Distract'),
(@HordePandarenMask, @RogueMask, '26867', 'Rupture'),
(@HordePandarenMask, @RogueMask, '26889', 'Vanish'),
(@HordePandarenMask, @RogueMask, '1833', 'Cheap Shot'),
(@HordePandarenMask, @RogueMask, '1842', 'Disarm Trap'),
(@HordePandarenMask, @RogueMask, '408', 'Kidney Shot'),
(@HordePandarenMask, @RogueMask, '2094', 'Blind'),
(@HordePandarenMask, @RogueMask, '32684', 'Envenom'),
(@HordePandarenMask, @RogueMask, '26679', 'Deadly Throw'),
(@HordePandarenMask, @RogueMask, '31224', 'Cloak of Shadows'),
(@HordePandarenMask, @RogueMask, '5938', 'Shiv'),
(@HordePandarenMask, @RogueMask, '8643', 'Kidney Shot'),
(@HordePandarenMask, @RogueMask, '3127', 'Parry'),
(@HordePandarenMask, @RogueMask, '674', 'Dual Wield'),
(@HordePandarenMask, @RogueMask, '3776', 'Green Leather Bracers'), -- What?
-- (@HordePandarenMask, @RogueMask, '9186', null), -- Removed?
(@HordePandarenMask, @RogueMask, '21927', 'Natures Ally'), -- What?
(@HordePandarenMask, @RogueMask, '22054', 'QAEnchant Bracer +7 Intellect'), -- What?
-- (@HordePandarenMask, @RogueMask, '22055', null), -- Removed?
(@HordePandarenMask, @RogueMask, '2836', 'Detect Traps'),
-- (@HordePandarenMask, @RogueMask, '1860', 'Safe Fall'), -- Removed?

-- Horde Pandaren Priest
(@HordePandarenMask, @PriestMask, '668', 'Language Common'),
(@HordePandarenMask, @PriestMask, '68975', 'Viciousness'),
(@HordePandarenMask, @PriestMask, '68976', 'Aberration'),
(@HordePandarenMask, @PriestMask, '68978', 'Flayer'),
(@HordePandarenMask, @PriestMask, '68992', 'Darkflight'),
(@HordePandarenMask, @PriestMask, '81', 'Dodge'),
(@HordePandarenMask, @PriestMask, '198', 'One-Handed Maces'),
(@HordePandarenMask, @PriestMask, '203', 'Unarmed'),
(@HordePandarenMask, @PriestMask, '204', 'Defense'),
(@HordePandarenMask, @PriestMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @PriestMask, '585', 'Smite'),
(@HordePandarenMask, @PriestMask, '2050', 'Lesser Heal'),
(@HordePandarenMask, @PriestMask, '2382', 'Generic'),
(@HordePandarenMask, @PriestMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @PriestMask, '3050', 'Detect'),
(@HordePandarenMask, @PriestMask, '3365', 'Opening'),
(@HordePandarenMask, @PriestMask, '5009', 'Wands'),
(@HordePandarenMask, @PriestMask, '5019', 'Shoot'),
(@HordePandarenMask, @PriestMask, '6233', 'Closing'),
(@HordePandarenMask, @PriestMask, '6246', 'Closing'),
(@HordePandarenMask, @PriestMask, '6247', 'Opening'),
(@HordePandarenMask, @PriestMask, '6477', 'Opening'),
(@HordePandarenMask, @PriestMask, '6478', 'Opening'),
(@HordePandarenMask, @PriestMask, '6603', 'Attack'),
(@HordePandarenMask, @PriestMask, '7266', 'Duel'),
(@HordePandarenMask, @PriestMask, '7267', 'Grovel'),
(@HordePandarenMask, @PriestMask, '7355', 'Stuck'),
(@HordePandarenMask, @PriestMask, '8386', 'Attacking'),
(@HordePandarenMask, @PriestMask, '9078', 'Cloth'),
(@HordePandarenMask, @PriestMask, '9125', 'Generic'),
(@HordePandarenMask, @PriestMask, '21651', 'Opening'),
(@HordePandarenMask, @PriestMask, '21652', 'Closing'),
(@HordePandarenMask, @PriestMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @PriestMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @PriestMask, '25389', 'Power Word: Fortitude'),
(@HordePandarenMask, @PriestMask, '25364', 'Smite'),
(@HordePandarenMask, @PriestMask, '25368', 'Shadow Word: Pain'),
(@HordePandarenMask, @PriestMask, '25218', 'Power Word: Shield'),
-- (@HordePandarenMask, @PriestMask, '25429', 'Fade'), -- Removed?
(@HordePandarenMask, @PriestMask, '25222', 'Renew'),
(@HordePandarenMask, @PriestMask, '25375', 'Mind Blast'),
(@HordePandarenMask, @PriestMask, '25435', 'Resurrection'),
(@HordePandarenMask, @PriestMask, '25431', 'Inner Fire'),
(@HordePandarenMask, @PriestMask, '528', 'Cure Disease'),
(@HordePandarenMask, @PriestMask, '10890', 'Psychic Scream'),
(@HordePandarenMask, @PriestMask, '988', 'Dispel Magic'),
(@HordePandarenMask, @PriestMask, '6346', 'Fear Ward'),
(@HordePandarenMask, @PriestMask, '25235', 'Flash Heal'),
(@HordePandarenMask, @PriestMask, '25384', 'Holy Fire'),
-- (@HordePandarenMask, @PriestMask, '25596', 'Mind Soothe'), -- Removed?
(@HordePandarenMask, @PriestMask, '10955', 'Shackle Undead'),
(@HordePandarenMask, @PriestMask, '10909', 'Mind Vision'),
-- (@HordePandarenMask, @PriestMask, '25380', 'Mana Burn'), -- Removed?
-- (@HordePandarenMask, @PriestMask, '10912', 'Mind Control'), -- Removed?
(@HordePandarenMask, @PriestMask, '25308', 'Prayer of Healing'),
(@HordePandarenMask, @PriestMask, '25433', 'Shadow Protection'),
(@HordePandarenMask, @PriestMask, '552', 'Abolish Disease'),
(@HordePandarenMask, @PriestMask, '1706', 'Levitate'),
(@HordePandarenMask, @PriestMask, '25213', 'Greater Heal'),
(@HordePandarenMask, @PriestMask, '25392', 'Prayer of Fortitude'),
(@HordePandarenMask, @PriestMask, '39374', 'Prayer of Shadow Protection'),
(@HordePandarenMask, @PriestMask, '32999', 'Prayer of Spirit'),
(@HordePandarenMask, @PriestMask, '32996', 'Shadow Word: Death'),
(@HordePandarenMask, @PriestMask, '32546', 'Binding Heal'),
(@HordePandarenMask, @PriestMask, '34433', 'Shadowfiend'),
(@HordePandarenMask, @PriestMask, '33076', 'Prayer of Mending'),
(@HordePandarenMask, @PriestMask, '32375', 'Mass Dispel'),
-- (@HordePandarenMask, @PriestMask, '25441', 'Feedback'), -- Removed? Only 4?
(@HordePandarenMask, @PriestMask, '25312', 'Divine Spirit'),
(@HordePandarenMask, @PriestMask, '25437', 'Desperate Prayer'), -- Only 5?

-- Horde Pandaren Shaman
(@HordePandarenMask, @ShamanMask, '68975', 'Viciousness'),
(@HordePandarenMask, @ShamanMask, '68976', 'Aberration'),
(@HordePandarenMask, @ShamanMask, '68978', 'Flayer'),
(@HordePandarenMask, @ShamanMask, '68992', 'Darkflight'),
(@HordePandarenMask, @ShamanMask, '81', 'Dodge'),
(@HordePandarenMask, @ShamanMask, '107', 'Block'),
(@HordePandarenMask, @ShamanMask, '131', 'Water Breathing'),
(@HordePandarenMask, @ShamanMask, '198', 'One-Handed Maces'),
(@HordePandarenMask, @ShamanMask, '203', 'Unarmed'),
(@HordePandarenMask, @ShamanMask, '204', 'Defense'),
(@HordePandarenMask, @ShamanMask, '227', 'Staves'),
(@HordePandarenMask, @ShamanMask, '331', 'Healing Wave'),
(@HordePandarenMask, @ShamanMask, '403', 'Lightning Bolt'),
(@HordePandarenMask, @ShamanMask, '421', 'Chain Lightning'),
(@HordePandarenMask, @ShamanMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @ShamanMask, '526', 'Cure Toxins'),
(@HordePandarenMask, @ShamanMask, '546', 'Water Walking'),
(@HordePandarenMask, @ShamanMask, '556', 'Astral Recall'),
(@HordePandarenMask, @ShamanMask, '668', 'Language Common'),
(@HordePandarenMask, @ShamanMask, '2062', 'Earth Elemental Totem'),
(@HordePandarenMask, @ShamanMask, '2382', 'Generic'),
(@HordePandarenMask, @ShamanMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @ShamanMask, '2484', 'Earthbind Totem'),
(@HordePandarenMask, @ShamanMask, '2645', 'Ghost Wolf'),
(@HordePandarenMask, @ShamanMask, '2825', 'Bloodlust'),
-- (@HordePandarenMask, @ShamanMask, '2870', 'Cure Disease'), -- Removed?
(@HordePandarenMask, @ShamanMask, '2894', 'Fire Elemental Totem'),
(@HordePandarenMask, @ShamanMask, '3050', 'Detect'),
(@HordePandarenMask, @ShamanMask, '3365', 'Opening'),
(@HordePandarenMask, @ShamanMask, '3738', 'Wrath of Air Totem'),
(@HordePandarenMask, @ShamanMask, '6196', 'Far Sight'),
(@HordePandarenMask, @ShamanMask, '6233', 'Closing'),
(@HordePandarenMask, @ShamanMask, '6246', 'Closing'),
(@HordePandarenMask, @ShamanMask, '6247', 'Opening'),
(@HordePandarenMask, @ShamanMask, '6477', 'Opening'),
(@HordePandarenMask, @ShamanMask, '6478', 'Opening'),
(@HordePandarenMask, @ShamanMask, '6495', 'Sentry Totem'),
(@HordePandarenMask, @ShamanMask, '6603', 'Attack'),
(@HordePandarenMask, @ShamanMask, '7266', 'Duel'),
(@HordePandarenMask, @ShamanMask, '7267', 'Grovel'),
(@HordePandarenMask, @ShamanMask, '7355', 'Stuck'),
(@HordePandarenMask, @ShamanMask, '8012', 'Purge'),
(@HordePandarenMask, @ShamanMask, '8143', 'Tremor Totem'),
(@HordePandarenMask, @ShamanMask, '8166', 'Poison Cleansing Totem'),
(@HordePandarenMask, @ShamanMask, '8170', 'Cleansing Totem'),
(@HordePandarenMask, @ShamanMask, '8177', 'Grounding Totem'),
(@HordePandarenMask, @ShamanMask, '8386', 'Attacking'),
(@HordePandarenMask, @ShamanMask, '9077', 'Leather'),
(@HordePandarenMask, @ShamanMask, '9078', 'Cloth'),
(@HordePandarenMask, @ShamanMask, '9116', 'Shield'),
(@HordePandarenMask, @ShamanMask, '9125', 'Generic'),
(@HordePandarenMask, @ShamanMask, '20777', 'Ancestral Spirit'),
(@HordePandarenMask, @ShamanMask, '21651', 'Opening'),
(@HordePandarenMask, @ShamanMask, '21652', 'Closing'),
(@HordePandarenMask, @ShamanMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @ShamanMask, '22810', 'Opening - No Text'),
-- (@HordePandarenMask, @ShamanMask, '25359', 'Grace of Air Totem'), -- Removed?
(@HordePandarenMask, @ShamanMask, '25396', 'Healing Wave'),
(@HordePandarenMask, @ShamanMask, '25420', 'Lesser Healing Wave'),
(@HordePandarenMask, @ShamanMask, '25423', 'Chain Heal'),
(@HordePandarenMask, @ShamanMask, '25449', 'Lightning Bolt'),
(@HordePandarenMask, @ShamanMask, '25454', 'Earth Shock'),
(@HordePandarenMask, @ShamanMask, '25457', 'Flame Shock'),
(@HordePandarenMask, @ShamanMask, '25464', 'Frost Shock'),
(@HordePandarenMask, @ShamanMask, '25472', 'Lightning Shield'),
-- (@HordePandarenMask, @ShamanMask, '25485', 'Rockbiter Weapon'), -- Removed?
(@HordePandarenMask, @ShamanMask, '25489', 'Flametongue Weapon'),
(@HordePandarenMask, @ShamanMask, '25500', 'Frostbrand Weapon'),
(@HordePandarenMask, @ShamanMask, '25505', 'Windfury Weapon'),
(@HordePandarenMask, @ShamanMask, '25509', 'Stoneskin Totem'),
(@HordePandarenMask, @ShamanMask, '25525', 'Stoneclaw Totem'),
(@HordePandarenMask, @ShamanMask, '25528', 'Strength of Earth Totem'),
(@HordePandarenMask, @ShamanMask, '25533', 'Searing Totem'),
(@HordePandarenMask, @ShamanMask, '25547', 'Fire Nova'),
(@HordePandarenMask, @ShamanMask, '25552', 'Magma Totem'),
(@HordePandarenMask, @ShamanMask, '25557', 'Flametongue Totem'),
(@HordePandarenMask, @ShamanMask, '25560', 'Frost Resistance Totem'),
(@HordePandarenMask, @ShamanMask, '25563', 'Fire Resistance Totem'),
(@HordePandarenMask, @ShamanMask, '25567', 'Healing Stream Totem'),
(@HordePandarenMask, @ShamanMask, '25570', 'Mana Spring Totem'),
(@HordePandarenMask, @ShamanMask, '25574', 'Nature Resistance Totem'),
-- (@HordePandarenMask, @ShamanMask, '25577', 'Windwall Totem'), -- Removed?
-- (@HordePandarenMask, @ShamanMask, '25587', 'Windfury Totem'), -- Removed?
-- (@HordePandarenMask, @ShamanMask, '25908', 'Tranquil Air Totem'), -- Removed?
(@HordePandarenMask, @ShamanMask, '27763', 'Totem'),
(@HordePandarenMask, @ShamanMask, '33736', 'Water Shield'),
(@HordePandarenMask, @ShamanMask, '36936', 'Totemic Recall'),

-- Horde Pandaren Mage
(@HordePandarenMask, @MageMask, '668', 'Language Common'),
(@HordePandarenMask, @MageMask, '68975', 'Viciousness'),
(@HordePandarenMask, @MageMask, '68976', 'Aberration'),
(@HordePandarenMask, @MageMask, '68978', 'Flayer'),
(@HordePandarenMask, @MageMask, '68992', 'Darkflight'),
(@HordePandarenMask, @MageMask, '81', 'Dodge'),
(@HordePandarenMask, @MageMask, '133', 'Fireball'),
(@HordePandarenMask, @MageMask, '168', 'Frost Armor'),
(@HordePandarenMask, @MageMask, '203', 'Unarmed'),
(@HordePandarenMask, @MageMask, '204', 'Defense'),
(@HordePandarenMask, @MageMask, '227', 'Staves'),
(@HordePandarenMask, @MageMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @MageMask, '2382', 'Generic'),
(@HordePandarenMask, @MageMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @MageMask, '3050', 'Detect'),
(@HordePandarenMask, @MageMask, '3365', 'Opening'),
(@HordePandarenMask, @MageMask, '5009', 'Wands'),
(@HordePandarenMask, @MageMask, '5019', 'Shoot'),
(@HordePandarenMask, @MageMask, '6233', 'Closing'),
(@HordePandarenMask, @MageMask, '6246', 'Closing'),
(@HordePandarenMask, @MageMask, '6247', 'Opening'),
(@HordePandarenMask, @MageMask, '6477', 'Opening'),
(@HordePandarenMask, @MageMask, '6478', 'Opening'),
(@HordePandarenMask, @MageMask, '6603', 'Attack'),
(@HordePandarenMask, @MageMask, '7266', 'Duel'),
(@HordePandarenMask, @MageMask, '7267', 'Grovel'),
(@HordePandarenMask, @MageMask, '7355', 'Stuck'),
(@HordePandarenMask, @MageMask, '8386', 'Attacking'),
(@HordePandarenMask, @MageMask, '9078', 'Cloth'),
(@HordePandarenMask, @MageMask, '9125', 'Generic'),
(@HordePandarenMask, @MageMask, '21651', 'Opening'),
(@HordePandarenMask, @MageMask, '21652', 'Closing'),
(@HordePandarenMask, @MageMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @MageMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @MageMask, '27126', 'Arcane Intellect'),
(@HordePandarenMask, @MageMask, '27070', 'Fireball'),
-- (@HordePandarenMask, @MageMask, '22018', null), -- Removed?
(@HordePandarenMask, @MageMask, '27072', 'Frostbolt'),
-- (@HordePandarenMask, @MageMask, '22019', null), -- Removed?
(@HordePandarenMask, @MageMask, '27079', 'Fire Blast'),
(@HordePandarenMask, @MageMask, '38704', 'Arcane Missiles'),
(@HordePandarenMask, @MageMask, '28272', 'Polymorph (Pig)'),
(@HordePandarenMask, @MageMask, '28271', 'Polymorph (Turtle)'),
(@HordePandarenMask, @MageMask, '12826', 'Polymorph (Sheep)'),
(@HordePandarenMask, @MageMask, '27088', 'Frost Nova'),
(@HordePandarenMask, @MageMask, '33944', 'Dampen Magic'),
(@HordePandarenMask, @MageMask, '130', 'Slow Fall'),
(@HordePandarenMask, @MageMask, '27082', 'Arcane Explosion'),
(@HordePandarenMask, @MageMask, '27086', 'Flamestrike'),
(@HordePandarenMask, @MageMask, '33946', 'Amplify Magic'),
(@HordePandarenMask, @MageMask, '475', 'Remove Curse'),
(@HordePandarenMask, @MageMask, '1953', 'Blink'),
(@HordePandarenMask, @MageMask, '27085', 'Blizzard'),
(@HordePandarenMask, @MageMask, '12051', 'Evocation'),
(@HordePandarenMask, @MageMask, '27128', 'Fire Ward'),
(@HordePandarenMask, @MageMask, '27131', 'Mana Shield'),
(@HordePandarenMask, @MageMask, '32796', 'Frost Ward'),
(@HordePandarenMask, @MageMask, '27074', 'Scorch'),
(@HordePandarenMask, @MageMask, '2139', 'Counterspell'),
(@HordePandarenMask, @MageMask, '27101', 'Conjure Mana Gem'),
(@HordePandarenMask, @MageMask, '27124', 'Ice Armor'),
(@HordePandarenMask, @MageMask, '45438', 'Ice Block'),
(@HordePandarenMask, @MageMask, '27125', 'Mage Armor'),
(@HordePandarenMask, @MageMask, '27127', 'Arcane Brilliance'),
(@HordePandarenMask, @MageMask, '30482', 'Molten Armor'),
(@HordePandarenMask, @MageMask, '30451', 'Arcane Blast'),
(@HordePandarenMask, @MageMask, '30455', 'Ice Lance'),
(@HordePandarenMask, @MageMask, '66', 'Invisibility'),
(@HordePandarenMask, @MageMask, '43987', 'Ritual of Refreshment'),
(@HordePandarenMask, @MageMask, '30449', 'Spellsteal'),
(@HordePandarenMask, @MageMask, '27087', 'Cone of Cold');
