INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Horde Pandaren Paladin
(@HordePandarenMask, @PaladinMask, '68975', 'Viciousness'),
(@HordePandarenMask, @PaladinMask, '68976', 'Aberration'),
(@HordePandarenMask, @PaladinMask, '68978', 'Flayer'),
(@HordePandarenMask, @PaladinMask, '68992', 'Darkflight'),
(@HordePandarenMask, @PaladinMask, '81', 'Dodge'),
(@HordePandarenMask, @PaladinMask, '107', 'Block'),
(@HordePandarenMask, @PaladinMask, '198', 'One-Handed Maces'),
(@HordePandarenMask, @PaladinMask, '199', 'Two-Handed Maces'),
(@HordePandarenMask, @PaladinMask, '203', 'Unarmed'),
(@HordePandarenMask, @PaladinMask, '204', 'Defense'),
(@HordePandarenMask, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @PaladinMask, '635', 'Holy Light'),
(@HordePandarenMask, @PaladinMask, '668', 'Language Common'),
(@HordePandarenMask, @PaladinMask, '2382', 'Generic'),
(@HordePandarenMask, @PaladinMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @PaladinMask, '3050', 'Detect'),
(@HordePandarenMask, @PaladinMask, '3365', 'Opening'),
(@HordePandarenMask, @PaladinMask, '6233', 'Closing'),
(@HordePandarenMask, @PaladinMask, '6246', 'Closing'),
(@HordePandarenMask, @PaladinMask, '6247', 'Opening'),
(@HordePandarenMask, @PaladinMask, '6477', 'Opening'),
(@HordePandarenMask, @PaladinMask, '6478', 'Opening'),
(@HordePandarenMask, @PaladinMask, '6603', 'Attack'),
(@HordePandarenMask, @PaladinMask, '7266', 'Duel'),
(@HordePandarenMask, @PaladinMask, '7267', 'Grovel'),
(@HordePandarenMask, @PaladinMask, '7355', 'Stuck'),
(@HordePandarenMask, @PaladinMask, '8386', 'Attacking'),
(@HordePandarenMask, @PaladinMask, '8737', 'Mail'),
(@HordePandarenMask, @PaladinMask, '9077', 'Leather'),
(@HordePandarenMask, @PaladinMask, '9078', 'Cloth'),
(@HordePandarenMask, @PaladinMask, '9116', 'Shield'),
(@HordePandarenMask, @PaladinMask, '9125', 'Generic'),
(@HordePandarenMask, @PaladinMask, '21084', 'Seal of Righteousness'),
(@HordePandarenMask, @PaladinMask, '21651', 'Opening'),
(@HordePandarenMask, @PaladinMask, '21652', 'Closing'),
(@HordePandarenMask, @PaladinMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @PaladinMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @PaladinMask, '27762', 'Libram'),
(@HordePandarenMask, @PaladinMask, '27149', 'Devotion Aura'),
(@HordePandarenMask, @PaladinMask, '27136', 'Holy Light'),
-- (@HordePandarenMask, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
(@HordePandarenMask, @PaladinMask, '27140', 'Blessing of Might'),
(@HordePandarenMask, @PaladinMask, '20271', 'Judgement of Light'),
-- (@HordePandarenMask, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
(@HordePandarenMask, @PaladinMask, '10308', 'Hammer of Justice'),
(@HordePandarenMask, @PaladinMask, '10278', 'Hand of Protection'),
(@HordePandarenMask, @PaladinMask, '27154', 'Lay on Hands'),
(@HordePandarenMask, @PaladinMask, '20773', 'Redemption'),
(@HordePandarenMask, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@HordePandarenMask, @PaladinMask, '31789', 'Righteous Defense'),
(@HordePandarenMask, @PaladinMask, '27150', 'Retribution Aura'),
(@HordePandarenMask, @PaladinMask, '25780', 'Righteous Fury'),
(@HordePandarenMask, @PaladinMask, '1044', 'Hand of Freedom'),
(@HordePandarenMask, @PaladinMask, '33776', 'Spiritual Attunement'),
(@HordePandarenMask, @PaladinMask, '27173', 'Consecration'),
(@HordePandarenMask, @PaladinMask, '27138', 'Exorcism'),
(@HordePandarenMask, @PaladinMask, '27137', 'Flash of Light'),
(@HordePandarenMask, @PaladinMask, '5502', 'Sense Undead'),
(@HordePandarenMask, @PaladinMask, '19746', 'Concentration Aura'),
-- (@HordePandarenMask, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
-- (@HordePandarenMask, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@HordePandarenMask, @PaladinMask, '1038', 'Hand of Salvation'),
(@HordePandarenMask, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@HordePandarenMask, @PaladinMask, '19752', 'Divine Intervention'),
-- (@HordePandarenMask, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
(@HordePandarenMask, @PaladinMask, '27152', 'Frost Resistance Aura'),
-- (@HordePandarenMask, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@HordePandarenMask, @PaladinMask, '27153', 'Fire Resistance Aura'),
-- (@HordePandarenMask, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@HordePandarenMask, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
(@HordePandarenMask, @PaladinMask, '4987', 'Cleanse'),
(@HordePandarenMask, @PaladinMask, '27180', 'Hammer of Wrath'),
-- (@HordePandarenMask, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@HordePandarenMask, @PaladinMask, '27139', 'Holy Wrath'),
(@HordePandarenMask, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@HordePandarenMask, @PaladinMask, '10326', 'Turn Evil'),
(@HordePandarenMask, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
(@HordePandarenMask, @PaladinMask, '25898', 'Greater Blessing of Kings'),
-- (@HordePandarenMask, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@HordePandarenMask, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@HordePandarenMask, @PaladinMask, '32223', 'Crusader Aura'),
-- (@HordePandarenMask, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@HordePandarenMask, @PaladinMask, '31884', 'Avenging Wrath'),
(@HordePandarenMask, @PaladinMask, '750', 'Plate Armor'),
(@HordePandarenMask, @PaladinMask, '3127', 'Parry'),
(@HordePandarenMask, @PaladinMask, '23214', 'Charger'), -- Only 9?
(@HordePandarenMask, @PaladinMask, '31801', 'Seal of Vengeance'), -- Only 9?

-- Horde Pandaren Warlock
(@HordePandarenMask, @WarlockMask, '668', 'Language Common'),
(@HordePandarenMask, @WarlockMask, '68975', 'Viciousness'),
(@HordePandarenMask, @WarlockMask, '68976', 'Aberration'),
(@HordePandarenMask, @WarlockMask, '68978', 'Flayer'),
(@HordePandarenMask, @WarlockMask, '68992', 'Darkflight'),
(@HordePandarenMask, @WarlockMask, '81', 'Dodge'),
(@HordePandarenMask, @WarlockMask, '203', 'Unarmed'),
(@HordePandarenMask, @WarlockMask, '204', 'Defense'),
(@HordePandarenMask, @WarlockMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @WarlockMask, '686', 'Shadow Bolt'),
(@HordePandarenMask, @WarlockMask, '687', 'Demon Skin'),
(@HordePandarenMask, @WarlockMask, '1180', 'Daggers'),
(@HordePandarenMask, @WarlockMask, '2382', 'Generic'),
(@HordePandarenMask, @WarlockMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @WarlockMask, '3050', 'Detect'),
(@HordePandarenMask, @WarlockMask, '3365', 'Opening'),
(@HordePandarenMask, @WarlockMask, '5009', 'Wands'),
(@HordePandarenMask, @WarlockMask, '5019', 'Shoot'),
(@HordePandarenMask, @WarlockMask, '6233', 'Closing'),
(@HordePandarenMask, @WarlockMask, '6246', 'Closing'),
(@HordePandarenMask, @WarlockMask, '6247', 'Opening'),
(@HordePandarenMask, @WarlockMask, '6477', 'Opening'),
(@HordePandarenMask, @WarlockMask, '6478', 'Opening'),
(@HordePandarenMask, @WarlockMask, '6603', 'Attack'),
(@HordePandarenMask, @WarlockMask, '7266', 'Duel'),
(@HordePandarenMask, @WarlockMask, '7267', 'Grovel'),
(@HordePandarenMask, @WarlockMask, '7355', 'Stuck'),
(@HordePandarenMask, @WarlockMask, '8386', 'Attacking'),
(@HordePandarenMask, @WarlockMask, '9078', 'Cloth'),
(@HordePandarenMask, @WarlockMask, '9125', 'Generic'),
(@HordePandarenMask, @WarlockMask, '21651', 'Opening'),
(@HordePandarenMask, @WarlockMask, '21652', 'Closing'),
(@HordePandarenMask, @WarlockMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @WarlockMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @WarlockMask, '27215', 'Immolate'), -- Only 9?
(@HordePandarenMask, @WarlockMask, '27209', 'Shadow Bolt'),
(@HordePandarenMask, @WarlockMask, '27216', 'Corruption'),
(@HordePandarenMask, @WarlockMask, '30909', 'Curse of Weakness'),
(@HordePandarenMask, @WarlockMask, '27222', 'Life Tap'),
(@HordePandarenMask, @WarlockMask, '27218', 'Curse of Agony'),
(@HordePandarenMask, @WarlockMask, '6215', 'Fear'),
(@HordePandarenMask, @WarlockMask, '27230', 'Create Healthstone'),
(@HordePandarenMask, @WarlockMask, '27217', 'Drain Soul'),
(@HordePandarenMask, @WarlockMask, '27259', 'Health Funnel'),
-- (@HordePandarenMask, @WarlockMask, '27226', 'Curse of Recklessness'), -- Removed?
(@HordePandarenMask, @WarlockMask, '27220', 'Drain Life'),
(@HordePandarenMask, @WarlockMask, '5697', 'Unending Breath'),
(@HordePandarenMask, @WarlockMask, '27238', 'Create Soulstone'),
(@HordePandarenMask, @WarlockMask, '30459', 'Searing Pain'),
(@HordePandarenMask, @WarlockMask, '27260', 'Demon Armor'),
(@HordePandarenMask, @WarlockMask, '27212', 'Rain of Fire'),
(@HordePandarenMask, @WarlockMask, '698', 'Ritual of Summoning'),
(@HordePandarenMask, @WarlockMask, '5500', 'Sense Demons'),
-- (@HordePandarenMask, @WarlockMask, '30908', 'Drain Mana'), -- Removed?
(@HordePandarenMask, @WarlockMask, '11719', 'Curse of Tongues'),
(@HordePandarenMask, @WarlockMask, '132', 'Detect Invisibility'),
(@HordePandarenMask, @WarlockMask, '18647', 'Banish'),
(@HordePandarenMask, @WarlockMask, '27213', 'Hellfire'),
(@HordePandarenMask, @WarlockMask, '11726', 'Subjugate Demon'),
(@HordePandarenMask, @WarlockMask, '27228', 'Curse of the Elements'),
(@HordePandarenMask, @WarlockMask, '28610', 'Shadow Ward'),
(@HordePandarenMask, @WarlockMask, '28172', 'Create Spellstone'),
(@HordePandarenMask, @WarlockMask, '27250', 'Create Firestone'),
(@HordePandarenMask, @WarlockMask, '17928', 'Howl of Terror'),
(@HordePandarenMask, @WarlockMask, '27223', 'Death Coil'),
-- (@HordePandarenMask, @WarlockMask, '27229', 'Curse of Shadow'), -- Removed?
(@HordePandarenMask, @WarlockMask, '30545', 'Soul Fire'),
(@HordePandarenMask, @WarlockMask, '30910', 'Curse of Doom'),
(@HordePandarenMask, @WarlockMask, '18540', 'Ritual of Doom'),
(@HordePandarenMask, @WarlockMask, '28189', 'Fel Armor'),
(@HordePandarenMask, @WarlockMask, '32231', 'Incinerate'),
(@HordePandarenMask, @WarlockMask, '29858', 'Soulshatter'),
(@HordePandarenMask, @WarlockMask, '29893', 'Ritual of Souls'),
(@HordePandarenMask, @WarlockMask, '27243', 'Seed of Corruption'),
(@HordePandarenMask, @WarlockMask, '23161', 'Dreadsteed'),
(@HordePandarenMask, @WarlockMask, '688', 'Summon Imp'),
(@HordePandarenMask, @WarlockMask, '697', 'Summon Voidwalker'),
(@HordePandarenMask, @WarlockMask, '712', 'Summon Succubus'),
(@HordePandarenMask, @WarlockMask, '691', 'Summon Felhunter'), -- 10 of this?
(@HordePandarenMask, @WarlockMask, '126', 'Eye of Kilrogg'),

-- Horde Pandaren Druid
(@HordePandarenMask, @DruidMask, '668', 'Language Common'),
(@HordePandarenMask, @DruidMask, '68975', 'Viciousness'),
(@HordePandarenMask, @DruidMask, '68976', 'Aberration'),
(@HordePandarenMask, @DruidMask, '68978', 'Flayer'),
(@HordePandarenMask, @DruidMask, '68992', 'Darkflight'),
(@HordePandarenMask, @DruidMask, '81', 'Dodge'),
(@HordePandarenMask, @DruidMask, '203', 'Unarmed'),
(@HordePandarenMask, @DruidMask, '204', 'Defense'),
(@HordePandarenMask, @DruidMask, '227', 'Staves'),
(@HordePandarenMask, @DruidMask, '522', 'SPELLDEFENSE(DND)'),
(@HordePandarenMask, @DruidMask, '768', 'Cat Form'),
(@HordePandarenMask, @DruidMask, '783', 'Travel Form'),
(@HordePandarenMask, @DruidMask, '1066', 'Aquatic Form'),
(@HordePandarenMask, @DruidMask, '1178', 'Bear Form(Passive)'),
(@HordePandarenMask, @DruidMask, '1180', 'Daggers'),
(@HordePandarenMask, @DruidMask, '2382', 'Generic'),
(@HordePandarenMask, @DruidMask, '2479', 'Honorless Target'),
(@HordePandarenMask, @DruidMask, '2782', 'Remove Curse'),
(@HordePandarenMask, @DruidMask, '2893', 'Abolish Poison'),
(@HordePandarenMask, @DruidMask, '3025', 'Cat Form(Passive)'),
(@HordePandarenMask, @DruidMask, '3050', 'Detect'),
(@HordePandarenMask, @DruidMask, '3365', 'Opening'),
(@HordePandarenMask, @DruidMask, '5176', 'Wrath'),
(@HordePandarenMask, @DruidMask, '5185', 'Healing Touch'),
(@HordePandarenMask, @DruidMask, '5209', 'Challenging Roar'),
(@HordePandarenMask, @DruidMask, '5225', 'Track Humanoids'),
(@HordePandarenMask, @DruidMask, '5229', 'Enrage'),
(@HordePandarenMask, @DruidMask, '5419', 'Travel Form(Passive)'),
(@HordePandarenMask, @DruidMask, '5420', 'Tree of Life'),
(@HordePandarenMask, @DruidMask, '5421', 'Aquatic Form(Passive)'),
(@HordePandarenMask, @DruidMask, '6233', 'Closing'),
(@HordePandarenMask, @DruidMask, '6246', 'Closing'),
(@HordePandarenMask, @DruidMask, '6247', 'Opening'),
(@HordePandarenMask, @DruidMask, '6477', 'Opening'),
(@HordePandarenMask, @DruidMask, '6478', 'Opening'),
(@HordePandarenMask, @DruidMask, '6603', 'Attack'),
(@HordePandarenMask, @DruidMask, '6795', 'Growl'),
(@HordePandarenMask, @DruidMask, '7266', 'Duel'),
(@HordePandarenMask, @DruidMask, '7267', 'Grovel'),
(@HordePandarenMask, @DruidMask, '7355', 'Stuck'),
(@HordePandarenMask, @DruidMask, '8386', 'Attacking'),
(@HordePandarenMask, @DruidMask, '8946', 'Cure Poison'),
(@HordePandarenMask, @DruidMask, '8983', 'Bash'),
(@HordePandarenMask, @DruidMask, '9077', 'Leather'),
(@HordePandarenMask, @DruidMask, '9078', 'Cloth'),
(@HordePandarenMask, @DruidMask, '9125', 'Generic'),
(@HordePandarenMask, @DruidMask, '9634', 'Dire Bear Form'),
(@HordePandarenMask, @DruidMask, '9635', 'Dire Bear Form(Passive)'),
(@HordePandarenMask, @DruidMask, '9846', 'Tigers Fury'),
(@HordePandarenMask, @DruidMask, '9913', 'Prowl'),
(@HordePandarenMask, @DruidMask, '18658', 'Hibernate'),
(@HordePandarenMask, @DruidMask, '18960', 'Teleport: Moonglade'),
(@HordePandarenMask, @DruidMask, '21178', 'Bear Form(Passive2)'),
(@HordePandarenMask, @DruidMask, '21651', 'Opening'),
(@HordePandarenMask, @DruidMask, '21652', 'Closing'),
(@HordePandarenMask, @DruidMask, '22027', 'Remove Insignia'),
(@HordePandarenMask, @DruidMask, '22570', 'Maim'),
(@HordePandarenMask, @DruidMask, '22810', 'Opening - No Text'),
(@HordePandarenMask, @DruidMask, '22812', 'Bark Skin'),
(@HordePandarenMask, @DruidMask, '24248', 'Ferocious Bite'),
(@HordePandarenMask, @DruidMask, '24905', 'Moonkin Form(Passive)'),
(@HordePandarenMask, @DruidMask, '26979', 'Healing Touch'),
(@HordePandarenMask, @DruidMask, '26980', 'Regrowth'),
(@HordePandarenMask, @DruidMask, '26982', 'Rejuvenation'),
(@HordePandarenMask, @DruidMask, '26983', 'Tranquility'),
(@HordePandarenMask, @DruidMask, '26985', 'Wrath'),
(@HordePandarenMask, @DruidMask, '26986', 'Starfire'),
(@HordePandarenMask, @DruidMask, '26988', 'Moonfire'),
(@HordePandarenMask, @DruidMask, '26989', 'Entangling Roots'),
(@HordePandarenMask, @DruidMask, '26990', 'Mark of the Wild'),
(@HordePandarenMask, @DruidMask, '26991', 'Gift of the Wild'),
(@HordePandarenMask, @DruidMask, '26992', 'Thorns'),
-- (@HordePandarenMask, @DruidMask, '26993', 'Faerie Fire'), -- Removed?
(@HordePandarenMask, @DruidMask, '26994', 'Rebirth'),
(@HordePandarenMask, @DruidMask, '26995', 'Soothe Animal'),
(@HordePandarenMask, @DruidMask, '26996', 'Maul'),
(@HordePandarenMask, @DruidMask, '26997', 'Swipe (Bear)'),
(@HordePandarenMask, @DruidMask, '26998', 'Demoralizing Roar'),
-- (@HordePandarenMask, @DruidMask, '26999', 'Frenzied Regeneration'), -- Removed?
(@HordePandarenMask, @DruidMask, '27000', 'Claw'),
(@HordePandarenMask, @DruidMask, '27002', 'Shred'),
(@HordePandarenMask, @DruidMask, '27003', 'Rake'),
(@HordePandarenMask, @DruidMask, '27004', 'Cower'),
(@HordePandarenMask, @DruidMask, '27005', 'Ravage'),
(@HordePandarenMask, @DruidMask, '27006', 'Pounce'),
(@HordePandarenMask, @DruidMask, '27008', 'Rip'),
(@HordePandarenMask, @DruidMask, '27012', 'Hurricane'),
(@HordePandarenMask, @DruidMask, '27764', 'Fetish'),
(@HordePandarenMask, @DruidMask, '29166', 'Innervate'),
(@HordePandarenMask, @DruidMask, '33357', 'Dash'),
(@HordePandarenMask, @DruidMask, '33745', 'Lacerate'),
(@HordePandarenMask, @DruidMask, '33763', 'Lifebloom'),
(@HordePandarenMask, @DruidMask, '33786', 'Cyclone'),
(@HordePandarenMask, @DruidMask, '33948', 'Flight Form(Passive)'),
(@HordePandarenMask, @DruidMask, '34123', 'Tree of Life(Passive)'),
(@HordePandarenMask, @DruidMask, '40120', 'Swift Flight Form'),
(@HordePandarenMask, @DruidMask, '40121', 'Swift Flight Form(Passive)');
