-- [F-029] mod-arac: skillraceclassinfo: 0 inserts, 107 updates, 0 deletes

-- Changed values
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 21; -- Skill: 293 (Plate Mail)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 24; -- Skill: 272 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 26; -- Skill: 247 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 27; -- Skill: 356 (Fishing)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask /*, `flags` = 128, `skill_tier_id` = 0 */ WHERE `id` = 28; -- Skill: 182 (Herbalism)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 29; -- Skill: 186 (Mining)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 30; -- Skill: 393 (Skinning)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 34; -- Skill: 273 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 35; -- Skill: 262 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 36; -- Skill: 263 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 37; -- Skill: 264 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 38; -- Skill: 260 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @AllianceMask WHERE `id` = 40; -- Skill: 98 (Language: Common)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | (@HordeMask & ~@UndeadMask) WHERE `id` = 41; -- Skill: 98 (Language: Common)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @HordeMask WHERE `id` = 48; -- Skill: 109 (Language: Orcish)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @AllianceMask WHERE `id` = 49; -- Skill: 109 (Language: Orcish)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 54; -- Skill: 130 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 59; -- Skill: 96 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 62; -- Skill: 268 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 64; -- Skill: 269 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 65; -- Skill: 198 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 66; -- Skill: 246 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 73; -- Skill: 254 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 76; -- Skill: 241 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 79; -- Skill: 238 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 81; -- Skill: 239 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 83; -- Skill: 252 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 84; -- Skill: 139 (Language: Demon Tongue)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 85; -- Skill: 138 (Language: Draconic)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 87; -- Skill: 148 (Horse Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 88; -- Skill: 141 (Language: Old Tongue)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 89; -- Skill: 152 (Ram Riding)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 92; -- Skill: 150 (Tiger Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 93; -- Skill: 140 (Language: Titan)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 94; -- Skill: 149 (Wolf Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 97; -- Skill: 199 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 104; -- Skill: 353 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 105; -- Skill: 120 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 106; -- Skill: 245 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 108; -- Skill: 255 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 111; -- Skill: 244 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 112; -- Skill: 243 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 113; -- Skill: 258 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @GnomeMask WHERE `id` = 133; -- Skill: 46 (Guns [Dwarf, Tauren])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 137; -- Skill: 227 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 145; -- Skill: 413 (Mail)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 146; -- Skill: 413 (Mail)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 147; -- Skill: 414 (Leather)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 148; -- Skill: 415 (Cloth)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 149; -- Skill: 242 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 151; -- Skill: 416 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 155; -- Skill: 416 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 158; -- Skill: 416 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 159; -- Skill: 416 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 175; -- Skill: 418 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 178; -- Skill: 418 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 183; -- Skill: 418 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 186; -- Skill: 418 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 189; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 191; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 193; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 198; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 200; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 203; -- Skill: 420 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 204; -- Skill: 420 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 205; -- Skill: 420 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 241; -- Skill: 171 (Alchemy)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 243; -- Skill: 164 (Blacksmithing)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 244; -- Skill: 202 (Engineering)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 246; -- Skill: 433 (Shield)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 265; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 266; -- Skill: 419 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 268; -- Skill: 420 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 269; -- Skill: 420 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 270; -- Skill: 418 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 271; -- Skill: 416 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 272; -- Skill: 453 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 281; -- Skill: 333 (Enchanting)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 282; -- Skill: 185 (Cooking)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 284; -- Skill: 197 (Tailoring)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 328; -- Skill: 43 (Swords)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 330; -- Skill: 473 (Fist Weapons)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask, `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 403; -- Skill: 515 (N/A)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 441; -- Skill: 148 (Horse Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 442; -- Skill: 152 (Ram Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 443; -- Skill: 149 (Wolf Riding)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 446; -- Skill: 533 (Raptor Riding)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 461; -- Skill: 533 (Raptor Riding)
UPDATE `skillraceclassinfo` SET `class_mask` = `class_mask` | @AllClassMask WHERE `id` = 463; -- Skill: 554 (Undead Horsemanship)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 481; -- Skill: 150 (Tiger Riding)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 622; -- Skill: 172 (Two-Handed Axes)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @TaurenMask WHERE `id` = 624; -- Skill: 160 (Two-Handed Maces)
UPDATE `skillraceclassinfo` SET `race_mask` = 262111 WHERE `id` = 625; -- Skill: 160 (Two-Handed Maces) UNCHANGED?
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask /*, `class_mask` = 1 */ WHERE `id` = 628; -- Skill: 44 (Axes [Rogue])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 630; -- Skill: 44 (Axes [Warrior])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 632; -- Skill: 173 (Daggers [Rogue])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 634; -- Skill: 173 (Daggers [Warrior])
UPDATE `skillraceclassinfo` SET `race_mask` = 1691 WHERE `id` = 635; -- Skill: 46 (Guns [Rogue])
UPDATE `skillraceclassinfo` SET `race_mask` = 2962 WHERE `id` = 637; -- Skill: 54 (Maces [Warrior])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 638; -- Skill: 43 (Swords [Warrior])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask & ~(@TaurenMask | @DraeneiMask) WHERE `id` = 642; -- Skill: 173 (Daggers [Druid])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 644; -- Skill: 54 (Maces [Druid])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask, `class_mask` = `class_mask` | @AllClassMask /*, `skill_tier_id` = 41 */ WHERE `id` = 742; -- Skill: 673 (Language: Gutterspeak)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 865; -- Skill: 142 (Survival)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask /* , `flags` = 128, `skill_tier_id` = 0 */ WHERE `id` = 866; -- Skill: 755 (Jewelcrafting)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 886; -- Skill: 43 (Swords [Paladin])
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 899; -- Skill: 165 (Leatherworking)
