-- faction: 0 inserts, 89 updates, 0 deletes

-- Changed values
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 21;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 46;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 47;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 54;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 59;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 67;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 68;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HumanMask | @DwarfMask | @GnomeMask | @DraeneiMask | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 69;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 70;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 72;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 76;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 81;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 83;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 86;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 87;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 92;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 93;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 169;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 270;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 289;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 349;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 369;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 469;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 470;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 471;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 509;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 510;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 529;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 530;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 549;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 550;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 551;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 569;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 570;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 571;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 574;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 576;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 577;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 589;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 609;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 729;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 730;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 749;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 809;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 889;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 890;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 891;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 892;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 909;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 910;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 911;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 922;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask WHERE `id` = 930;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask WHERE `id` = 932;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 933;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask WHERE `id` = 934;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 935;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 936;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 941;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 942;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 946;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 947;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 970;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 978;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 989;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 990;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1012;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1015;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1031;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1037;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1038;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1050;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 1052;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 1064;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 1067;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1068;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1073;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1082;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1085;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask, `reputation_race_mask_3` = `reputation_race_mask_3` | @AlliancePandarenMask, `reputation_race_mask_4` = `reputation_race_mask_4` | @HordePandarenMask WHERE `id` = 1090;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1091;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1094;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1104;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1105;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1117;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1118;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask | @AlliancePandarenMask WHERE `id` = 1119;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @AlliancePandarenMask WHERE `id` = 1124;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AlliancePandarenMask, `reputation_race_mask_2` = `reputation_race_mask_2` | @HordePandarenMask WHERE `id` = 1126;
