-- charhairgeosets: 62 inserts, 0 updates, 6 deletes

-- New entries
DELETE FROM `charhairgeosets` WHERE `race` = @Goblin;
SET @CharHairGeosetsID = (SELECT COALESCE(MAX(id), 0) FROM `charhairgeosets`);
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    0, 19, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    1,  2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  0,  2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  1,  3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    2,  3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    3,  4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    4,  5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  2,  4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  3,  5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  4,  6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  5,  7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  6,  8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  7,  9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  8, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female,  9, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 10, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 11, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 12, 14, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 13, 15, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 14, 16, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 15, 17, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 16, 18, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    5,  6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    6,  7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    7,  8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    9, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   10, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,    8,  9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   11, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   12, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   13, 14, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   14, 15, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   15, 16, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   16, 17, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male,   17, 18, 0);
