-- creaturedisplayinfo: 12 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94217; -- male orc
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94217, 51, 0, 45428, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94218; -- female dwarf
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94218, 54, 0, 45429, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94219; -- female night elf
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94219, 56, 0, 45430, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94220; -- female troll
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94220, 186, 0, 45431, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94221; -- male draenei
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94221, 2248, 0, 45432, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94224; -- male undead
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94224, 57, 0, 45435, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94225; -- female undead
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94225, 58, 0, 45436, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
-- DELETE FROM `creaturedisplayinfo` WHERE `id` = 94228;
-- INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94228, 2298, 0, 14488, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
