-- [F-031] mod-azerothcore-high-elf: characterfacialhairstyles: 19 inserts, 43 updates, 0 deletes

-- New entries
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 1, 2, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 2, 3, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 3, 4, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 4, 5, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 5, 6, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 6, 7, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 7, 8, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 8, 9, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Male AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Male, 9, 10, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 1, 0, 2, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 2, 0, 3, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 3, 0, 4, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 4, 0, 5, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 5, 0, 6, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 6, 0, 7, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 7, 0, 8, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 8, 0, 9, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 9, 0, 10, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = @HighElf AND `gender` = @Female AND `variation_id` = 10;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (@HighElf, @Female, 10, 0, 11, 0, 0, 2);
