-- [F-031] mod-azerothcore-high-elf: emotestextsound: 720 inserts, 0 updates, 0 deletes

-- New entries
SET @EmotesTextSoundID = (SELECT COALESCE(MAX(id), 0) FROM `dbc`.`emotestextsound`);

DELETE FROM `emotestextsound` WHERE `id` BETWEEN 2501 AND 2553;
INSERT INTO `emotestextsound` (`id`, `emotes_text_id`, `race_id`, `sex_id`, `sound_id`) VALUES
(@EmotesTextSoundID := @EmotesTextSoundID +1, 14, @HighElf, @Female, 10025),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 14, @HighElf, @Male, 10026),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 19, @HighElf, @Female, 9636),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 19, @HighElf, @Male, 9654),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 21, @HighElf, @Female, 9632),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 21, @HighElf, @Male, 9656),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 26, @HighElf, @Female, 9641),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 26, @HighElf, @Male, 9657),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 55, @HighElf, @Female, 9635),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 55, @HighElf, @Male, 9662),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 66, @HighElf, @Female, 9638),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 66, @HighElf, @Male, 9665),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 67, @HighElf, @Female, 9637),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 67, @HighElf, @Male, 9666),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 85, @HighElf, @Female, 10573),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 85, @HighElf, @Male, 10575),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 97, @HighElf, @Female, 9639),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 97, @HighElf, @Male, 9671),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 102, @HighElf, @Female, 9635),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 102, @HighElf, @Male, 9662),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 104, @HighElf, @Female, 10032),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 104, @HighElf, @Male, 10033),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 106, @HighElf, @Female, 10574),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 106, @HighElf, @Male, 10576),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 183, @HighElf, @Female, 9634),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 183, @HighElf, @Male, 9669),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 264, @HighElf, @Female, 9644),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 264, @HighElf, @Male, 9672),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 303, @HighElf, @Female, 9623),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 303, @HighElf, @Male, 9663),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 304, @HighElf, @Female, 9624),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 304, @HighElf, @Male, 9664),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 305, @HighElf, @Female, 9625),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 305, @HighElf, @Male, 9655),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 306, @HighElf, @Female, 9626),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 306, @HighElf, @Male, 9658),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 307, @HighElf, @Female, 9627),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 307, @HighElf, @Male, 9653),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 323, @HighElf, @Female, 9628),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 323, @HighElf, @Male, 9667),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 324, @HighElf, @Female, 9629),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 324, @HighElf, @Male, 9660),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 325, @HighElf, @Female, 9630),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 325, @HighElf, @Male, 9673),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 326, @HighElf, @Female, 9631),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 326, @HighElf, @Male, 9661),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 327, @HighElf, @Female, 9633),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 327, @HighElf, @Male, 9668),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 328, @HighElf, @Female, 9642),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 328, @HighElf, @Male, 9659),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 329, @HighElf, @Female, 9643),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 329, @HighElf, @Male, 9670),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 453, @HighElf, @Female, 9640),
(@EmotesTextSoundID := @EmotesTextSoundID +1, 453, @HighElf, @Male, 9674);
