-- charsections: 456 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `charsections` WHERE `race` = @ZandalariTroll;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES
(32265, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_00.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32266, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32267, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_01.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32268, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32269, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_02.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32270, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32271, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_03.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32272, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32273, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_04.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32274, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32275, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_05.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32276, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32277, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_00.blp', '', @CharacterCreateMask, 0, 0),
(32278, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_01.blp', '', @CharacterCreateMask, 0, 1),
(32279, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_02.blp', '', @CharacterCreateMask, 0, 2),
(32280, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_03.blp', '', @CharacterCreateMask, 0, 3),
(32281, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_04.blp', '', @CharacterCreateMask, 0, 4),
(32282, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_05.blp', '', @CharacterCreateMask, 0, 5),
(32283, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_00.blp', '', @CharacterCreateMask, 1, 0),
(32284, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_01.blp', '', @CharacterCreateMask, 1, 1),
(32285, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_02.blp', '', @CharacterCreateMask, 1, 2),
(32286, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_03.blp', '', @CharacterCreateMask, 1, 3),
(32287, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_04.blp', '', @CharacterCreateMask, 1, 4),
(32288, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_05.blp', '', @CharacterCreateMask, 1, 5),
(32289, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_00.blp', '', @CharacterCreateMask, 2, 0),
(32290, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_01.blp', '', @CharacterCreateMask, 2, 1),
(32291, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_02.blp', '', @CharacterCreateMask, 2, 2),
(32292, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_03.blp', '', @CharacterCreateMask, 2, 3),
(32293, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_04.blp', '', @CharacterCreateMask, 2, 4),
(32294, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_05.blp', '', @CharacterCreateMask, 2, 5),
(32295, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_00.blp', '', @CharacterCreateMask, 3, 0),
(32296, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_01.blp', '', @CharacterCreateMask, 3, 1),
(32297, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_02.blp', '', @CharacterCreateMask, 3, 2),
(32298, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_03.blp', '', @CharacterCreateMask, 3, 3),
(32299, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_04.blp', '', @CharacterCreateMask, 3, 4),
(32300, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_05.blp', '', @CharacterCreateMask, 3, 5),
(32301, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_00.blp', '', @CharacterCreateMask, 4, 0),
(32302, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_01.blp', '', @CharacterCreateMask, 4, 1),
(32303, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_02.blp', '', @CharacterCreateMask, 4, 2),
(32304, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_03.blp', '', @CharacterCreateMask, 4, 3),
(32305, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_04.blp', '', @CharacterCreateMask, 4, 4),
(32306, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_05.blp', '', @CharacterCreateMask, 4, 5),
(32307, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_00.blp', '', @CharacterCreateMask, 4, 0),
(32308, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower05_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_01.blp', '', @CharacterCreateMask, 5, 1),
(32309, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower05_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_02.blp', '', @CharacterCreateMask, 5, 2),
(32310, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower05_03.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_03.blp', '', @CharacterCreateMask, 5, 3),
(32311, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower05_04.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_04.blp', '', @CharacterCreateMask, 5, 4),
(32312, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower05_05.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper05_05.blp', '', @CharacterCreateMask, 5, 5),
(32313, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 0, 0),
(32314, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 0, 1),
(32315, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 0, 2),
(32316, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 0, 3),
(32317, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 0, 4),
(32318, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 0, 5),
(32319, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 1, 0),
(32320, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 1, 1),
(32321, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 1, 2),
(32322, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 1, 3),
(32323, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 1, 4),
(32324, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 1, 5),
(32325, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 2, 0),
(32326, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 2, 1),
(32327, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 2, 2),
(32328, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 2, 3),
(32329, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 2, 4),
(32330, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 2, 5),
(32331, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 3, 0),
(32332, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 3, 1),
(32333, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 3, 2),
(32334, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 3, 3),
(32335, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 3, 4),
(32336, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 3, 5),
(32337, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 4, 0),
(32338, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 4, 1),
(32339, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 4, 2),
(32340, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 4, 3),
(32341, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 4, 4),
(32342, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 4, 5),
(32343, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 5, 0),
(32344, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 5, 1),
(32345, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 5, 2),
(32346, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 5, 3),
(32347, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 5, 4),
(32348, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 5, 5),
(32349, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 6, 0),
(32350, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 6, 1),
(32351, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 6, 2),
(32352, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 6, 3),
(32353, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 6, 4),
(32354, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 6, 5),
(32355, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '',17, 7, 0),
(32356, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '',17, 7, 1),
(32357, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '',17, 7, 2),
(32358, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_03.blp', '', '',17, 7, 3),
(32359, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_04.blp', '', '',17, 7, 4),
(32360, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_05.blp', '', '',17, 7, 5),
(32361, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32362, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32363, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32364, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32365, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32366, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32367, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 6),
(32368, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 0),
(32369, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 1),
(32370, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 2),
(32371, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 3),
(32372, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 4),
(32373, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 5),
(32374, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 6),
(32375, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 0),
(32376, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 1),
(32377, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 2),
(32378, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 3),
(32379, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 4),
(32380, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 5),
(32381, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 6),
(32382, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 0),
(32383, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 1),
(32384, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 2),
(32385, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 3),
(32386, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 4),
(32387, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 5),
(32388, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 6),
(32389, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 0),
(32390, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 1),
(32391, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 2),
(32392, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 3),
(32393, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 4),
(32394, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 5),
(32395, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 6),
(32396, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 0),
(32397, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 1),
(32398, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 2),
(32399, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 3),
(32400, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 4),
(32401, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 5),
(32402, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 6),
(32403, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 0),
(32404, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 1),
(32405, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 2),
(32406, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 3),
(32407, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 4),
(32408, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 5),
(32409, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 6),
(32410, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 0),
(32411, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 1),
(32412, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 2),
(32413, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 3),
(32414, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 4),
(32415, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 5),
(32416, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 7, 6),
(32417, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_00.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32418, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32419, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_01.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32420, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32421, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_02.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32422, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32423, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_03.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32424, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32425, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_04.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32426, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32427, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_05.blp', '', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32428, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32429, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_00.blp', '', @CharacterCreateMask, 0, 0),
(32430, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_01.blp', '', @CharacterCreateMask, 0, 1),
(32431, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_02.blp', '', @CharacterCreateMask, 0, 2),
(32432, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_03.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_03.blp', '', @CharacterCreateMask, 0, 3),
(32433, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_04.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_04.blp', '', @CharacterCreateMask, 0, 4),
(32434, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_05.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_05.blp', '', @CharacterCreateMask, 0, 5),
(32435, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_00.blp', '', @CharacterCreateMask, 1, 0),
(32436, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_01.blp', '', @CharacterCreateMask, 1, 1),
(32437, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_02.blp', '', @CharacterCreateMask, 1, 2),
(32438, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_03.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_03.blp', '', @CharacterCreateMask, 1, 3),
(32439, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_04.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_04.blp', '', @CharacterCreateMask, 1, 4),
(32440, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_05.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_05.blp', '', @CharacterCreateMask, 1, 5),
(32441, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_00.blp', '', @CharacterCreateMask, 2, 0),
(32442, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_01.blp', '', @CharacterCreateMask, 2, 1),
(32443, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_02.blp', '', @CharacterCreateMask, 2, 2),
(32444, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_03.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_03.blp', '', @CharacterCreateMask, 2, 3),
(32445, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_04.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_04.blp', '', @CharacterCreateMask, 2, 4),
(32446, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_05.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_05.blp', '', @CharacterCreateMask, 2, 5),
(32447, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_00.blp', '', @CharacterCreateMask, 3, 0),
(32448, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_01.blp', '', @CharacterCreateMask, 3, 1),
(32449, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_02.blp', '', @CharacterCreateMask, 3, 2),
(32450, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_03.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_03.blp', '', @CharacterCreateMask, 3, 3),
(32451, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_04.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_04.blp', '', @CharacterCreateMask, 3, 4),
(32452, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_05.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_05.blp', '', @CharacterCreateMask, 3, 5),
(32453, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_00.blp', '', @CharacterCreateMask, 4, 0),
(32454, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_01.blp', '', @CharacterCreateMask, 4, 1),
(32455, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_02.blp', '', @CharacterCreateMask, 4, 2),
(32456, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_03.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_03.blp', '', @CharacterCreateMask, 4, 3),
(32457, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_04.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_04.blp', '', @CharacterCreateMask, 4, 4),
(32458, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_05.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_05.blp', '', @CharacterCreateMask, 4, 5),
(32459, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 0, 0),
(32460, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 0, 1),
(32461, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 0, 2),
(32462, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 0, 3),
(32463, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 0, 4),
(32464, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 0, 5),
(32465, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 1, 0),
(32466, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 1, 1),
(32467, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 1, 2),
(32468, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 1, 3),
(32469, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 1, 4),
(32470, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 1, 5),
(32471, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 2, 0),
(32472, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 2, 1),
(32473, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 2, 2),
(32474, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 2, 3),
(32475, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 2, 4),
(32476, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 2, 5),
(32477, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 3, 0),
(32478, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 3, 1),
(32479, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 3, 2),
(32480, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 3, 3),
(32481, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 3, 4),
(32482, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 3, 5),
(32483, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 4, 0),
(32484, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 4, 1),
(32485, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 4, 2),
(32486, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 4, 3),
(32487, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 4, 4),
(32488, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 4, 5),
(32489, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 5, 0),
(32490, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 5, 1),
(32491, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 5, 2),
(32492, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 5, 3),
(32493, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 5, 4),
(32494, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 5, 5),
(32495, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 6, 0),
(32496, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 6, 1),
(32497, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 6, 2),
(32498, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 6, 3),
(32499, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 6, 4),
(32500, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 6, 5),
(32501, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 7, 0),
(32502, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 7, 1),
(32503, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 7, 2),
(32504, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 7, 3),
(32505, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 7, 4),
(32506, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 7, 5),
(32507, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 8, 0),
(32508, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 8, 1),
(32509, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 8, 2),
(32510, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 8, 3),
(32511, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 8, 4),
(32512, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 8, 5),
(32513, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 9, 0),
(32514, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 9, 1),
(32515, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 9, 2),
(32516, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 9, 3),
(32517, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 9, 4),
(32518, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 9, 5),
(32519, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '',17, 10, 0),
(32520, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '',17, 10, 1),
(32521, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '',17, 10, 2),
(32522, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_03.blp', '', '',17, 10, 3),
(32523, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_04.blp', '', '',17, 10, 4),
(32524, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_05.blp', '', '',17, 10, 5),
(32525, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 0),
(32526, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 1),
(32527, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 2),
(32528, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 3),
(32529, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 4),
(32530, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 5),
(32531, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 0, 6),
(32532, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 0),
(32533, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 1),
(32534, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 2),
(32535, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 3),
(32536, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 4),
(32537, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 5),
(32538, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 1, 6),
(32539, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 0),
(32540, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 1),
(32541, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 2),
(32542, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 3),
(32543, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 4),
(32544, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 5),
(32545, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 2, 6),
(32546, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 0),
(32547, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 1),
(32548, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 2),
(32549, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 3),
(32550, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 4),
(32551, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 5),
(32552, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 3, 6),
(32553, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 0),
(32554, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 1),
(32555, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 2),
(32556, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 3),
(32557, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 4),
(32558, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 5),
(32559, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 4, 6),
(32560, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 0),
(32561, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 1),
(32562, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 2),
(32563, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 3),
(32564, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 4),
(32565, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 5),
(32566, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 5, 6),
(32567, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 0),
(32568, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 1),
(32569, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 2),
(32570, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 3),
(32571, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 4),
(32572, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 5),
(32573, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @RegularMask, 6, 6),
(32574, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 19),
(32575, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\ZandalariTrollmalenakedpelvisskin.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 19),
(32576, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 19),
(32577, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 19),
(32578, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 19),
(32579, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 19),
(32580, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_00.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 19),
(32581, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 20),
(32582, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 20),
(32583, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 20),
(32584, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 20),
(32585, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 20),
(32586, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 20),
(32587, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_01.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 20),
(32588, @ZandalariTroll, @Male, @Skin, 'Character\\zandalaritroll\\male\\zandalaritrollMaleSkin00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 21),
(32589, @ZandalariTroll, @Male, @Underwear, 'Character\\zandalaritroll\\male\\zandalaritrollMaleNakedPelvisSkin.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 21),
(32590, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower00_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper00_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 21),
(32591, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower01_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper01_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 21),
(32592, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower02_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper02_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 21),
(32593, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower03_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper03_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 21),
(32594, @ZandalariTroll, @Male, @Face, 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceLower04_02.blp', 'Character\\zandalaritroll\\male\\zandalaritrollMaleFaceUpper04_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 21),
(32595, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 10),
(32596, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32597, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32598, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 10),
(32599, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 11),
(32600, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 12),
(32601, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 10),
(32602, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 11),
(32603, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 12),
(32604, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 10),
(32605, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 11),
(32606, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 12),
(32607, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 10),
(32608, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 11),
(32609, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 12),
(32610, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 10),
(32611, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 11),
(32612, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 12),
(32613, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 10),
(32614, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 11),
(32615, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 12),
(32616, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 10),
(32617, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 11),
(32618, @ZandalariTroll, @Male, @Hair, 'Character\\zandalaritroll\\male\\zandalaritrollmalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 12),
(32619, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 10),
(32620, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32621, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32622, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 10),
(32623, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 11),
(32624, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 12),
(32625, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 10),
(32626, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 11),
(32627, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 12),
(32628, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 10),
(32629, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 11),
(32630, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 12),
(32631, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 10),
(32632, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 11),
(32633, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 12),
(32634, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 10),
(32635, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 11),
(32636, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 12),
(32637, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 10),
(32638, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 11),
(32639, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 12),
(32640, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 10),
(32641, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 11),
(32642, @ZandalariTroll, @Male, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 12),
(32643, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32644, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32645, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32646, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 11),
(32647, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 11),
(32648, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 11),
(32649, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 11),
(32650, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower05_00.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper05_00.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 11),
(32651, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32652, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32653, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32654, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 12),
(32655, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 12),
(32656, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 12),
(32657, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 12),
(32658, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower05_01.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper05_01.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 12),
(32659, @ZandalariTroll, @Female, @Skin, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleSkin00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 13),
(32660, @ZandalariTroll, @Female, @Underwear, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedPelvis.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleNakedTorso.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 13),
(32661, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower00_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper00_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 13),
(32662, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower01_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper01_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 13),
(32663, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower02_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper02_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 13),
(32664, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower03_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper03_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 13),
(32665, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower04_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper04_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 13),
(32666, @ZandalariTroll, @Female, @Face, 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceLower05_02.blp', 'Character\\zandalaritroll\\female\\zandalaritrollFemaleFaceUpper05_02.blp', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 13),
(32667, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 10),
(32668, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32669, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32670, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 10),
(32671, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 11),
(32672, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 12),
(32673, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 10),
(32674, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 11),
(32675, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 12),
(32676, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 10),
(32677, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 11),
(32678, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 12),
(32679, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 10),
(32680, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 11),
(32681, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 12),
(32682, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 10),
(32683, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 11),
(32684, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 12),
(32685, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 10),
(32686, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 11),
(32687, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 12),
(32688, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 10),
(32689, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 11),
(32690, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 7, 12),
(32691, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 8, 10),
(32692, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 8, 11),
(32693, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 8, 12),
(32694, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 9, 10),
(32695, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 9, 11),
(32696, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 9, 12),
(32697, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_00.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 10, 10),
(32698, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_01.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 10, 11),
(32699, @ZandalariTroll, @Female, @Hair, 'Character\\zandalaritroll\\female\\zandalaritrollfemalehair00_02.blp', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 10, 12),
(32700, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 10),
(32701, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 11),
(32702, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 0, 12),
(32703, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 10),
(32704, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 11),
(32705, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 1, 12),
(32706, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 10),
(32707, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 11),
(32708, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 2, 12),
(32709, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 10),
(32710, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 11),
(32711, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 3, 12),
(32712, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 10),
(32713, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 11),
(32714, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 4, 12),
(32715, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 10),
(32716, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 11),
(32717, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 5, 12),
(32718, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 10),
(32719, @ZandalariTroll, @Female, @FacialHair, '', '', '', @CharacterCreateMask | @DeathKnightTextureMask, 6, 11),
(32720, @ZandalariTroll, @Female, @FacialHair, '', '', '', 5, 6, 12);
