-- faction: 2 inserts, 91 updates, 0 deletes

-- new entries
DELETE FROM `faction` WHERE `id` IN (@KulTiranPlayer, @KulTiranFaction);
INSERT INTO `faction` (`id`, `reputation_index`, `reputation_race_mask_1`, `reputation_race_mask_2`, `reputation_race_mask_3`, `reputation_race_mask_4`, `reputation_class_mask_1`, `reputation_class_mask_2`, `reputation_class_mask_3`, `reputation_class_mask_4`, `reputation_base_1`, `reputation_base_2`, `reputation_base_3`, `reputation_base_4`, `reputation_flags_1`, `reputation_flags_2`, `reputation_flags_3`, `reputation_flags_4`, `parent_faction_id`, `parent_faction_mod_1`, `parent_faction_mod_2`, `parent_faction_cap_1`, `parent_faction_cap_2`, `name_enus`, `name_kokr`, `name_frfr`, `name_dede`, `name_zhcn`, `name_zhtw`, `name_eses`, `name_esmx`, `name_ruru`, `name_jajp`, `name_ptpt`, `name_itit`, `name_unused_1`, `name_unused_2`, `name_unused_3`, `name_unused_4`, `name_flags`, `description_enus`, `description_kokr`, `description_frfr`, `description_dede`, `description_zhcn`, `description_zhtw`, `description_eses`, `description_esmx`, `description_ruru`, `description_jajp`, `description_ptpt`, `description_itit`, `description_unused_1`, `description_unused_2`, `description_unused_3`, `description_unused_4`, `description_flags`) VALUES
(@KulTiranPlayer, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1.0000000000000000', '1.0000000000000000', 5, 5, '"PLAYER"," KulTiran"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188),
(@KulTiranFaction, @KulTiranFactionRepIndex, @AllianceMask & ~@KulTiranMask, @HordeMask, @KulTiranMask, 0, 0, 0, 0, 0, 3100, -42000, 4000, 0, 273, 6, 17, 0, 469, '1.0000000000000000', '0.2500000000000000', 7, 5, 'Kul Tiras', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'The kingdom of Kul Tiras.', '쿨 티라스 왕국입니다.', 'Le royaume de Kul Tiras.', 'Das Königreich Kul Tiras.', '库尔提拉斯王国。', '庫爾提拉斯王國。', 'El reino de Kul Tiras.', 'El reino de Kul Tiras.', '', '', '', '', '', '', '', '', 16712190);

-- Changed values
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBootyBay;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBlacksmithingArmorsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionIronforge;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionGnomereganExiles;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionThoriumBrotherhood;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionHorde;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionUndercity;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionDarnassus;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionSyndicate;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionStormwind;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionOrgrimmar;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionThunderBluff;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionLeatherworkingElemental;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionLeatherworkingDragonscale;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBloodsailBuccaneers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionGelkisClanCentaur;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionMagramClanCentaur;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionSteamwheedleCartel;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionZandalarTribe;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBlacksmithingWeaponsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionRavenholdt;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionGadgetzan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionAlliance;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionRatchet;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionWildhammerClan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheLeagueofArathor;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTheDefilers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionArgentDawn;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionDarkspearTrolls530;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionLeatherworkingTribal;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionEngineeringGoblin;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionEngineeringGnome;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBlacksmithingHammersmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBlacksmithingAxesmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBlacksmithingSwordsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionCaerDarrow;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTimbermawHold;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionEverlook;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionWintersaberTrainers;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionCenarionCircle;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionFrostwolfClan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionStormpikeGuard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionHydraxianWaterlords;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionShendralar;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionWarsongOutriders;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionSilverwingSentinels;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionAllianceForces;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionHordeForces;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionDarkmoonFaire;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionBroodofNozdormu;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionSilvermoonCity;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTranquillien;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionExodar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheAldor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheConsortium;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheScryers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheShatar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionShattrathCity;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTheMaghar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionCenarionExpedition;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionHonorHold;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionThrallmar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionSporeggar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionKurenai;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionKeepersofTime;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheScaleoftheSands;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionAshtongueDeathsworn;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionNetherwing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionShatariSkyguard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionAllianceVanguard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionOgrila;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionValianceExpedition;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionHordeExpedition;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTheTaunka;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTheHandofVengeance;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionExplorersLeague;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheKaluak;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = 1082; -- REUSE? Maybe 1077: Shattered Sun Offensive?
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionWarsongOffensive;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask, `reputation_race_mask_3` = `reputation_race_mask_3` | @KulTiranMask WHERE `id` = @FactionKirinTor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheWyrmrestAccord;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheSilverCovenant;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionFrenzyheartTribe;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheOracles;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionSholazarBasin;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionClassic;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheSonsofHodir;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @KulTiranMask WHERE `id` = @FactionTheSunreavers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheFrostborn;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheAldor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @KulTiranMask WHERE `id` = @FactionTheScryers;
