SET @Broken     = (SELECT COALESCE(MAX(id), 0) FROM `chrraces`) +1;
SET @BrokenMask = 1 << (@Broken - 1);
SET @BrokenHelmetMask = 1 << @Broken;
SET @BrokenMaleModel = 2367;
SET @BrokenFemaleModel = 2368;
SET @BrokenMaleDisplay = (SELECT COALESCE(MAX(id), 0) FROM `creaturedisplayinfo`) +1;
SET @BrokenFemaleDisplay = @BrokenMaleDisplay +1;
SET @BrokenMaleDisplayExtra = (SELECT COALESCE(MAX(id), 0) FROM `creaturedisplayinfoextra`) +1;
SET @BrokenFemaleDisplayExtra = @BrokenMaleDisplayExtra +1;
SET @BrokenRacials = (SELECT COALESCE(MAX(id), 0) FROM `skillline`) +1;
SET @AllianceMask = @AllianceMask | @BrokenMask;
SET @BrokenPlayer = (SELECT COALESCE(MAX(id), 0) FROM `faction`) +1;
SET @BrokenFaction = @BrokenPlayer +1;
SET @BrokenFactionRepIndex = (SELECT COALESCE(MAX(reputation_index), 0) FROM `faction`) +1;
SET @BrokenFactionTemplate = (SELECT COALESCE(MAX(id), 0) FROM `factiontemplate`) +1;
SET @BrokenAchievement = (SELECT COALESCE(MAX(id), 0) FROM `achievements`) +1;
SET @BrokenCriteria1 = (SELECT COALESCE(MAX(id), 0) FROM `achievement_criteria`) +1; -- Achievement 246: Know Thy Enemy
SET @BrokenCriteria2 = @BrokenCriteria1 +1; -- Achievement 2422: Shake Your Bunny-Maker
SET @BrokenCriteria3 = @BrokenCriteria1 +2; -- Achievement 291: Check Your Head
SET @BrokenCriteria4 = @BrokenCriteria1 +3; -- @BrokenAchievement: Realm First! Level 80 Broken
