-- factiontemplate: 0 inserts, 274 updates, 0 deletes

-- Changed values
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 2;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 3;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 4;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 5;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 6;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 10;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 11;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 12;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 23;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 29;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 33;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 53;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 55;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 56;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 57;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 64;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 68;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 71;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 76;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 79;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 80;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 83;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 84;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 85;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 88;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 96;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 98;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 101;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 102;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 104;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 105;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 106;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 115;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 116;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 118;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 122;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 123;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 124;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 125;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 126;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 149;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 150;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 151;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 208;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 209;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 210;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 231;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 232;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 371;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 412;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 534;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 554;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 655;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 694;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 714;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 774;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 775;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 874;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 875;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 876;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 877;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 894;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 995;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1034;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1054;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1055;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1074;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1075;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1076;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1077;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1078;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1096;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1097;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1134;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1154;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1174;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1214;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1215;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1216;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1217;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1274;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1275;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1314;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1315;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1334;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1335;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1414;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1415;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1494;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1495;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1496;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1514;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1515;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1534;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1554;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1575;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1576;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1577;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1594;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1595;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1596;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1597;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1598;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1599;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1600;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1602;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1603;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1604;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1606;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1607;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1610;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1611;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1612;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1618;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1619;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1621;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1622;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1623;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1627;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1628;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1629;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1630;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1636;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1637;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1638;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1639;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1640;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1641;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1642;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1644;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1645;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1646;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1647;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1648;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1649;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1650;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1651;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1652;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1653;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1654;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1655;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1656;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1657;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1658;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1666;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1667;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1668;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1669;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1670;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1671;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1685;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1686;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1694;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1695;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1698;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1699;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1700;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1701;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1702;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1714;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1721;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1722;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1723;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1724;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1729;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1732;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1733;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1734;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1735;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1737;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1745;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1752;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1753;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1754;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1755;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1756;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1757;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1758;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1759;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1760;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1762;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1763;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1764;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1765;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1789;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1793;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1801;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1802;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1803;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1804;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1819;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1835;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1883;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1891;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1892;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1893;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1897;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1898;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1899;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1900;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1901;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1918;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1920;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1921;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1922;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1923;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1926;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1927;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1928;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1929;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1933;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1934;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1935;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 1948;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 1951;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1973;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1974;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1975;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1976;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1977;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1978;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1979;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1980;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 1981;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1988;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 1991;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1993;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 1994;
UPDATE `factiontemplate` SET `friend_group` = 7, `enemy_group` = 0 WHERE `id` = 1995;
UPDATE `factiontemplate` SET `friend_group` = 7, `enemy_group` = 0 WHERE `id` = 1997;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2004;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2005;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2018;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2019;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2020;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2021;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 2023;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 2024;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2025;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2026;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2027;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 2031;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2032;
UPDATE `factiontemplate` SET `enemy_group` = 0 WHERE `id` = 2034;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2035;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2037;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2040;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2042;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2043;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2044;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2045;
UPDATE `factiontemplate` SET `friend_group` = 6 WHERE `id` = 2046;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2055;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2056;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2068;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2069;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2080;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2121;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2122;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2123;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 2129;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 2130;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2132;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 8 WHERE `id` = 2142;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2143;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2145;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2155;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2176;
UPDATE `factiontemplate` SET `friend_group` = 6, `enemy_group` = 0 WHERE `id` = 2178;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2209;
UPDATE `factiontemplate` SET `enemy_group` = 1 WHERE `id` = 2212;
UPDATE `factiontemplate` SET `friend_group` = 7, `enemy_group` = 0 WHERE `id` = 2235;
UPDATE `factiontemplate` SET `friend_group` = 7, `enemy_group` = 0 WHERE `id` = 2236;
