INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Worgen Warrior
(@WorgenMask, @WarriorMask, '668', 'Language Common'),
(@WorgenMask, @WarriorMask, '68975', 'Viciousness'),
(@WorgenMask, @WarriorMask, '68976', 'Aberration'),
(@WorgenMask, @WarriorMask, '68978', 'Flayer'),
(@WorgenMask, @WarriorMask, '68992', 'Darkflight'),
(@WorgenMask, @WarriorMask, '78', 'Heroic Strike'),
(@WorgenMask, @WarriorMask, '81', 'Dodge'),
(@WorgenMask, @WarriorMask, '107', 'Block'),
(@WorgenMask, @WarriorMask, '196', 'One-Handed Axes'),
(@WorgenMask, @WarriorMask, '198', 'One-Handed Maces'),
(@WorgenMask, @WarriorMask, '201', 'One-Handed Swords'),
(@WorgenMask, @WarriorMask, '203', 'Unarmed'),
(@WorgenMask, @WarriorMask, '204', 'Defense'),
(@WorgenMask, @WarriorMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @WarriorMask, '2382', 'Generic'),
(@WorgenMask, @WarriorMask, '2457', 'Battle Stance'),
(@WorgenMask, @WarriorMask, '2479', 'Honorless Target'),
(@WorgenMask, @WarriorMask, '3050', 'Detect'),
(@WorgenMask, @WarriorMask, '3365', 'Opening'),
(@WorgenMask, @WarriorMask, '5301', 'Defensive State(DND)'),
(@WorgenMask, @WarriorMask, '6233', 'Closing'),
(@WorgenMask, @WarriorMask, '6246', 'Closing'),
(@WorgenMask, @WarriorMask, '6247', 'Opening'),
(@WorgenMask, @WarriorMask, '6477', 'Opening'),
(@WorgenMask, @WarriorMask, '6478', 'Opening'),
(@WorgenMask, @WarriorMask, '6603', 'Attack'),
(@WorgenMask, @WarriorMask, '7266', 'Duel'),
(@WorgenMask, @WarriorMask, '7267', 'Grovel'),
(@WorgenMask, @WarriorMask, '7355', 'Stuck'),
(@WorgenMask, @WarriorMask, '7376', 'Defensive Stance Passive'),
(@WorgenMask, @WarriorMask, '7381', 'Berserker Stance Passive'),
(@WorgenMask, @WarriorMask, '8386', 'Attacking'),
(@WorgenMask, @WarriorMask, '8737', 'Mail'),
(@WorgenMask, @WarriorMask, '9077', 'Leather'),
(@WorgenMask, @WarriorMask, '9078', 'Cloth'),
(@WorgenMask, @WarriorMask, '9116', 'Shield'),
(@WorgenMask, @WarriorMask, '9125', 'Generic'),
(@WorgenMask, @WarriorMask, '21156', 'Battle Stance Passive'),
(@WorgenMask, @WarriorMask, '21651', 'Opening'),
(@WorgenMask, @WarriorMask, '21652', 'Closing'),
(@WorgenMask, @WarriorMask, '22027', 'Remove Insignia'),
(@WorgenMask, @WarriorMask, '22810', 'Opening - No Text'),
(@WorgenMask, @WarriorMask, '32215', 'Victorious State'),
(@WorgenMask, @WarriorMask, '2048', 'Battle Shout'),
(@WorgenMask, @WarriorMask, '30324', 'Heroic Strike'),
(@WorgenMask, @WarriorMask, '11578', 'Charge'),
(@WorgenMask, @WarriorMask, '25208', 'Rend'),
(@WorgenMask, @WarriorMask, '25264', 'Thunder Clap'),
(@WorgenMask, @WarriorMask, '2687', 'Bloodrage'),
(@WorgenMask, @WarriorMask, '71', 'Defensive Stance'),
(@WorgenMask, @WarriorMask, '25225', 'Sunder Armor'),
(@WorgenMask, @WarriorMask, '355', 'Taunt'),
(@WorgenMask, @WarriorMask, '11585', 'Overpower'),
(@WorgenMask, @WarriorMask, '29704', 'Shield Bash'),
(@WorgenMask, @WarriorMask, '25203', 'Demoralizing Shout'),
(@WorgenMask, @WarriorMask, '30357', 'Revenge'),
(@WorgenMask, @WarriorMask, '25266', 'Mocking Blow'),
(@WorgenMask, @WarriorMask, '2565', 'Shield Block'),
(@WorgenMask, @WarriorMask, '676', 'Disarm'),
(@WorgenMask, @WarriorMask, '25231', 'Cleave'),
(@WorgenMask, @WarriorMask, '20230', 'Retaliation'),
(@WorgenMask, @WarriorMask, '5246', 'Intimidating Shout'),
(@WorgenMask, @WarriorMask, '25236', 'Execute'),
(@WorgenMask, @WarriorMask, '1161', 'Challenging Shout'),
(@WorgenMask, @WarriorMask, '871', 'Shield Wall'),
(@WorgenMask, @WarriorMask, '2458', 'Berserker Stance'),
(@WorgenMask, @WarriorMask, '25275', 'Intercept'),
(@WorgenMask, @WarriorMask, '25242', 'Slam'),
(@WorgenMask, @WarriorMask, '18499', 'Berserker Rage'),
(@WorgenMask, @WarriorMask, '1680', 'Whirlwind'),
(@WorgenMask, @WarriorMask, '6554', 'Pummel'),
(@WorgenMask, @WarriorMask, '1719', 'Recklessness'),
(@WorgenMask, @WarriorMask, '34428', 'Victory Rush'),
(@WorgenMask, @WarriorMask, '23920', 'Spell Reflection'),
(@WorgenMask, @WarriorMask, '469', 'Commanding Shout'),
(@WorgenMask, @WarriorMask, '3411', 'Intervene'),
(@WorgenMask, @WarriorMask, '25212', 'Hamstring'), -- Only 9?
(@WorgenMask, @WarriorMask, '674', 'Dual Wield'),
(@WorgenMask, @WarriorMask, '750', 'Plate Armor'), -- Only 19?
(@WorgenMask, @WarriorMask, '12678', 'Stance Mastery'), -- Only 9?

-- Worgen Hunter
(@WorgenMask, @HunterMask, '668', 'Language Common'),
(@WorgenMask, @HunterMask, '68975', 'Viciousness'),
(@WorgenMask, @HunterMask, '68976', 'Aberration'),
(@WorgenMask, @HunterMask, '68978', 'Flayer'),
(@WorgenMask, @HunterMask, '68992', 'Darkflight'),
(@WorgenMask, @HunterMask, '75', 'Auto Shot'),
(@WorgenMask, @HunterMask, '81', 'Dodge'),
(@WorgenMask, @HunterMask, '196', 'One-Handed Axes'),
(@WorgenMask, @HunterMask, '203', 'Unarmed'),
(@WorgenMask, @HunterMask, '204', 'Defense'),
(@WorgenMask, @HunterMask, '264', 'Bows'),
(@WorgenMask, @HunterMask, '266', 'Guns'),
(@WorgenMask, @HunterMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @HunterMask, '883', 'Call Pet'),
(@WorgenMask, @HunterMask, '982', 'Revive Pet'),
(@WorgenMask, @HunterMask, '1002', 'Eyes of the Beast'),
(@WorgenMask, @HunterMask, '1462', 'Beast Lore'),
(@WorgenMask, @HunterMask, '1494', 'Track Beasts'),
(@WorgenMask, @HunterMask, '1515', 'Tame Beast'),
(@WorgenMask, @HunterMask, '1543', 'Flare'),
(@WorgenMask, @HunterMask, '2382', 'Generic'),
(@WorgenMask, @HunterMask, '2479', 'Honorless Target'),
(@WorgenMask, @HunterMask, '2641', 'Dismiss Pet'),
(@WorgenMask, @HunterMask, '2973', 'Raptor Strike'),
(@WorgenMask, @HunterMask, '3043', 'Scorpid Sting'),
(@WorgenMask, @HunterMask, '3045', 'Rapid Fire'),
(@WorgenMask, @HunterMask, '3050', 'Detect'),
(@WorgenMask, @HunterMask, '3365', 'Opening'),
(@WorgenMask, @HunterMask, '5116', 'Concussive Shot'),
(@WorgenMask, @HunterMask, '5118', 'Aspect of the Cheetah'),
(@WorgenMask, @HunterMask, '5384', 'Feign Death'),
(@WorgenMask, @HunterMask, '6197', 'Eagle Eye'),
(@WorgenMask, @HunterMask, '6233', 'Closing'),
(@WorgenMask, @HunterMask, '6246', 'Closing'),
(@WorgenMask, @HunterMask, '6247', 'Opening'),
(@WorgenMask, @HunterMask, '6477', 'Opening'),
(@WorgenMask, @HunterMask, '6478', 'Opening'),
(@WorgenMask, @HunterMask, '6603', 'Attack'),
(@WorgenMask, @HunterMask, '6991', 'Feed Pet'),
(@WorgenMask, @HunterMask, '7266', 'Duel'),
(@WorgenMask, @HunterMask, '7267', 'Grovel'),
(@WorgenMask, @HunterMask, '7355', 'Stuck'),
(@WorgenMask, @HunterMask, '8386', 'Attacking'),
(@WorgenMask, @HunterMask, '9077', 'Leather'),
(@WorgenMask, @HunterMask, '9078', 'Cloth'),
(@WorgenMask, @HunterMask, '9125', 'Generic'),
(@WorgenMask, @HunterMask, '13159', 'Aspect of the Pack'),
(@WorgenMask, @HunterMask, '13161', 'Aspect of the Beast'),
(@WorgenMask, @HunterMask, '13163', 'Aspect of the Monkey'),
(@WorgenMask, @HunterMask, '13358', 'Defensive State(DND)'),
(@WorgenMask, @HunterMask, '13809', 'Frost Trap'),
(@WorgenMask, @HunterMask, '14268', 'Alliance Flag'), -- What?
(@WorgenMask, @HunterMask, '14311', 'Freezing Trap'),
(@WorgenMask, @HunterMask, '14325', 'Hunters Mark'),
(@WorgenMask, @HunterMask, '14327', 'Scare Beast'),
(@WorgenMask, @HunterMask, '19801', 'Tranquilizing Shot'),
(@WorgenMask, @HunterMask, '19878', 'Track Demons'),
(@WorgenMask, @HunterMask, '19879', 'Track Dragonkin'),
(@WorgenMask, @HunterMask, '19880', 'Track Elementals'),
(@WorgenMask, @HunterMask, '19882', 'Track Giants'),
(@WorgenMask, @HunterMask, '19883', 'Track Humanoids'),
(@WorgenMask, @HunterMask, '19884', 'Track Undead'),
(@WorgenMask, @HunterMask, '19885', 'Track Hidden'),
(@WorgenMask, @HunterMask, '21651', 'Opening'),
(@WorgenMask, @HunterMask, '21652', 'Closing'),
(@WorgenMask, @HunterMask, '22027', 'Remove Insignia'),
(@WorgenMask, @HunterMask, '22810', 'Opening - No Text'),
(@WorgenMask, @HunterMask, '24949', 'Defensive State 2(DND)'),
(@WorgenMask, @HunterMask, '27014', 'Raptor Strike'),
-- (@WorgenMask, @HunterMask, '27015', 'Disengage'), -- Removed?
(@WorgenMask, @HunterMask, '27016', 'Serpent Sting'),
-- (@WorgenMask, @HunterMask, '27018', 'Viper Sting'), -- Removed?
(@WorgenMask, @HunterMask, '27019', 'Arcane Shot'),
-- (@WorgenMask, @HunterMask, '27020', 'Distracting Shot'), -- Removed?
(@WorgenMask, @HunterMask, '27021', 'Multi-Shot'),
(@WorgenMask, @HunterMask, '27022', 'Volley'),
(@WorgenMask, @HunterMask, '27023', 'Immolation Trap'),
(@WorgenMask, @HunterMask, '27025', 'Explosive Trap'),
(@WorgenMask, @HunterMask, '27044', 'Aspect of the Hawk'),
(@WorgenMask, @HunterMask, '27045', 'Aspect of the Wild'),
(@WorgenMask, @HunterMask, '27046', 'Mend Pet'),
(@WorgenMask, @HunterMask, '34026', 'Kill Command'),
(@WorgenMask, @HunterMask, '34074', 'Aspect of the Viper'),
(@WorgenMask, @HunterMask, '34082', 'Advantaged State(DND)'),
(@WorgenMask, @HunterMask, '34120', 'Steady Shot'),
(@WorgenMask, @HunterMask, '34477', 'Misdirection'),
(@WorgenMask, @HunterMask, '34600', 'Snake Trap'),
(@WorgenMask, @HunterMask, '36916', 'Mongoose Bite'),

-- Worgen Rogue
(@WorgenMask, @RogueMask, '668', 'Language Common'),
(@WorgenMask, @RogueMask, '68975', 'Viciousness'),
(@WorgenMask, @RogueMask, '68976', 'Aberration'),
(@WorgenMask, @RogueMask, '68978', 'Flayer'),
(@WorgenMask, @RogueMask, '68992', 'Darkflight'),
(@WorgenMask, @RogueMask, '81', 'Dodge'),
(@WorgenMask, @RogueMask, '203', 'Unarmed'),
(@WorgenMask, @RogueMask, '204', 'Defense'),
(@WorgenMask, @RogueMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @RogueMask, '1180', 'Daggers'),
(@WorgenMask, @RogueMask, '1752', 'Sinister Strike'),
(@WorgenMask, @RogueMask, '2098', 'Eviscerate'),
(@WorgenMask, @RogueMask, '2382', 'Generic'),
(@WorgenMask, @RogueMask, '2479', 'Honorless Target'),
(@WorgenMask, @RogueMask, '2567', 'Thrown'),
(@WorgenMask, @RogueMask, '2764', 'Throw'),
(@WorgenMask, @RogueMask, '3050', 'Detect'),
(@WorgenMask, @RogueMask, '3365', 'Opening'),
(@WorgenMask, @RogueMask, '6233', 'Closing'),
(@WorgenMask, @RogueMask, '6246', 'Closing'),
(@WorgenMask, @RogueMask, '6247', 'Opening'),
(@WorgenMask, @RogueMask, '6477', 'Opening'),
(@WorgenMask, @RogueMask, '6478', 'Opening'),
(@WorgenMask, @RogueMask, '6603', 'Attack'),
(@WorgenMask, @RogueMask, '7266', 'Duel'),
(@WorgenMask, @RogueMask, '7267', 'Grovel'),
(@WorgenMask, @RogueMask, '7355', 'Stuck'),
(@WorgenMask, @RogueMask, '8386', 'Attacking'),
(@WorgenMask, @RogueMask, '9077', 'Leather'),
(@WorgenMask, @RogueMask, '9078', 'Cloth'),
(@WorgenMask, @RogueMask, '9125', 'Generic'),
(@WorgenMask, @RogueMask, '16092', 'Defensive State(DND)'),
(@WorgenMask, @RogueMask, '21184', 'Rogue Passive(DND)'),
(@WorgenMask, @RogueMask, '21651', 'Opening'),
(@WorgenMask, @RogueMask, '21652', 'Closing'),
(@WorgenMask, @RogueMask, '22027', 'Remove Insignia'),
(@WorgenMask, @RogueMask, '22810', 'Opening - No Text'),
(@WorgenMask, @RogueMask, '26865', 'Eviscerate'), -- Only 9?
(@WorgenMask, @RogueMask, '26862', 'Sinister Strike'), -- Only 9?
(@WorgenMask, @RogueMask, '1787', 'Stealth'), -- Only 9?
(@WorgenMask, @RogueMask, '26863', 'Backstab'),
(@WorgenMask, @RogueMask, '921', 'Pick Pocket'),
(@WorgenMask, @RogueMask, '38764', 'Gouge'),
(@WorgenMask, @RogueMask, '26669', 'Evasion'),
(@WorgenMask, @RogueMask, '11297', 'Sap'),
(@WorgenMask, @RogueMask, '6774', 'Slice and Dice'),
(@WorgenMask, @RogueMask, '11305', 'Sprint'),
(@WorgenMask, @RogueMask, '38768', 'Kick'),
(@WorgenMask, @RogueMask, '26866', 'Expose Armor'),
(@WorgenMask, @RogueMask, '26884', 'Garrote'),
(@WorgenMask, @RogueMask, '27448', 'Feint'), -- Only 8?
(@WorgenMask, @RogueMask, '1804', 'Pick Lock'),
(@WorgenMask, @RogueMask, '27441', 'Ambush'),
(@WorgenMask, @RogueMask, '2842', 'Poisons'),
(@WorgenMask, @RogueMask, '1725', 'Distract'),
(@WorgenMask, @RogueMask, '26867', 'Rupture'),
(@WorgenMask, @RogueMask, '26889', 'Vanish'),
(@WorgenMask, @RogueMask, '1833', 'Cheap Shot'),
(@WorgenMask, @RogueMask, '1842', 'Disarm Trap'),
(@WorgenMask, @RogueMask, '408', 'Kidney Shot'),
(@WorgenMask, @RogueMask, '2094', 'Blind'),
(@WorgenMask, @RogueMask, '32684', 'Envenom'),
(@WorgenMask, @RogueMask, '26679', 'Deadly Throw'),
(@WorgenMask, @RogueMask, '31224', 'Cloak of Shadows'),
(@WorgenMask, @RogueMask, '5938', 'Shiv'),
(@WorgenMask, @RogueMask, '8643', 'Kidney Shot'),
(@WorgenMask, @RogueMask, '3127', 'Parry'),
(@WorgenMask, @RogueMask, '674', 'Dual Wield'),
(@WorgenMask, @RogueMask, '3776', 'Green Leather Bracers'), -- What?
-- (@WorgenMask, @RogueMask, '9186', null), -- Removed?
(@WorgenMask, @RogueMask, '21927', 'Natures Ally'), -- What?
(@WorgenMask, @RogueMask, '22054', 'QAEnchant Bracer +7 Intellect'), -- What?
-- (@WorgenMask, @RogueMask, '22055', null), -- Removed?
(@WorgenMask, @RogueMask, '2836', 'Detect Traps'),
-- (@WorgenMask, @RogueMask, '1860', 'Safe Fall'), -- Removed?

-- Worgen Priest
(@WorgenMask, @PriestMask, '668', 'Language Common'),
(@WorgenMask, @PriestMask, '68975', 'Viciousness'),
(@WorgenMask, @PriestMask, '68976', 'Aberration'),
(@WorgenMask, @PriestMask, '68978', 'Flayer'),
(@WorgenMask, @PriestMask, '68992', 'Darkflight'),
(@WorgenMask, @PriestMask, '81', 'Dodge'),
(@WorgenMask, @PriestMask, '198', 'One-Handed Maces'),
(@WorgenMask, @PriestMask, '203', 'Unarmed'),
(@WorgenMask, @PriestMask, '204', 'Defense'),
(@WorgenMask, @PriestMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @PriestMask, '585', 'Smite'),
(@WorgenMask, @PriestMask, '2050', 'Lesser Heal'),
(@WorgenMask, @PriestMask, '2382', 'Generic'),
(@WorgenMask, @PriestMask, '2479', 'Honorless Target'),
(@WorgenMask, @PriestMask, '3050', 'Detect'),
(@WorgenMask, @PriestMask, '3365', 'Opening'),
(@WorgenMask, @PriestMask, '5009', 'Wands'),
(@WorgenMask, @PriestMask, '5019', 'Shoot'),
(@WorgenMask, @PriestMask, '6233', 'Closing'),
(@WorgenMask, @PriestMask, '6246', 'Closing'),
(@WorgenMask, @PriestMask, '6247', 'Opening'),
(@WorgenMask, @PriestMask, '6477', 'Opening'),
(@WorgenMask, @PriestMask, '6478', 'Opening'),
(@WorgenMask, @PriestMask, '6603', 'Attack'),
(@WorgenMask, @PriestMask, '7266', 'Duel'),
(@WorgenMask, @PriestMask, '7267', 'Grovel'),
(@WorgenMask, @PriestMask, '7355', 'Stuck'),
(@WorgenMask, @PriestMask, '8386', 'Attacking'),
(@WorgenMask, @PriestMask, '9078', 'Cloth'),
(@WorgenMask, @PriestMask, '9125', 'Generic'),
(@WorgenMask, @PriestMask, '21651', 'Opening'),
(@WorgenMask, @PriestMask, '21652', 'Closing'),
(@WorgenMask, @PriestMask, '22027', 'Remove Insignia'),
(@WorgenMask, @PriestMask, '22810', 'Opening - No Text'),
(@WorgenMask, @PriestMask, '25389', 'Power Word: Fortitude'),
(@WorgenMask, @PriestMask, '25364', 'Smite'),
(@WorgenMask, @PriestMask, '25368', 'Shadow Word: Pain'),
(@WorgenMask, @PriestMask, '25218', 'Power Word: Shield'),
-- (@WorgenMask, @PriestMask, '25429', 'Fade'), -- Removed?
(@WorgenMask, @PriestMask, '25222', 'Renew'),
(@WorgenMask, @PriestMask, '25375', 'Mind Blast'),
(@WorgenMask, @PriestMask, '25435', 'Resurrection'),
(@WorgenMask, @PriestMask, '25431', 'Inner Fire'),
(@WorgenMask, @PriestMask, '528', 'Cure Disease'),
(@WorgenMask, @PriestMask, '10890', 'Psychic Scream'),
(@WorgenMask, @PriestMask, '988', 'Dispel Magic'),
(@WorgenMask, @PriestMask, '6346', 'Fear Ward'),
(@WorgenMask, @PriestMask, '25235', 'Flash Heal'),
(@WorgenMask, @PriestMask, '25384', 'Holy Fire'),
-- (@WorgenMask, @PriestMask, '25596', 'Mind Soothe'), -- Removed?
(@WorgenMask, @PriestMask, '10955', 'Shackle Undead'),
(@WorgenMask, @PriestMask, '10909', 'Mind Vision'),
-- (@WorgenMask, @PriestMask, '25380', 'Mana Burn'), -- Removed?
-- (@WorgenMask, @PriestMask, '10912', 'Mind Control'), -- Removed?
(@WorgenMask, @PriestMask, '25308', 'Prayer of Healing'),
(@WorgenMask, @PriestMask, '25433', 'Shadow Protection'),
(@WorgenMask, @PriestMask, '552', 'Abolish Disease'),
(@WorgenMask, @PriestMask, '1706', 'Levitate'),
(@WorgenMask, @PriestMask, '25213', 'Greater Heal'),
(@WorgenMask, @PriestMask, '25392', 'Prayer of Fortitude'),
(@WorgenMask, @PriestMask, '39374', 'Prayer of Shadow Protection'),
(@WorgenMask, @PriestMask, '32999', 'Prayer of Spirit'),
(@WorgenMask, @PriestMask, '32996', 'Shadow Word: Death'),
(@WorgenMask, @PriestMask, '32546', 'Binding Heal'),
(@WorgenMask, @PriestMask, '34433', 'Shadowfiend'),
(@WorgenMask, @PriestMask, '33076', 'Prayer of Mending'),
(@WorgenMask, @PriestMask, '32375', 'Mass Dispel'),
-- (@WorgenMask, @PriestMask, '25441', 'Feedback'), -- Removed? Only 4?
(@WorgenMask, @PriestMask, '25312', 'Divine Spirit'),
(@WorgenMask, @PriestMask, '25437', 'Desperate Prayer'), -- Only 5?

-- Worgen Mage
(@WorgenMask, @MageMask, '668', 'Language Common'),
(@WorgenMask, @MageMask, '68975', 'Viciousness'),
(@WorgenMask, @MageMask, '68976', 'Aberration'),
(@WorgenMask, @MageMask, '68978', 'Flayer'),
(@WorgenMask, @MageMask, '68992', 'Darkflight'),
(@WorgenMask, @MageMask, '81', 'Dodge'),
(@WorgenMask, @MageMask, '133', 'Fireball'),
(@WorgenMask, @MageMask, '168', 'Frost Armor'),
(@WorgenMask, @MageMask, '203', 'Unarmed'),
(@WorgenMask, @MageMask, '204', 'Defense'),
(@WorgenMask, @MageMask, '227', 'Staves'),
(@WorgenMask, @MageMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @MageMask, '2382', 'Generic'),
(@WorgenMask, @MageMask, '2479', 'Honorless Target'),
(@WorgenMask, @MageMask, '3050', 'Detect'),
(@WorgenMask, @MageMask, '3365', 'Opening'),
(@WorgenMask, @MageMask, '5009', 'Wands'),
(@WorgenMask, @MageMask, '5019', 'Shoot'),
(@WorgenMask, @MageMask, '6233', 'Closing'),
(@WorgenMask, @MageMask, '6246', 'Closing'),
(@WorgenMask, @MageMask, '6247', 'Opening'),
(@WorgenMask, @MageMask, '6477', 'Opening'),
(@WorgenMask, @MageMask, '6478', 'Opening'),
(@WorgenMask, @MageMask, '6603', 'Attack'),
(@WorgenMask, @MageMask, '7266', 'Duel'),
(@WorgenMask, @MageMask, '7267', 'Grovel'),
(@WorgenMask, @MageMask, '7355', 'Stuck'),
(@WorgenMask, @MageMask, '8386', 'Attacking'),
(@WorgenMask, @MageMask, '9078', 'Cloth'),
(@WorgenMask, @MageMask, '9125', 'Generic'),
(@WorgenMask, @MageMask, '21651', 'Opening'),
(@WorgenMask, @MageMask, '21652', 'Closing'),
(@WorgenMask, @MageMask, '22027', 'Remove Insignia'),
(@WorgenMask, @MageMask, '22810', 'Opening - No Text'),
(@WorgenMask, @MageMask, '27126', 'Arcane Intellect'),
(@WorgenMask, @MageMask, '27070', 'Fireball'),
-- (@WorgenMask, @MageMask, '22018', null), -- Removed?
(@WorgenMask, @MageMask, '27072', 'Frostbolt'),
-- (@WorgenMask, @MageMask, '22019', null), -- Removed?
(@WorgenMask, @MageMask, '27079', 'Fire Blast'),
(@WorgenMask, @MageMask, '38704', 'Arcane Missiles'),
(@WorgenMask, @MageMask, '28272', 'Polymorph (Pig)'),
(@WorgenMask, @MageMask, '28271', 'Polymorph (Turtle)'),
(@WorgenMask, @MageMask, '12826', 'Polymorph (Sheep)'),
(@WorgenMask, @MageMask, '27088', 'Frost Nova'),
(@WorgenMask, @MageMask, '33944', 'Dampen Magic'),
(@WorgenMask, @MageMask, '130', 'Slow Fall'),
(@WorgenMask, @MageMask, '27082', 'Arcane Explosion'),
(@WorgenMask, @MageMask, '27086', 'Flamestrike'),
(@WorgenMask, @MageMask, '33946', 'Amplify Magic'),
(@WorgenMask, @MageMask, '475', 'Remove Curse'),
(@WorgenMask, @MageMask, '1953', 'Blink'),
(@WorgenMask, @MageMask, '27085', 'Blizzard'),
(@WorgenMask, @MageMask, '12051', 'Evocation'),
(@WorgenMask, @MageMask, '27128', 'Fire Ward'),
(@WorgenMask, @MageMask, '27131', 'Mana Shield'),
(@WorgenMask, @MageMask, '32796', 'Frost Ward'),
(@WorgenMask, @MageMask, '27074', 'Scorch'),
(@WorgenMask, @MageMask, '2139', 'Counterspell'),
(@WorgenMask, @MageMask, '27101', 'Conjure Mana Gem'),
(@WorgenMask, @MageMask, '27124', 'Ice Armor'),
(@WorgenMask, @MageMask, '45438', 'Ice Block'),
(@WorgenMask, @MageMask, '27125', 'Mage Armor'),
(@WorgenMask, @MageMask, '27127', 'Arcane Brilliance'),
(@WorgenMask, @MageMask, '30482', 'Molten Armor'),
(@WorgenMask, @MageMask, '30451', 'Arcane Blast'),
(@WorgenMask, @MageMask, '30455', 'Ice Lance'),
(@WorgenMask, @MageMask, '66', 'Invisibility'),
(@WorgenMask, @MageMask, '43987', 'Ritual of Refreshment'),
(@WorgenMask, @MageMask, '30449', 'Spellsteal'),
(@WorgenMask, @MageMask, '27087', 'Cone of Cold'),

-- Worgen Warlock
(@WorgenMask, @WarlockMask, '668', 'Language Common'),
(@WorgenMask, @WarlockMask, '68975', 'Viciousness'),
(@WorgenMask, @WarlockMask, '68976', 'Aberration'),
(@WorgenMask, @WarlockMask, '68978', 'Flayer'),
(@WorgenMask, @WarlockMask, '68992', 'Darkflight'),
(@WorgenMask, @WarlockMask, '81', 'Dodge'),
(@WorgenMask, @WarlockMask, '203', 'Unarmed'),
(@WorgenMask, @WarlockMask, '204', 'Defense'),
(@WorgenMask, @WarlockMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @WarlockMask, '686', 'Shadow Bolt'),
(@WorgenMask, @WarlockMask, '687', 'Demon Skin'),
(@WorgenMask, @WarlockMask, '1180', 'Daggers'),
(@WorgenMask, @WarlockMask, '2382', 'Generic'),
(@WorgenMask, @WarlockMask, '2479', 'Honorless Target'),
(@WorgenMask, @WarlockMask, '3050', 'Detect'),
(@WorgenMask, @WarlockMask, '3365', 'Opening'),
(@WorgenMask, @WarlockMask, '5009', 'Wands'),
(@WorgenMask, @WarlockMask, '5019', 'Shoot'),
(@WorgenMask, @WarlockMask, '6233', 'Closing'),
(@WorgenMask, @WarlockMask, '6246', 'Closing'),
(@WorgenMask, @WarlockMask, '6247', 'Opening'),
(@WorgenMask, @WarlockMask, '6477', 'Opening'),
(@WorgenMask, @WarlockMask, '6478', 'Opening'),
(@WorgenMask, @WarlockMask, '6603', 'Attack'),
(@WorgenMask, @WarlockMask, '7266', 'Duel'),
(@WorgenMask, @WarlockMask, '7267', 'Grovel'),
(@WorgenMask, @WarlockMask, '7355', 'Stuck'),
(@WorgenMask, @WarlockMask, '8386', 'Attacking'),
(@WorgenMask, @WarlockMask, '9078', 'Cloth'),
(@WorgenMask, @WarlockMask, '9125', 'Generic'),
(@WorgenMask, @WarlockMask, '21651', 'Opening'),
(@WorgenMask, @WarlockMask, '21652', 'Closing'),
(@WorgenMask, @WarlockMask, '22027', 'Remove Insignia'),
(@WorgenMask, @WarlockMask, '22810', 'Opening - No Text'),
(@WorgenMask, @WarlockMask, '27215', 'Immolate'), -- Only 9?
(@WorgenMask, @WarlockMask, '27209', 'Shadow Bolt'),
(@WorgenMask, @WarlockMask, '27216', 'Corruption'),
(@WorgenMask, @WarlockMask, '30909', 'Curse of Weakness'),
(@WorgenMask, @WarlockMask, '27222', 'Life Tap'),
(@WorgenMask, @WarlockMask, '27218', 'Curse of Agony'),
(@WorgenMask, @WarlockMask, '6215', 'Fear'),
(@WorgenMask, @WarlockMask, '27230', 'Create Healthstone'),
(@WorgenMask, @WarlockMask, '27217', 'Drain Soul'),
(@WorgenMask, @WarlockMask, '27259', 'Health Funnel'),
-- (@WorgenMask, @WarlockMask, '27226', 'Curse of Recklessness'), -- Removed?
(@WorgenMask, @WarlockMask, '27220', 'Drain Life'),
(@WorgenMask, @WarlockMask, '5697', 'Unending Breath'),
(@WorgenMask, @WarlockMask, '27238', 'Create Soulstone'),
(@WorgenMask, @WarlockMask, '30459', 'Searing Pain'),
(@WorgenMask, @WarlockMask, '27260', 'Demon Armor'),
(@WorgenMask, @WarlockMask, '27212', 'Rain of Fire'),
(@WorgenMask, @WarlockMask, '698', 'Ritual of Summoning'),
(@WorgenMask, @WarlockMask, '5500', 'Sense Demons'),
-- (@WorgenMask, @WarlockMask, '30908', 'Drain Mana'), -- Removed?
(@WorgenMask, @WarlockMask, '11719', 'Curse of Tongues'),
(@WorgenMask, @WarlockMask, '132', 'Detect Invisibility'),
(@WorgenMask, @WarlockMask, '18647', 'Banish'),
(@WorgenMask, @WarlockMask, '27213', 'Hellfire'),
(@WorgenMask, @WarlockMask, '11726', 'Subjugate Demon'),
(@WorgenMask, @WarlockMask, '27228', 'Curse of the Elements'),
(@WorgenMask, @WarlockMask, '28610', 'Shadow Ward'),
(@WorgenMask, @WarlockMask, '28172', 'Create Spellstone'),
(@WorgenMask, @WarlockMask, '27250', 'Create Firestone'),
(@WorgenMask, @WarlockMask, '17928', 'Howl of Terror'),
(@WorgenMask, @WarlockMask, '27223', 'Death Coil'),
-- (@WorgenMask, @WarlockMask, '27229', 'Curse of Shadow'), -- Removed?
(@WorgenMask, @WarlockMask, '30545', 'Soul Fire'),
(@WorgenMask, @WarlockMask, '30910', 'Curse of Doom'),
(@WorgenMask, @WarlockMask, '18540', 'Ritual of Doom'),
(@WorgenMask, @WarlockMask, '28189', 'Fel Armor'),
(@WorgenMask, @WarlockMask, '32231', 'Incinerate'),
(@WorgenMask, @WarlockMask, '29858', 'Soulshatter'),
(@WorgenMask, @WarlockMask, '29893', 'Ritual of Souls'),
(@WorgenMask, @WarlockMask, '27243', 'Seed of Corruption'),
(@WorgenMask, @WarlockMask, '23161', 'Dreadsteed'),
(@WorgenMask, @WarlockMask, '688', 'Summon Imp'),
(@WorgenMask, @WarlockMask, '697', 'Summon Voidwalker'),
(@WorgenMask, @WarlockMask, '712', 'Summon Succubus'),
(@WorgenMask, @WarlockMask, '691', 'Summon Felhunter'), -- 10 of this?
(@WorgenMask, @WarlockMask, '126', 'Eye of Kilrogg'),

-- Worgen Druid
(@WorgenMask, @DruidMask, '668', 'Language Common'),
(@WorgenMask, @DruidMask, '68975', 'Viciousness'),
(@WorgenMask, @DruidMask, '68976', 'Aberration'),
(@WorgenMask, @DruidMask, '68978', 'Flayer'),
(@WorgenMask, @DruidMask, '68992', 'Darkflight'),
(@WorgenMask, @DruidMask, '81', 'Dodge'),
(@WorgenMask, @DruidMask, '203', 'Unarmed'),
(@WorgenMask, @DruidMask, '204', 'Defense'),
(@WorgenMask, @DruidMask, '227', 'Staves'),
(@WorgenMask, @DruidMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @DruidMask, '768', 'Cat Form'),
(@WorgenMask, @DruidMask, '783', 'Travel Form'),
(@WorgenMask, @DruidMask, '1066', 'Aquatic Form'),
(@WorgenMask, @DruidMask, '1178', 'Bear Form(Passive)'),
(@WorgenMask, @DruidMask, '1180', 'Daggers'),
(@WorgenMask, @DruidMask, '2382', 'Generic'),
(@WorgenMask, @DruidMask, '2479', 'Honorless Target'),
(@WorgenMask, @DruidMask, '2782', 'Remove Curse'),
(@WorgenMask, @DruidMask, '2893', 'Abolish Poison'),
(@WorgenMask, @DruidMask, '3025', 'Cat Form(Passive)'),
(@WorgenMask, @DruidMask, '3050', 'Detect'),
(@WorgenMask, @DruidMask, '3365', 'Opening'),
(@WorgenMask, @DruidMask, '5176', 'Wrath'),
(@WorgenMask, @DruidMask, '5185', 'Healing Touch'),
(@WorgenMask, @DruidMask, '5209', 'Challenging Roar'),
(@WorgenMask, @DruidMask, '5225', 'Track Humanoids'),
(@WorgenMask, @DruidMask, '5229', 'Enrage'),
(@WorgenMask, @DruidMask, '5419', 'Travel Form(Passive)'),
(@WorgenMask, @DruidMask, '5420', 'Tree of Life'),
(@WorgenMask, @DruidMask, '5421', 'Aquatic Form(Passive)'),
(@WorgenMask, @DruidMask, '6233', 'Closing'),
(@WorgenMask, @DruidMask, '6246', 'Closing'),
(@WorgenMask, @DruidMask, '6247', 'Opening'),
(@WorgenMask, @DruidMask, '6477', 'Opening'),
(@WorgenMask, @DruidMask, '6478', 'Opening'),
(@WorgenMask, @DruidMask, '6603', 'Attack'),
(@WorgenMask, @DruidMask, '6795', 'Growl'),
(@WorgenMask, @DruidMask, '7266', 'Duel'),
(@WorgenMask, @DruidMask, '7267', 'Grovel'),
(@WorgenMask, @DruidMask, '7355', 'Stuck'),
(@WorgenMask, @DruidMask, '8386', 'Attacking'),
(@WorgenMask, @DruidMask, '8946', 'Cure Poison'),
(@WorgenMask, @DruidMask, '8983', 'Bash'),
(@WorgenMask, @DruidMask, '9077', 'Leather'),
(@WorgenMask, @DruidMask, '9078', 'Cloth'),
(@WorgenMask, @DruidMask, '9125', 'Generic'),
(@WorgenMask, @DruidMask, '9634', 'Dire Bear Form'),
(@WorgenMask, @DruidMask, '9635', 'Dire Bear Form(Passive)'),
(@WorgenMask, @DruidMask, '9846', 'Tigers Fury'),
(@WorgenMask, @DruidMask, '9913', 'Prowl'),
(@WorgenMask, @DruidMask, '18658', 'Hibernate'),
(@WorgenMask, @DruidMask, '18960', 'Teleport: Moonglade'),
(@WorgenMask, @DruidMask, '21178', 'Bear Form(Passive2)'),
(@WorgenMask, @DruidMask, '21651', 'Opening'),
(@WorgenMask, @DruidMask, '21652', 'Closing'),
(@WorgenMask, @DruidMask, '22027', 'Remove Insignia'),
(@WorgenMask, @DruidMask, '22570', 'Maim'),
(@WorgenMask, @DruidMask, '22810', 'Opening - No Text'),
(@WorgenMask, @DruidMask, '22812', 'Bark Skin'),
(@WorgenMask, @DruidMask, '24248', 'Ferocious Bite'),
(@WorgenMask, @DruidMask, '24905', 'Moonkin Form(Passive)'),
(@WorgenMask, @DruidMask, '26979', 'Healing Touch'),
(@WorgenMask, @DruidMask, '26980', 'Regrowth'),
(@WorgenMask, @DruidMask, '26982', 'Rejuvenation'),
(@WorgenMask, @DruidMask, '26983', 'Tranquility'),
(@WorgenMask, @DruidMask, '26985', 'Wrath'),
(@WorgenMask, @DruidMask, '26986', 'Starfire'),
(@WorgenMask, @DruidMask, '26988', 'Moonfire'),
(@WorgenMask, @DruidMask, '26989', 'Entangling Roots'),
(@WorgenMask, @DruidMask, '26990', 'Mark of the Wild'),
(@WorgenMask, @DruidMask, '26991', 'Gift of the Wild'),
(@WorgenMask, @DruidMask, '26992', 'Thorns'),
-- (@WorgenMask, @DruidMask, '26993', 'Faerie Fire'), -- Removed?
(@WorgenMask, @DruidMask, '26994', 'Rebirth'),
(@WorgenMask, @DruidMask, '26995', 'Soothe Animal'),
(@WorgenMask, @DruidMask, '26996', 'Maul'),
(@WorgenMask, @DruidMask, '26997', 'Swipe (Bear)'),
(@WorgenMask, @DruidMask, '26998', 'Demoralizing Roar'),
-- (@WorgenMask, @DruidMask, '26999', 'Frenzied Regeneration'), -- Removed?
(@WorgenMask, @DruidMask, '27000', 'Claw'),
(@WorgenMask, @DruidMask, '27002', 'Shred'),
(@WorgenMask, @DruidMask, '27003', 'Rake'),
(@WorgenMask, @DruidMask, '27004', 'Cower'),
(@WorgenMask, @DruidMask, '27005', 'Ravage'),
(@WorgenMask, @DruidMask, '27006', 'Pounce'),
(@WorgenMask, @DruidMask, '27008', 'Rip'),
(@WorgenMask, @DruidMask, '27012', 'Hurricane'),
(@WorgenMask, @DruidMask, '27764', 'Fetish'),
(@WorgenMask, @DruidMask, '29166', 'Innervate'),
(@WorgenMask, @DruidMask, '33357', 'Dash'),
(@WorgenMask, @DruidMask, '33745', 'Lacerate'),
(@WorgenMask, @DruidMask, '33763', 'Lifebloom'),
(@WorgenMask, @DruidMask, '33786', 'Cyclone'),
(@WorgenMask, @DruidMask, '33948', 'Flight Form(Passive)'),
(@WorgenMask, @DruidMask, '34123', 'Tree of Life(Passive)'),
(@WorgenMask, @DruidMask, '40120', 'Swift Flight Form'),
(@WorgenMask, @DruidMask, '40121', 'Swift Flight Form(Passive)');
