INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Kul Tiran Paladin
(@KulTiranMask, @PaladinMask, '81', 'Dodge'),
(@KulTiranMask, @PaladinMask, '107', 'Block'),
(@KulTiranMask, @PaladinMask, '198', 'One-Handed Maces'),
(@KulTiranMask, @PaladinMask, '199', 'Two-Handed Maces'),
(@KulTiranMask, @PaladinMask, '203', 'Unarmed'),
(@KulTiranMask, @PaladinMask, '204', 'Defense'),
(@KulTiranMask, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@KulTiranMask, @PaladinMask, '635', 'Holy Light'),
(@KulTiranMask, @PaladinMask, '668', 'Language Common'),
(@KulTiranMask, @PaladinMask, '2382', 'Generic'),
(@KulTiranMask, @PaladinMask, '2479', 'Honorless Target'),
(@KulTiranMask, @PaladinMask, '3050', 'Detect'),
(@KulTiranMask, @PaladinMask, '3365', 'Opening'),
(@KulTiranMask, @PaladinMask, '6233', 'Closing'),
(@KulTiranMask, @PaladinMask, '6246', 'Closing'),
(@KulTiranMask, @PaladinMask, '6247', 'Opening'),
(@KulTiranMask, @PaladinMask, '6477', 'Opening'),
(@KulTiranMask, @PaladinMask, '6478', 'Opening'),
(@KulTiranMask, @PaladinMask, '6603', 'Attack'),
(@KulTiranMask, @PaladinMask, '7266', 'Duel'),
(@KulTiranMask, @PaladinMask, '7267', 'Grovel'),
(@KulTiranMask, @PaladinMask, '7355', 'Stuck'),
(@KulTiranMask, @PaladinMask, '8386', 'Attacking'),
(@KulTiranMask, @PaladinMask, '8737', 'Mail'),
(@KulTiranMask, @PaladinMask, '9077', 'Leather'),
(@KulTiranMask, @PaladinMask, '9078', 'Cloth'),
(@KulTiranMask, @PaladinMask, '9116', 'Shield'),
(@KulTiranMask, @PaladinMask, '9125', 'Generic'),
(@KulTiranMask, @PaladinMask, '21084', 'Seal of Righteousness'),
(@KulTiranMask, @PaladinMask, '21651', 'Opening'),
(@KulTiranMask, @PaladinMask, '21652', 'Closing'),
(@KulTiranMask, @PaladinMask, '22027', 'Remove Insignia'),
(@KulTiranMask, @PaladinMask, '22810', 'Opening - No Text'),
(@KulTiranMask, @PaladinMask, '27762', 'Libram'),
(@KulTiranMask, @PaladinMask, '27149', 'Devotion Aura'),
(@KulTiranMask, @PaladinMask, '27136', 'Holy Light'),
-- (@KulTiranMask, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
(@KulTiranMask, @PaladinMask, '27140', 'Blessing of Might'),
(@KulTiranMask, @PaladinMask, '20271', 'Judgement of Light'),
-- (@KulTiranMask, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
(@KulTiranMask, @PaladinMask, '10308', 'Hammer of Justice'),
(@KulTiranMask, @PaladinMask, '10278', 'Hand of Protection'),
(@KulTiranMask, @PaladinMask, '27154', 'Lay on Hands'),
(@KulTiranMask, @PaladinMask, '20773', 'Redemption'),
(@KulTiranMask, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@KulTiranMask, @PaladinMask, '31789', 'Righteous Defense'),
(@KulTiranMask, @PaladinMask, '27150', 'Retribution Aura'),
(@KulTiranMask, @PaladinMask, '25780', 'Righteous Fury'),
(@KulTiranMask, @PaladinMask, '1044', 'Hand of Freedom'),
(@KulTiranMask, @PaladinMask, '33776', 'Spiritual Attunement'),
(@KulTiranMask, @PaladinMask, '27173', 'Consecration'),
(@KulTiranMask, @PaladinMask, '27138', 'Exorcism'),
(@KulTiranMask, @PaladinMask, '27137', 'Flash of Light'),
(@KulTiranMask, @PaladinMask, '5502', 'Sense Undead'),
(@KulTiranMask, @PaladinMask, '19746', 'Concentration Aura'),
-- (@KulTiranMask, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
-- (@KulTiranMask, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@KulTiranMask, @PaladinMask, '1038', 'Hand of Salvation'),
(@KulTiranMask, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@KulTiranMask, @PaladinMask, '19752', 'Divine Intervention'),
-- (@KulTiranMask, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
(@KulTiranMask, @PaladinMask, '27152', 'Frost Resistance Aura'),
-- (@KulTiranMask, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@KulTiranMask, @PaladinMask, '27153', 'Fire Resistance Aura'),
-- (@KulTiranMask, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@KulTiranMask, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
(@KulTiranMask, @PaladinMask, '4987', 'Cleanse'),
(@KulTiranMask, @PaladinMask, '27180', 'Hammer of Wrath'),
-- (@KulTiranMask, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@KulTiranMask, @PaladinMask, '27139', 'Holy Wrath'),
(@KulTiranMask, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@KulTiranMask, @PaladinMask, '10326', 'Turn Evil'),
(@KulTiranMask, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
(@KulTiranMask, @PaladinMask, '25898', 'Greater Blessing of Kings'),
-- (@KulTiranMask, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@KulTiranMask, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@KulTiranMask, @PaladinMask, '32223', 'Crusader Aura'),
-- (@KulTiranMask, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@KulTiranMask, @PaladinMask, '31884', 'Avenging Wrath'),
(@KulTiranMask, @PaladinMask, '750', 'Plate Armor'),
(@KulTiranMask, @PaladinMask, '3127', 'Parry'),
(@KulTiranMask, @PaladinMask, '23214', 'Charger'), -- Only 9?
(@KulTiranMask, @PaladinMask, '31801', 'Seal of Vengeance'), -- Only 9?

-- Kul Tiran Warlock
(@KulTiranMask, @WarlockMask, '668', 'Language Common'),
(@KulTiranMask, @WarlockMask, '81', 'Dodge'),
(@KulTiranMask, @WarlockMask, '203', 'Unarmed'),
(@KulTiranMask, @WarlockMask, '204', 'Defense'),
(@KulTiranMask, @WarlockMask, '522', 'SPELLDEFENSE(DND)'),
(@KulTiranMask, @WarlockMask, '686', 'Shadow Bolt'),
(@KulTiranMask, @WarlockMask, '687', 'Demon Skin'),
(@KulTiranMask, @WarlockMask, '1180', 'Daggers'),
(@KulTiranMask, @WarlockMask, '2382', 'Generic'),
(@KulTiranMask, @WarlockMask, '2479', 'Honorless Target'),
(@KulTiranMask, @WarlockMask, '3050', 'Detect'),
(@KulTiranMask, @WarlockMask, '3365', 'Opening'),
(@KulTiranMask, @WarlockMask, '5009', 'Wands'),
(@KulTiranMask, @WarlockMask, '5019', 'Shoot'),
(@KulTiranMask, @WarlockMask, '6233', 'Closing'),
(@KulTiranMask, @WarlockMask, '6246', 'Closing'),
(@KulTiranMask, @WarlockMask, '6247', 'Opening'),
(@KulTiranMask, @WarlockMask, '6477', 'Opening'),
(@KulTiranMask, @WarlockMask, '6478', 'Opening'),
(@KulTiranMask, @WarlockMask, '6603', 'Attack'),
(@KulTiranMask, @WarlockMask, '7266', 'Duel'),
(@KulTiranMask, @WarlockMask, '7267', 'Grovel'),
(@KulTiranMask, @WarlockMask, '7355', 'Stuck'),
(@KulTiranMask, @WarlockMask, '8386', 'Attacking'),
(@KulTiranMask, @WarlockMask, '9078', 'Cloth'),
(@KulTiranMask, @WarlockMask, '9125', 'Generic'),
(@KulTiranMask, @WarlockMask, '21651', 'Opening'),
(@KulTiranMask, @WarlockMask, '21652', 'Closing'),
(@KulTiranMask, @WarlockMask, '22027', 'Remove Insignia'),
(@KulTiranMask, @WarlockMask, '22810', 'Opening - No Text'),
(@KulTiranMask, @WarlockMask, '27215', 'Immolate'), -- Only 9?
(@KulTiranMask, @WarlockMask, '27209', 'Shadow Bolt'),
(@KulTiranMask, @WarlockMask, '27216', 'Corruption'),
(@KulTiranMask, @WarlockMask, '30909', 'Curse of Weakness'),
(@KulTiranMask, @WarlockMask, '27222', 'Life Tap'),
(@KulTiranMask, @WarlockMask, '27218', 'Curse of Agony'),
(@KulTiranMask, @WarlockMask, '6215', 'Fear'),
(@KulTiranMask, @WarlockMask, '27230', 'Create Healthstone'),
(@KulTiranMask, @WarlockMask, '27217', 'Drain Soul'),
(@KulTiranMask, @WarlockMask, '27259', 'Health Funnel'),
-- (@KulTiranMask, @WarlockMask, '27226', 'Curse of Recklessness'), -- Removed?
(@KulTiranMask, @WarlockMask, '27220', 'Drain Life'),
(@KulTiranMask, @WarlockMask, '5697', 'Unending Breath'),
(@KulTiranMask, @WarlockMask, '27238', 'Create Soulstone'),
(@KulTiranMask, @WarlockMask, '30459', 'Searing Pain'),
(@KulTiranMask, @WarlockMask, '27260', 'Demon Armor'),
(@KulTiranMask, @WarlockMask, '27212', 'Rain of Fire'),
(@KulTiranMask, @WarlockMask, '698', 'Ritual of Summoning'),
(@KulTiranMask, @WarlockMask, '5500', 'Sense Demons'),
-- (@KulTiranMask, @WarlockMask, '30908', 'Drain Mana'), -- Removed?
(@KulTiranMask, @WarlockMask, '11719', 'Curse of Tongues'),
(@KulTiranMask, @WarlockMask, '132', 'Detect Invisibility'),
(@KulTiranMask, @WarlockMask, '18647', 'Banish'),
(@KulTiranMask, @WarlockMask, '27213', 'Hellfire'),
(@KulTiranMask, @WarlockMask, '11726', 'Subjugate Demon'),
(@KulTiranMask, @WarlockMask, '27228', 'Curse of the Elements'),
(@KulTiranMask, @WarlockMask, '28610', 'Shadow Ward'),
(@KulTiranMask, @WarlockMask, '28172', 'Create Spellstone'),
(@KulTiranMask, @WarlockMask, '27250', 'Create Firestone'),
(@KulTiranMask, @WarlockMask, '17928', 'Howl of Terror'),
(@KulTiranMask, @WarlockMask, '27223', 'Death Coil'),
-- (@KulTiranMask, @WarlockMask, '27229', 'Curse of Shadow'), -- Removed?
(@KulTiranMask, @WarlockMask, '30545', 'Soul Fire'),
(@KulTiranMask, @WarlockMask, '30910', 'Curse of Doom'),
(@KulTiranMask, @WarlockMask, '18540', 'Ritual of Doom'),
(@KulTiranMask, @WarlockMask, '28189', 'Fel Armor'),
(@KulTiranMask, @WarlockMask, '32231', 'Incinerate'),
(@KulTiranMask, @WarlockMask, '29858', 'Soulshatter'),
(@KulTiranMask, @WarlockMask, '29893', 'Ritual of Souls'),
(@KulTiranMask, @WarlockMask, '27243', 'Seed of Corruption'),
(@KulTiranMask, @WarlockMask, '23161', 'Dreadsteed'),
(@KulTiranMask, @WarlockMask, '688', 'Summon Imp'),
(@KulTiranMask, @WarlockMask, '697', 'Summon Voidwalker'),
(@KulTiranMask, @WarlockMask, '712', 'Summon Succubus'),
(@KulTiranMask, @WarlockMask, '691', 'Summon Felhunter'), -- 10 of this?
(@KulTiranMask, @WarlockMask, '126', 'Eye of Kilrogg');
