-- [F-031] mod-azerothcore-high-elf: charhairgeosets: 123 inserts, 6 updates, 0 deletes

-- New entries
DELETE FROM `charhairgeosets` WHERE `id` = 570;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (570, @HighElf, @Male, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 571;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (571, @HighElf, @Female, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 572;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (572, @HighElf, @Female, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 573;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (573, @HighElf, @Male, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 574;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (574, @HighElf, @Male, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 575;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (575, @HighElf, @Male, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 576;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (576, @HighElf, @Male, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 577;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (577, @HighElf, @Male, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 578;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (578, @HighElf, @Male, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 579;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (579, @HighElf, @Male, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 580;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (580, @HighElf, @Male, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 581;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (581, @HighElf, @Male, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 582;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (582, @HighElf, @Male, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 583;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (583, @HighElf, @Female, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 584;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (584, @HighElf, @Female, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 585;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (585, @HighElf, @Female, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 586;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (586, @HighElf, @Female, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 587;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (587, @HighElf, @Female, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 588;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (588, @HighElf, @Female, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 589;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (589, @HighElf, @Female, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 590;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (590, @HighElf, @Female, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 591;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (591, @HighElf, @Female, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 592;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (592, @HighElf, @Female, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 593;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (593, @HighElf, @Female, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 594;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (594, @HighElf, @Female, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 595;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (595, @HighElf, @Female, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 596;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (596, @HighElf, @Female, 15, 17, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 597;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (597, @HighElf, @Female, 16, 18, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 598;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (598, @HighElf, @Female, 17, 19, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 599;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (599, @HighElf, @Female, 18, 20, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 600;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (600, @HighElf, @Female, 19, 21, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 601;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (601, @HighElf, @Male, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 602;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (602, @HighElf, @Male, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 603;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (603, @HighElf, @Male, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 604;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (604, @HighElf, @Male, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 605;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (605, @HighElf, @Male, 15, 17, 0);
