INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Goblin Warrior
(@GoblinMask, @WarriorMask, '669', 'Language Orcish'),
(@GoblinMask, @WarriorMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @WarriorMask, '69042', 'Time is Money'),
(@GoblinMask, @WarriorMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @WarriorMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @WarriorMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @WarriorMask, '69070', 'Rocket Jump'),
(@GoblinMask, @WarriorMask, '78', 'Heroic Strike'),
(@GoblinMask, @WarriorMask, '81', 'Dodge'),
(@GoblinMask, @WarriorMask, '107', 'Block'),
(@GoblinMask, @WarriorMask, '196', 'One-Handed Axes'),
(@GoblinMask, @WarriorMask, '197', 'Two-Handed Axes'),
(@GoblinMask, @WarriorMask, '201', 'One-Handed Swords'),
(@GoblinMask, @WarriorMask, '203', 'Unarmed'),
(@GoblinMask, @WarriorMask, '204', 'Defense'),
(@GoblinMask, @WarriorMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @WarriorMask, '2382', 'Generic'),
(@GoblinMask, @WarriorMask, '2457', 'Battle Stance'),
(@GoblinMask, @WarriorMask, '2479', 'Honorless Target'),
(@GoblinMask, @WarriorMask, '3050', 'Detect'),
(@GoblinMask, @WarriorMask, '3365', 'Opening'),
(@GoblinMask, @WarriorMask, '5301', 'Defensive State(DND)'),
(@GoblinMask, @WarriorMask, '6233', 'Closing'),
(@GoblinMask, @WarriorMask, '6246', 'Closing'),
(@GoblinMask, @WarriorMask, '6247', 'Opening'),
(@GoblinMask, @WarriorMask, '6477', 'Opening'),
(@GoblinMask, @WarriorMask, '6478', 'Opening'),
(@GoblinMask, @WarriorMask, '6603', 'Attack'),
(@GoblinMask, @WarriorMask, '7266', 'Duel'),
(@GoblinMask, @WarriorMask, '7267', 'Grovel'),
(@GoblinMask, @WarriorMask, '7355', 'Stuck'),
(@GoblinMask, @WarriorMask, '7376', 'Defensive Stance Passive'),
(@GoblinMask, @WarriorMask, '7381', 'Berserker Stance Passive'),
(@GoblinMask, @WarriorMask, '8386', 'Attacking'),
(@GoblinMask, @WarriorMask, '8737', 'Mail'),
(@GoblinMask, @WarriorMask, '9077', 'Leather'),
(@GoblinMask, @WarriorMask, '9078', 'Cloth'),
(@GoblinMask, @WarriorMask, '9116', 'Shield'),
(@GoblinMask, @WarriorMask, '9125', 'Generic'),
(@GoblinMask, @WarriorMask, '21156', 'Battle Stance Passive'),
(@GoblinMask, @WarriorMask, '21651', 'Opening'),
(@GoblinMask, @WarriorMask, '21652', 'Closing'),
(@GoblinMask, @WarriorMask, '22027', 'Remove Insignia'),
(@GoblinMask, @WarriorMask, '22810', 'Opening - No Text'),
(@GoblinMask, @WarriorMask, '32215', 'Victorious State'),
(@GoblinMask, @WarriorMask, '2048', 'Battle Shout'),
(@GoblinMask, @WarriorMask, '30324', 'Heroic Strike'),
(@GoblinMask, @WarriorMask, '11578', 'Charge'),
(@GoblinMask, @WarriorMask, '25208', 'Rend'),
(@GoblinMask, @WarriorMask, '25264', 'Thunder Clap'),
(@GoblinMask, @WarriorMask, '2687', 'Bloodrage'),
(@GoblinMask, @WarriorMask, '71', 'Defensive Stance'),
(@GoblinMask, @WarriorMask, '25225', 'Sunder Armor'),
(@GoblinMask, @WarriorMask, '355', 'Taunt'),
(@GoblinMask, @WarriorMask, '11585', 'Overpower'),
(@GoblinMask, @WarriorMask, '29704', 'Shield Bash'),
(@GoblinMask, @WarriorMask, '25203', 'Demoralizing Shout'),
(@GoblinMask, @WarriorMask, '30357', 'Revenge'),
(@GoblinMask, @WarriorMask, '25266', 'Mocking Blow'),
(@GoblinMask, @WarriorMask, '2565', 'Shield Block'),
(@GoblinMask, @WarriorMask, '676', 'Disarm'),
(@GoblinMask, @WarriorMask, '25231', 'Cleave'),
(@GoblinMask, @WarriorMask, '20230', 'Retaliation'),
(@GoblinMask, @WarriorMask, '5246', 'Intimidating Shout'),
(@GoblinMask, @WarriorMask, '25236', 'Execute'),
(@GoblinMask, @WarriorMask, '1161', 'Challenging Shout'),
(@GoblinMask, @WarriorMask, '871', 'Shield Wall'),
(@GoblinMask, @WarriorMask, '2458', 'Berserker Stance'),
(@GoblinMask, @WarriorMask, '25275', 'Intercept'),
(@GoblinMask, @WarriorMask, '25242', 'Slam'),
(@GoblinMask, @WarriorMask, '18499', 'Berserker Rage'),
(@GoblinMask, @WarriorMask, '1680', 'Whirlwind'),
(@GoblinMask, @WarriorMask, '6554', 'Pummel'),
(@GoblinMask, @WarriorMask, '1719', 'Recklessness'),
(@GoblinMask, @WarriorMask, '34428', 'Victory Rush'),
(@GoblinMask, @WarriorMask, '23920', 'Spell Reflection'),
(@GoblinMask, @WarriorMask, '469', 'Commanding Shout'),
(@GoblinMask, @WarriorMask, '3411', 'Intervene'),
(@GoblinMask, @WarriorMask, '25212', 'Hamstring'),
(@GoblinMask, @WarriorMask, '674', 'Dual Wield'),
(@GoblinMask, @WarriorMask, '750', 'Plate Armor'),
(@GoblinMask, @WarriorMask, '12678', 'Stance Mastery'),

-- Goblin Hunter
(@GoblinMask, @HunterMask, '669', 'Language Orcish'),
(@GoblinMask, @HunterMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @HunterMask, '69042', 'Time is Money'),
(@GoblinMask, @HunterMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @HunterMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @HunterMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @HunterMask, '69070', 'Rocket Jump'),
(@GoblinMask, @HunterMask, '75', 'Auto Shot'),
(@GoblinMask, @HunterMask, '81', 'Dodge'),
(@GoblinMask, @HunterMask, '196', 'One-Handed Axes'),
(@GoblinMask, @HunterMask, '203', 'Unarmed'),
(@GoblinMask, @HunterMask, '204', 'Defense'),
(@GoblinMask, @HunterMask, '264', 'Bows'),
(@GoblinMask, @HunterMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @HunterMask, '2382', 'Generic'),
(@GoblinMask, @HunterMask, '2479', 'Honorless Target'),
(@GoblinMask, @HunterMask, '2973', 'Raptor Strike'),
(@GoblinMask, @HunterMask, '3050', 'Detect'),
(@GoblinMask, @HunterMask, '3365', 'Opening'),
(@GoblinMask, @HunterMask, '6233', 'Closing'),
(@GoblinMask, @HunterMask, '6246', 'Closing'),
(@GoblinMask, @HunterMask, '6247', 'Opening'),
(@GoblinMask, @HunterMask, '6477', 'Opening'),
(@GoblinMask, @HunterMask, '6478', 'Opening'),
(@GoblinMask, @HunterMask, '6603', 'Attack'),
(@GoblinMask, @HunterMask, '7266', 'Duel'),
(@GoblinMask, @HunterMask, '7267', 'Grovel'),
(@GoblinMask, @HunterMask, '7355', 'Stuck'),
(@GoblinMask, @HunterMask, '8386', 'Attacking'),
(@GoblinMask, @HunterMask, '9077', 'Leather'),
(@GoblinMask, @HunterMask, '9078', 'Cloth'),
(@GoblinMask, @HunterMask, '9125', 'Generic'),
(@GoblinMask, @HunterMask, '13358', 'Defensive State(DND)'),
(@GoblinMask, @HunterMask, '21651', 'Opening'),
(@GoblinMask, @HunterMask, '21652', 'Closing'),
(@GoblinMask, @HunterMask, '22027', 'Remove Insignia'),
(@GoblinMask, @HunterMask, '22810', 'Opening - No Text'),
(@GoblinMask, @HunterMask, '24949', 'Defensive State 2(DND)'),
(@GoblinMask, @HunterMask, '34082', 'Advantaged State(DND)'),
(@GoblinMask, @HunterMask, '27014', 'Raptor Strike'),
(@GoblinMask, @HunterMask, '1494', 'Track Beasts'),
(@GoblinMask, @HunterMask, '13163', 'Aspect of the Monkey'),
(@GoblinMask, @HunterMask, '27016', 'Serpent Sting'),
(@GoblinMask, @HunterMask, '27019', 'Arcane Shot'),
(@GoblinMask, @HunterMask, '14325', 'Hunters Mark'),
(@GoblinMask, @HunterMask, '5116', 'Concussive Shot'),
(@GoblinMask, @HunterMask, '27044', 'Aspect of the Hawk'),
(@GoblinMask, @HunterMask, '883', 'Call Pet'),
(@GoblinMask, @HunterMask, '2641', 'Dismiss Pet'),
(@GoblinMask, @HunterMask, '6991', 'Feed Pet'),
(@GoblinMask, @HunterMask, '982', 'Revive Pet'),
(@GoblinMask, @HunterMask, '1515', 'Tame Beast'),
(@GoblinMask, @HunterMask, '19883', 'Track Humanoids'),
-- (@GoblinMask, @HunterMask, '27020', 'Distracting Shot'), -- Removed?
(@GoblinMask, @HunterMask, '27046', 'Mend Pet'),
(@GoblinMask, @HunterMask, '14268', 'Alliance Flag'), -- What?
(@GoblinMask, @HunterMask, '6197', 'Eagle Eye'),
(@GoblinMask, @HunterMask, '1002', 'Eyes of the Beast'),
(@GoblinMask, @HunterMask, '14327', 'Scare Beast'),
(@GoblinMask, @HunterMask, '27023', 'Immolation Trap'),
(@GoblinMask, @HunterMask, '36916', 'Mongoose Bite'),
(@GoblinMask, @HunterMask, '27021', 'Multi-Shot'),
(@GoblinMask, @HunterMask, '19884', 'Track Undead'),
(@GoblinMask, @HunterMask, '5118', 'Aspect of the Cheetah'),
-- (@GoblinMask, @HunterMask, '27015', 'Disengage'), -- Removed?
(@GoblinMask, @HunterMask, '14311', 'Freezing Trap'),
(@GoblinMask, @HunterMask, '3043', 'Scorpid Sting'),
(@GoblinMask, @HunterMask, '1462', 'Beast Lore'),
(@GoblinMask, @HunterMask, '19885', 'Track Hidden'),
(@GoblinMask, @HunterMask, '3045', 'Rapid Fire'),
(@GoblinMask, @HunterMask, '19880', 'Track Elementals'),
(@GoblinMask, @HunterMask, '13809', 'Frost Trap'),
(@GoblinMask, @HunterMask, '13161', 'Aspect of the Beast'),
(@GoblinMask, @HunterMask, '5384', 'Feign Death'),
(@GoblinMask, @HunterMask, '1543', 'Flare'),
(@GoblinMask, @HunterMask, '19878', 'Track Demons'),
(@GoblinMask, @HunterMask, '27025', 'Explosive Trap'),
-- (@GoblinMask, @HunterMask, '27018', 'Viper Sting'), -- Removed?
(@GoblinMask, @HunterMask, '13159', 'Aspect of the Pack'),
(@GoblinMask, @HunterMask, '19882', 'Track Giants'),
(@GoblinMask, @HunterMask, '27022', 'Volley'),
(@GoblinMask, @HunterMask, '27045', 'Aspect of the Wild'),
(@GoblinMask, @HunterMask, '19879', 'Track Dragonkin'),
(@GoblinMask, @HunterMask, '19801', 'Tranquilizing Shot'),
(@GoblinMask, @HunterMask, '34120', 'Steady Shot'),
(@GoblinMask, @HunterMask, '34074', 'Aspect of the Viper'),
(@GoblinMask, @HunterMask, '34026', 'Kill Command'),
(@GoblinMask, @HunterMask, '34600', 'Snake Trap'),
(@GoblinMask, @HunterMask, '34477', 'Misdirection'),
(@GoblinMask, @HunterMask, '674', 'Dual Wield'),
(@GoblinMask, @HunterMask, '8737', 'Mail'),
(@GoblinMask, @HunterMask, '5149', 'Beast Training'), -- Only 8?
(@GoblinMask, @HunterMask, '3127', 'Parry'),

-- Goblin Rogue
(@GoblinMask, @RogueMask, '669', 'Language Orcish'),
(@GoblinMask, @RogueMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @RogueMask, '69042', 'Time is Money'),
(@GoblinMask, @RogueMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @RogueMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @RogueMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @RogueMask, '69070', 'Rocket Jump'),
(@GoblinMask, @RogueMask, '81', 'Dodge'),
(@GoblinMask, @RogueMask, '203', 'Unarmed'),
(@GoblinMask, @RogueMask, '204', 'Defense'),
(@GoblinMask, @RogueMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @RogueMask, '1180', 'Daggers'),
(@GoblinMask, @RogueMask, '1752', 'Sinister Strike'),
(@GoblinMask, @RogueMask, '2098', 'Eviscerate'),
(@GoblinMask, @RogueMask, '2382', 'Generic'),
(@GoblinMask, @RogueMask, '2479', 'Honorless Target'),
(@GoblinMask, @RogueMask, '2567', 'Thrown'),
(@GoblinMask, @RogueMask, '2764', 'Throw'),
(@GoblinMask, @RogueMask, '3050', 'Detect'),
(@GoblinMask, @RogueMask, '3365', 'Opening'),
(@GoblinMask, @RogueMask, '6233', 'Closing'),
(@GoblinMask, @RogueMask, '6246', 'Closing'),
(@GoblinMask, @RogueMask, '6247', 'Opening'),
(@GoblinMask, @RogueMask, '6477', 'Opening'),
(@GoblinMask, @RogueMask, '6478', 'Opening'),
(@GoblinMask, @RogueMask, '6603', 'Attack'),
(@GoblinMask, @RogueMask, '7266', 'Duel'),
(@GoblinMask, @RogueMask, '7267', 'Grovel'),
(@GoblinMask, @RogueMask, '7355', 'Stuck'),
(@GoblinMask, @RogueMask, '8386', 'Attacking'),
(@GoblinMask, @RogueMask, '9077', 'Leather'),
(@GoblinMask, @RogueMask, '9078', 'Cloth'),
(@GoblinMask, @RogueMask, '9125', 'Generic'),
(@GoblinMask, @RogueMask, '16092', 'Defensive State(DND)'),
(@GoblinMask, @RogueMask, '21184', 'Rogue Passive(DND)'),
(@GoblinMask, @RogueMask, '21651', 'Opening'),
(@GoblinMask, @RogueMask, '21652', 'Closing'),
(@GoblinMask, @RogueMask, '22027', 'Remove Insignia'),
(@GoblinMask, @RogueMask, '22810', 'Opening - No Text'),
(@GoblinMask, @RogueMask, '26865', 'Eviscerate'),
(@GoblinMask, @RogueMask, '26862', 'Sinister Strike'),
(@GoblinMask, @RogueMask, '1787', 'Stealth'),
(@GoblinMask, @RogueMask, '26863', 'Backstab'),
(@GoblinMask, @RogueMask, '921', 'Pick Pocket'),
(@GoblinMask, @RogueMask, '38764', 'Gouge'),
(@GoblinMask, @RogueMask, '26669', 'Evasion'),
(@GoblinMask, @RogueMask, '11297', 'Sap'),
(@GoblinMask, @RogueMask, '6774', 'Slice and Dice'),
(@GoblinMask, @RogueMask, '11305', 'Sprint'),
(@GoblinMask, @RogueMask, '38768', 'Kick'),
(@GoblinMask, @RogueMask, '26866', 'Expose Armor'),
(@GoblinMask, @RogueMask, '26884', 'Garrote'),
(@GoblinMask, @RogueMask, '27448', 'Feint'),
(@GoblinMask, @RogueMask, '1804', 'Pick Lock'),
(@GoblinMask, @RogueMask, '27441', 'Ambush'),
(@GoblinMask, @RogueMask, '2842', 'Poisons'),
(@GoblinMask, @RogueMask, '1725', 'Distract'),
(@GoblinMask, @RogueMask, '26867', 'Rupture'),
(@GoblinMask, @RogueMask, '26889', 'Vanish'),
(@GoblinMask, @RogueMask, '1833', 'Cheap Shot'),
(@GoblinMask, @RogueMask, '1842', 'Disarm Trap'),
(@GoblinMask, @RogueMask, '408', 'Kidney Shot'),
(@GoblinMask, @RogueMask, '2094', 'Blind'),
(@GoblinMask, @RogueMask, '32684', 'Envenom'),
(@GoblinMask, @RogueMask, '26679', 'Deadly Throw'),
(@GoblinMask, @RogueMask, '31224', 'Cloak of Shadows'),
(@GoblinMask, @RogueMask, '5938', 'Shiv'),
(@GoblinMask, @RogueMask, '8643', 'Kidney Shot'),
(@GoblinMask, @RogueMask, '3127', 'Parry'),
(@GoblinMask, @RogueMask, '674', 'Dual Wield'),
(@GoblinMask, @RogueMask, '3776', 'Green Leather Bracers'),
-- (@GoblinMask, @RogueMask, '9186', null), -- Removed?
(@GoblinMask, @RogueMask, '21927', 'Natures Ally'),
(@GoblinMask, @RogueMask, '22054', 'QAEnchant Bracer +7 Intellect'),
-- (@GoblinMask, @RogueMask, '22055', null), -- Removed?
(@GoblinMask, @RogueMask, '2836', 'Detect Traps'),
(@GoblinMask, @RogueMask, '1860', 'Safe Fall'),

-- Goblin Priest
(@GoblinMask, @PriestMask, '669', 'Language Orcish'),
(@GoblinMask, @PriestMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @PriestMask, '69042', 'Time is Money'),
(@GoblinMask, @PriestMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @PriestMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @PriestMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @PriestMask, '69070', 'Rocket Jump'),
(@GoblinMask, @PriestMask, '81', 'Dodge'),
(@GoblinMask, @PriestMask, '198', 'One-Handed Maces'),
(@GoblinMask, @PriestMask, '203', 'Unarmed'),
(@GoblinMask, @PriestMask, '204', 'Defense'),
(@GoblinMask, @PriestMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @PriestMask, '585', 'Smite'),
(@GoblinMask, @PriestMask, '2050', 'Lesser Heal'),
(@GoblinMask, @PriestMask, '2382', 'Generic'),
(@GoblinMask, @PriestMask, '2479', 'Honorless Target'),
(@GoblinMask, @PriestMask, '3050', 'Detect'),
(@GoblinMask, @PriestMask, '3365', 'Opening'),
(@GoblinMask, @PriestMask, '5009', 'Wands'),
(@GoblinMask, @PriestMask, '5019', 'Shoot'),
(@GoblinMask, @PriestMask, '6233', 'Closing'),
(@GoblinMask, @PriestMask, '6246', 'Closing'),
(@GoblinMask, @PriestMask, '6247', 'Opening'),
(@GoblinMask, @PriestMask, '6477', 'Opening'),
(@GoblinMask, @PriestMask, '6478', 'Opening'),
(@GoblinMask, @PriestMask, '6603', 'Attack'),
(@GoblinMask, @PriestMask, '7266', 'Duel'),
(@GoblinMask, @PriestMask, '7267', 'Grovel'),
(@GoblinMask, @PriestMask, '7355', 'Stuck'),
(@GoblinMask, @PriestMask, '8386', 'Attacking'),
(@GoblinMask, @PriestMask, '9078', 'Cloth'),
(@GoblinMask, @PriestMask, '9125', 'Generic'),
(@GoblinMask, @PriestMask, '21651', 'Opening'),
(@GoblinMask, @PriestMask, '21652', 'Closing'),
(@GoblinMask, @PriestMask, '22027', 'Remove Insignia'),
(@GoblinMask, @PriestMask, '22810', 'Opening - No Text'),
(@GoblinMask, @PriestMask, '25389', 'Power Word: Fortitude'),
(@GoblinMask, @PriestMask, '25364', 'Smite'),
(@GoblinMask, @PriestMask, '25368', 'Shadow Word: Pain'),
(@GoblinMask, @PriestMask, '25218', 'Power Word: Shield'),
-- (@GoblinMask, @PriestMask, '25429', 'Fade'), -- Removed?
(@GoblinMask, @PriestMask, '25222', 'Renew'),
(@GoblinMask, @PriestMask, '25375', 'Mind Blast'),
(@GoblinMask, @PriestMask, '25435', 'Resurrection'),
(@GoblinMask, @PriestMask, '25431', 'Inner Fire'),
(@GoblinMask, @PriestMask, '528', 'Cure Disease'),
(@GoblinMask, @PriestMask, '10890', 'Psychic Scream'),
(@GoblinMask, @PriestMask, '988', 'Dispel Magic'),
(@GoblinMask, @PriestMask, '6346', 'Fear Ward'),
(@GoblinMask, @PriestMask, '25235', 'Flash Heal'),
(@GoblinMask, @PriestMask, '25384', 'Holy Fire'),
-- (@GoblinMask, @PriestMask, '25596', 'Mind Soothe'), -- Removed?
(@GoblinMask, @PriestMask, '10955', 'Shackle Undead'),
(@GoblinMask, @PriestMask, '10909', 'Mind Vision'),
-- (@GoblinMask, @PriestMask, '25380', 'Mana Burn'), -- Removed?
-- (@GoblinMask, @PriestMask, '10912', 'Mind Control'), -- Removed?
(@GoblinMask, @PriestMask, '25308', 'Prayer of Healing'),
(@GoblinMask, @PriestMask, '25433', 'Shadow Protection'),
(@GoblinMask, @PriestMask, '552', 'Abolish Disease'),
(@GoblinMask, @PriestMask, '1706', 'Levitate'),
(@GoblinMask, @PriestMask, '25213', 'Greater Heal'),
(@GoblinMask, @PriestMask, '25392', 'Prayer of Fortitude'),
(@GoblinMask, @PriestMask, '39374', 'Prayer of Shadow Protection'),
(@GoblinMask, @PriestMask, '32999', 'Prayer of Spirit'),
(@GoblinMask, @PriestMask, '32996', 'Shadow Word: Death'),
(@GoblinMask, @PriestMask, '32546', 'Binding Heal'),
(@GoblinMask, @PriestMask, '34433', 'Shadowfiend'),
(@GoblinMask, @PriestMask, '33076', 'Prayer of Mending'),
(@GoblinMask, @PriestMask, '32375', 'Mass Dispel'),
-- (@GoblinMask, @PriestMask, '25441', 'Feedback'), -- Removed?
(@GoblinMask, @PriestMask, '25312', 'Divine Spirit'),
(@GoblinMask, @PriestMask, '25437', 'Desperate Prayer'),

-- Goblin Shaman
(@GoblinMask, @ShamanMask, '669', 'Language Orcish'),
(@GoblinMask, @ShamanMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @ShamanMask, '69042', 'Time is Money'),
(@GoblinMask, @ShamanMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @ShamanMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @ShamanMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @ShamanMask, '69070', 'Rocket Jump'),
(@GoblinMask, @ShamanMask, '81', 'Dodge'),
(@GoblinMask, @ShamanMask, '107', 'Block'),
(@GoblinMask, @ShamanMask, '198', 'One-Handed Maces'),
(@GoblinMask, @ShamanMask, '203', 'Unarmed'),
(@GoblinMask, @ShamanMask, '204', 'Defense'),
(@GoblinMask, @ShamanMask, '227', 'Staves'),
(@GoblinMask, @ShamanMask, '331', 'Healing Wave'),
(@GoblinMask, @ShamanMask, '403', 'Lightning Bolt'),
(@GoblinMask, @ShamanMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @ShamanMask, '2382', 'Generic'),
(@GoblinMask, @ShamanMask, '2479', 'Honorless Target'),
(@GoblinMask, @ShamanMask, '3050', 'Detect'),
(@GoblinMask, @ShamanMask, '3365', 'Opening'),
(@GoblinMask, @ShamanMask, '6233', 'Closing'),
(@GoblinMask, @ShamanMask, '6246', 'Closing'),
(@GoblinMask, @ShamanMask, '6247', 'Opening'),
(@GoblinMask, @ShamanMask, '6477', 'Opening'),
(@GoblinMask, @ShamanMask, '6478', 'Opening'),
(@GoblinMask, @ShamanMask, '6603', 'Attack'),
(@GoblinMask, @ShamanMask, '7266', 'Duel'),
(@GoblinMask, @ShamanMask, '7267', 'Grovel'),
(@GoblinMask, @ShamanMask, '7355', 'Stuck'),
(@GoblinMask, @ShamanMask, '8386', 'Attacking'),
(@GoblinMask, @ShamanMask, '9077', 'Leather'),
(@GoblinMask, @ShamanMask, '9078', 'Cloth'),
(@GoblinMask, @ShamanMask, '9116', 'Shield'),
(@GoblinMask, @ShamanMask, '9125', 'Generic'),
(@GoblinMask, @ShamanMask, '21651', 'Opening'),
(@GoblinMask, @ShamanMask, '21652', 'Closing'),
(@GoblinMask, @ShamanMask, '22027', 'Remove Insignia'),
(@GoblinMask, @ShamanMask, '22810', 'Opening - No Text'),
(@GoblinMask, @ShamanMask, '27763', 'Totem'),
(@GoblinMask, @ShamanMask, '25396', 'Healing Wave'),
(@GoblinMask, @ShamanMask, '25449', 'Lightning Bolt'),
-- (@GoblinMask, @ShamanMask, '25485', 'Rockbiter Weapon'), -- Removed?
(@GoblinMask, @ShamanMask, '25454', 'Earth Shock'),
(@GoblinMask, @ShamanMask, '25509', 'Stoneskin Totem'),
(@GoblinMask, @ShamanMask, '2484', 'Earthbind Totem'),
(@GoblinMask, @ShamanMask, '25472', 'Lightning Shield'),
(@GoblinMask, @ShamanMask, '25525', 'Stoneclaw Totem'),
(@GoblinMask, @ShamanMask, '25457', 'Flame Shock'),
(@GoblinMask, @ShamanMask, '25489', 'Flametongue Weapon'),
(@GoblinMask, @ShamanMask, '25533', 'Searing Totem'),
(@GoblinMask, @ShamanMask, '25528', 'Strength of Earth Totem'),
(@GoblinMask, @ShamanMask, '20777', 'Ancestral Spirit'),
(@GoblinMask, @ShamanMask, '25547', 'Fire Nova'),
(@GoblinMask, @ShamanMask, '8012', 'Purge'),
(@GoblinMask, @ShamanMask, '526', 'Cure Toxins'),
(@GoblinMask, @ShamanMask, '8143', 'Tremor Totem'),
(@GoblinMask, @ShamanMask, '25464', 'Frost Shock'),
(@GoblinMask, @ShamanMask, '25500', 'Frostbrand Weapon'),
(@GoblinMask, @ShamanMask, '2645', 'Ghost Wolf'),
(@GoblinMask, @ShamanMask, '25567', 'Healing Stream Totem'),
(@GoblinMask, @ShamanMask, '25420', 'Lesser Healing Wave'),
-- (@GoblinMask, @ShamanMask, '2870', 'Cure Disease'), -- Removed?
(@GoblinMask, @ShamanMask, '8166', 'Poison Cleansing Totem'),
(@GoblinMask, @ShamanMask, '131', 'Water Breathing'),
(@GoblinMask, @ShamanMask, '25560', 'Frost Resistance Totem'),
(@GoblinMask, @ShamanMask, '6196', 'Far Sight'),
(@GoblinMask, @ShamanMask, '25552', 'Magma Totem'),
(@GoblinMask, @ShamanMask, '25570', 'Mana Spring Totem'),
(@GoblinMask, @ShamanMask, '25563', 'Fire Resistance Totem'),
(@GoblinMask, @ShamanMask, '25557', 'Flametongue Totem'),
(@GoblinMask, @ShamanMask, '546', 'Water Walking'),
(@GoblinMask, @ShamanMask, '556', 'Astral Recall'),
(@GoblinMask, @ShamanMask, '8177', 'Grounding Totem'),
(@GoblinMask, @ShamanMask, '25574', 'Nature Resistance Totem'),
(@GoblinMask, @ShamanMask, '36936', 'Totemic Recall'),
(@GoblinMask, @ShamanMask, '25505', 'Windfury Weapon'),
(@GoblinMask, @ShamanMask, '421', 'Chain Lightning'),
-- (@GoblinMask, @ShamanMask, '25587', 'Windfury Totem'), -- Removed?
(@GoblinMask, @ShamanMask, '6495', 'Sentry Totem'),
-- (@GoblinMask, @ShamanMask, '25577', 'Windwall Totem'), -- Removed?
(@GoblinMask, @ShamanMask, '8170', 'Cleansing Totem'),
(@GoblinMask, @ShamanMask, '25423', 'Chain Heal'),
-- (@GoblinMask, @ShamanMask, '25359', 'Grace of Air Totem'), -- Removed?
-- (@GoblinMask, @ShamanMask, '25908', 'Tranquil Air Totem'), -- Removed?
(@GoblinMask, @ShamanMask, '33736', 'Water Shield'),
(@GoblinMask, @ShamanMask, '3738', 'Wrath of Air Totem'),
(@GoblinMask, @ShamanMask, '2062', 'Earth Elemental Totem'),
(@GoblinMask, @ShamanMask, '2894', 'Fire Elemental Totem'),
(@GoblinMask, @ShamanMask, '2825', 'Bloodlust'), -- Only 9?
(@GoblinMask, @ShamanMask, '25442', 'Chain Lightning'), -- Only 6?
(@GoblinMask, @ShamanMask, '8737', 'Mail'),
(@GoblinMask, @ShamanMask, '20608', 'Reincarnation'), -- Only 6?

-- Goblin Mage
(@GoblinMask, @MageMask, '669', 'Language Orcish'),
(@GoblinMask, @MageMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @MageMask, '69042', 'Time is Money'),
(@GoblinMask, @MageMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @MageMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @MageMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @MageMask, '69070', 'Rocket Jump'),
(@GoblinMask, @MageMask, '81', 'Dodge'),
(@GoblinMask, @MageMask, '133', 'Fireball'),
(@GoblinMask, @MageMask, '168', 'Frost Armor'),
(@GoblinMask, @MageMask, '203', 'Unarmed'),
(@GoblinMask, @MageMask, '204', 'Defense'),
(@GoblinMask, @MageMask, '227', 'Staves'),
(@GoblinMask, @MageMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @MageMask, '2382', 'Generic'),
(@GoblinMask, @MageMask, '2479', 'Honorless Target'),
(@GoblinMask, @MageMask, '3050', 'Detect'),
(@GoblinMask, @MageMask, '3365', 'Opening'),
(@GoblinMask, @MageMask, '5009', 'Wands'),
(@GoblinMask, @MageMask, '5019', 'Shoot'),
(@GoblinMask, @MageMask, '6233', 'Closing'),
(@GoblinMask, @MageMask, '6246', 'Closing'),
(@GoblinMask, @MageMask, '6247', 'Opening'),
(@GoblinMask, @MageMask, '6477', 'Opening'),
(@GoblinMask, @MageMask, '6478', 'Opening'),
(@GoblinMask, @MageMask, '6603', 'Attack'),
(@GoblinMask, @MageMask, '7266', 'Duel'),
(@GoblinMask, @MageMask, '7267', 'Grovel'),
(@GoblinMask, @MageMask, '7355', 'Stuck'),
(@GoblinMask, @MageMask, '8386', 'Attacking'),
(@GoblinMask, @MageMask, '9078', 'Cloth'),
(@GoblinMask, @MageMask, '9125', 'Generic'),
(@GoblinMask, @MageMask, '21651', 'Opening'),
(@GoblinMask, @MageMask, '21652', 'Closing'),
(@GoblinMask, @MageMask, '22027', 'Remove Insignia'),
(@GoblinMask, @MageMask, '22810', 'Opening - No Text'),
(@GoblinMask, @MageMask, '27126', 'Arcane Intellect'),
(@GoblinMask, @MageMask, '27070', 'Fireball'),
(@GoblinMask, @MageMask, '22018', null),
(@GoblinMask, @MageMask, '27072', 'Frostbolt'),
(@GoblinMask, @MageMask, '22019', null),
(@GoblinMask, @MageMask, '27079', 'Fire Blast'),
(@GoblinMask, @MageMask, '38704', 'Arcane Missiles'),
(@GoblinMask, @MageMask, '28272', 'Polymorph (Pig)'),
(@GoblinMask, @MageMask, '28271', 'Polymorph (Turtle)'),
(@GoblinMask, @MageMask, '12826', 'Polymorph (Sheep)'),
(@GoblinMask, @MageMask, '27088', 'Frost Nova'),
(@GoblinMask, @MageMask, '33944', 'Dampen Magic'),
(@GoblinMask, @MageMask, '130', 'Slow Fall'),
(@GoblinMask, @MageMask, '27082', 'Arcane Explosion'),
(@GoblinMask, @MageMask, '27086', 'Flamestrike'),
(@GoblinMask, @MageMask, '33946', 'Amplify Magic'),
(@GoblinMask, @MageMask, '475', 'Remove Curse'),
(@GoblinMask, @MageMask, '1953', 'Blink'),
(@GoblinMask, @MageMask, '27085', 'Blizzard'),
(@GoblinMask, @MageMask, '12051', 'Evocation'),
(@GoblinMask, @MageMask, '27128', 'Fire Ward'),
(@GoblinMask, @MageMask, '27131', 'Mana Shield'),
(@GoblinMask, @MageMask, '32796', 'Frost Ward'),
(@GoblinMask, @MageMask, '27074', 'Scorch'),
(@GoblinMask, @MageMask, '2139', 'Counterspell'),
(@GoblinMask, @MageMask, '27101', 'Conjure Mana Gem'),
(@GoblinMask, @MageMask, '27124', 'Ice Armor'),
(@GoblinMask, @MageMask, '45438', 'Ice Block'),
(@GoblinMask, @MageMask, '27125', 'Mage Armor'),
(@GoblinMask, @MageMask, '27127', 'Arcane Brilliance'),
(@GoblinMask, @MageMask, '30482', 'Molten Armor'),
(@GoblinMask, @MageMask, '30451', 'Arcane Blast'),
(@GoblinMask, @MageMask, '30455', 'Ice Lance'),
(@GoblinMask, @MageMask, '66', 'Invisibility'),
(@GoblinMask, @MageMask, '43987', 'Ritual of Refreshment'),
(@GoblinMask, @MageMask, '30449', 'Spellsteal'),
(@GoblinMask, @MageMask, '27087', 'Cone of Cold'),

-- Goblin Warlock
(@GoblinMask, @WarlockMask, '669', 'Language Orcish'),
(@GoblinMask, @WarlockMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @WarlockMask, '69042', 'Time is Money'),
(@GoblinMask, @WarlockMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @WarlockMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @WarlockMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @WarlockMask, '69070', 'Rocket Jump'),
(@GoblinMask, @WarlockMask, '81', 'Dodge'),
(@GoblinMask, @WarlockMask, '203', 'Unarmed'),
(@GoblinMask, @WarlockMask, '204', 'Defense'),
(@GoblinMask, @WarlockMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @WarlockMask, '686', 'Shadow Bolt'),
(@GoblinMask, @WarlockMask, '687', 'Demon Skin'),
(@GoblinMask, @WarlockMask, '1180', 'Daggers'),
(@GoblinMask, @WarlockMask, '2382', 'Generic'),
(@GoblinMask, @WarlockMask, '2479', 'Honorless Target'),
(@GoblinMask, @WarlockMask, '3050', 'Detect'),
(@GoblinMask, @WarlockMask, '3365', 'Opening'),
(@GoblinMask, @WarlockMask, '5009', 'Wands'),
(@GoblinMask, @WarlockMask, '5019', 'Shoot'),
(@GoblinMask, @WarlockMask, '6233', 'Closing'),
(@GoblinMask, @WarlockMask, '6246', 'Closing'),
(@GoblinMask, @WarlockMask, '6247', 'Opening'),
(@GoblinMask, @WarlockMask, '6477', 'Opening'),
(@GoblinMask, @WarlockMask, '6478', 'Opening'),
(@GoblinMask, @WarlockMask, '6603', 'Attack'),
(@GoblinMask, @WarlockMask, '7266', 'Duel'),
(@GoblinMask, @WarlockMask, '7267', 'Grovel'),
(@GoblinMask, @WarlockMask, '7355', 'Stuck'),
(@GoblinMask, @WarlockMask, '8386', 'Attacking'),
(@GoblinMask, @WarlockMask, '9078', 'Cloth'),
(@GoblinMask, @WarlockMask, '9125', 'Generic'),
(@GoblinMask, @WarlockMask, '21651', 'Opening'),
(@GoblinMask, @WarlockMask, '21652', 'Closing'),
(@GoblinMask, @WarlockMask, '22027', 'Remove Insignia'),
(@GoblinMask, @WarlockMask, '22810', 'Opening - No Text'),
(@GoblinMask, @WarlockMask, '27215', 'Immolate'),
(@GoblinMask, @WarlockMask, '27209', 'Shadow Bolt'),
(@GoblinMask, @WarlockMask, '27216', 'Corruption'),
(@GoblinMask, @WarlockMask, '30909', 'Curse of Weakness'),
(@GoblinMask, @WarlockMask, '27222', 'Life Tap'),
(@GoblinMask, @WarlockMask, '27218', 'Curse of Agony'),
(@GoblinMask, @WarlockMask, '6215', 'Fear'),
(@GoblinMask, @WarlockMask, '27230', 'Create Healthstone'),
(@GoblinMask, @WarlockMask, '27217', 'Drain Soul'),
(@GoblinMask, @WarlockMask, '27259', 'Health Funnel'),
-- (@GoblinMask, @WarlockMask, '27226', 'Curse of Recklessness'), -- Removed?
(@GoblinMask, @WarlockMask, '27220', 'Drain Life'),
(@GoblinMask, @WarlockMask, '5697', 'Unending Breath'),
(@GoblinMask, @WarlockMask, '27238', 'Create Soulstone'),
(@GoblinMask, @WarlockMask, '30459', 'Searing Pain'),
(@GoblinMask, @WarlockMask, '27260', 'Demon Armor'),
(@GoblinMask, @WarlockMask, '27212', 'Rain of Fire'),
(@GoblinMask, @WarlockMask, '698', 'Ritual of Summoning'),
(@GoblinMask, @WarlockMask, '5500', 'Sense Demons'),
-- (@GoblinMask, @WarlockMask, '30908', 'Drain Mana'), -- Removed?
(@GoblinMask, @WarlockMask, '11719', 'Curse of Tongues'),
(@GoblinMask, @WarlockMask, '132', 'Detect Invisibility'),
(@GoblinMask, @WarlockMask, '18647', 'Banish'),
(@GoblinMask, @WarlockMask, '27213', 'Hellfire'),
(@GoblinMask, @WarlockMask, '11726', 'Subjugate Demon'),
(@GoblinMask, @WarlockMask, '27228', 'Curse of the Elements'),
(@GoblinMask, @WarlockMask, '28610', 'Shadow Ward'),
(@GoblinMask, @WarlockMask, '28172', 'Create Spellstone'),
(@GoblinMask, @WarlockMask, '27250', 'Create Firestone'),
(@GoblinMask, @WarlockMask, '17928', 'Howl of Terror'),
(@GoblinMask, @WarlockMask, '27223', 'Death Coil'),
-- (@GoblinMask, @WarlockMask, '27229', 'Curse of Shadow'), -- Removed?
(@GoblinMask, @WarlockMask, '30545', 'Soul Fire'),
(@GoblinMask, @WarlockMask, '30910', 'Curse of Doom'),
(@GoblinMask, @WarlockMask, '18540', 'Ritual of Doom'),
(@GoblinMask, @WarlockMask, '28189', 'Fel Armor'),
(@GoblinMask, @WarlockMask, '32231', 'Incinerate'),
(@GoblinMask, @WarlockMask, '29858', 'Soulshatter'),
(@GoblinMask, @WarlockMask, '29893', 'Ritual of Souls'),
(@GoblinMask, @WarlockMask, '27243', 'Seed of Corruption'),
(@GoblinMask, @WarlockMask, '23161', 'Dreadsteed'),
(@GoblinMask, @WarlockMask, '688', 'Summon Imp'),
(@GoblinMask, @WarlockMask, '697', 'Summon Voidwalker'),
(@GoblinMask, @WarlockMask, '712', 'Summon Succubus'),
(@GoblinMask, @WarlockMask, '691', 'Summon Felhunter'),
(@GoblinMask, @WarlockMask, '126', 'Eye of Kilrogg');
