INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Goblin Paladin
(@GoblinMask, @PaladinMask, '669', 'Language Orcish'),
(@GoblinMask, @PaladinMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @PaladinMask, '69042', 'Time is Money'),
(@GoblinMask, @PaladinMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @PaladinMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @PaladinMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @PaladinMask, '69070', 'Rocket Jump'),
(@GoblinMask, @PaladinMask, '81', 'Dodge'),
(@GoblinMask, @PaladinMask, '107', 'Block'),
(@GoblinMask, @PaladinMask, '198', 'One-Handed Maces'),
(@GoblinMask, @PaladinMask, '199', 'Two-Handed Maces'),
(@GoblinMask, @PaladinMask, '203', 'Unarmed'),
(@GoblinMask, @PaladinMask, '204', 'Defense'),
(@GoblinMask, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @PaladinMask, '635', 'Holy Light'),
(@GoblinMask, @PaladinMask, '750', 'Plate Armor'),
-- (@GoblinMask, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@GoblinMask, @PaladinMask, '1038', 'Hand of Salvation'),
(@GoblinMask, @PaladinMask, '1044', 'Hand of Freedom'),
(@GoblinMask, @PaladinMask, '2382', 'Generic'),
(@GoblinMask, @PaladinMask, '2479', 'Honorless Target'),
(@GoblinMask, @PaladinMask, '3050', 'Detect'),
(@GoblinMask, @PaladinMask, '3127', 'Parry'),
(@GoblinMask, @PaladinMask, '3365', 'Opening'),
(@GoblinMask, @PaladinMask, '4987', 'Cleanse'),
(@GoblinMask, @PaladinMask, '5502', 'Sense Undead'),
-- (@GoblinMask, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@GoblinMask, @PaladinMask, '6233', 'Closing'),
(@GoblinMask, @PaladinMask, '6246', 'Closing'),
(@GoblinMask, @PaladinMask, '6247', 'Opening'),
(@GoblinMask, @PaladinMask, '6477', 'Opening'),
(@GoblinMask, @PaladinMask, '6478', 'Opening'),
(@GoblinMask, @PaladinMask, '6603', 'Attack'),
(@GoblinMask, @PaladinMask, '7266', 'Duel'),
(@GoblinMask, @PaladinMask, '7267', 'Grovel'),
(@GoblinMask, @PaladinMask, '7355', 'Stuck'),
(@GoblinMask, @PaladinMask, '8386', 'Attacking'),
(@GoblinMask, @PaladinMask, '8737', 'Mail'),
(@GoblinMask, @PaladinMask, '9077', 'Leather'),
(@GoblinMask, @PaladinMask, '9078', 'Cloth'),
(@GoblinMask, @PaladinMask, '9116', 'Shield'),
(@GoblinMask, @PaladinMask, '9125', 'Generic'),
(@GoblinMask, @PaladinMask, '10278', 'Hand of Protection'),
(@GoblinMask, @PaladinMask, '10308', 'Hammer of Justice'),
(@GoblinMask, @PaladinMask, '10326', 'Turn Evil'),
(@GoblinMask, @PaladinMask, '19746', 'Concentration Aura'),
(@GoblinMask, @PaladinMask, '19752', 'Divine Intervention'),
(@GoblinMask, @PaladinMask, '20271', 'Judgement of Light'),
(@GoblinMask, @PaladinMask, '20773', 'Redemption'),
(@GoblinMask, @PaladinMask, '21084', 'Seal of Righteousness'),
(@GoblinMask, @PaladinMask, '21651', 'Opening'),
(@GoblinMask, @PaladinMask, '21652', 'Closing'),
(@GoblinMask, @PaladinMask, '22027', 'Remove Insignia'),
(@GoblinMask, @PaladinMask, '22810', 'Opening - No Text'),
(@GoblinMask, @PaladinMask, '23214', 'Charger'),
(@GoblinMask, @PaladinMask, '25780', 'Righteous Fury'),
-- (@GoblinMask, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@GoblinMask, @PaladinMask, '25898', 'Greater Blessing of Kings'),
(@GoblinMask, @PaladinMask, '27136', 'Holy Light'),
(@GoblinMask, @PaladinMask, '27137', 'Flash of Light'),
(@GoblinMask, @PaladinMask, '27138', 'Exorcism'),
(@GoblinMask, @PaladinMask, '27139', 'Holy Wrath'),
(@GoblinMask, @PaladinMask, '27140', 'Blessing of Might'),
(@GoblinMask, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@GoblinMask, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@GoblinMask, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
-- (@GoblinMask, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@GoblinMask, @PaladinMask, '27149', 'Devotion Aura'),
(@GoblinMask, @PaladinMask, '27150', 'Retribution Aura'),
(@GoblinMask, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@GoblinMask, @PaladinMask, '27152', 'Frost Resistance Aura'),
(@GoblinMask, @PaladinMask, '27153', 'Fire Resistance Aura'),
(@GoblinMask, @PaladinMask, '27154', 'Lay on Hands'),
-- (@GoblinMask, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@GoblinMask, @PaladinMask, '27173', 'Consecration'),
(@GoblinMask, @PaladinMask, '27180', 'Hammer of Wrath'),
(@GoblinMask, @PaladinMask, '27762', 'Libram'),
(@GoblinMask, @PaladinMask, '31789', 'Righteous Defense'),
(@GoblinMask, @PaladinMask, '31801', 'Seal of Vengeance'),
(@GoblinMask, @PaladinMask, '31884', 'Avenging Wrath'),
-- (@GoblinMask, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
(@GoblinMask, @PaladinMask, '32223', 'Crusader Aura'),
(@GoblinMask, @PaladinMask, '33776', 'Spiritual Attunement'),

-- Goblin Druid
(@GoblinMask, @DruidMask, '669', 'Language Orcish'),
(@GoblinMask, @DruidMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @DruidMask, '69042', 'Time is Money'),
(@GoblinMask, @DruidMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @DruidMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @DruidMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @DruidMask, '69070', 'Rocket Jump'),
(@GoblinMask, @DruidMask, '81', 'Dodge'),
(@GoblinMask, @DruidMask, '198', 'One-Handed Maces'),
(@GoblinMask, @DruidMask, '203', 'Unarmed'),
(@GoblinMask, @DruidMask, '204', 'Defense'),
(@GoblinMask, @DruidMask, '227', 'Staves'),
(@GoblinMask, @DruidMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @DruidMask, '1178', 'Bear Form(Passive)'),
(@GoblinMask, @DruidMask, '2382', 'Generic'),
(@GoblinMask, @DruidMask, '2479', 'Honorless Target'),
(@GoblinMask, @DruidMask, '3025', 'Cat Form(Passive)'),
(@GoblinMask, @DruidMask, '3050', 'Detect'),
(@GoblinMask, @DruidMask, '3365', 'Opening'),
(@GoblinMask, @DruidMask, '5176', 'Wrath'),
(@GoblinMask, @DruidMask, '5185', 'Healing Touch'),
(@GoblinMask, @DruidMask, '5419', 'Travel Form(Passive)'),
(@GoblinMask, @DruidMask, '5420', 'Tree of Life'),
(@GoblinMask, @DruidMask, '5421', 'Aquatic Form(Passive)'),
(@GoblinMask, @DruidMask, '6233', 'Closing'),
(@GoblinMask, @DruidMask, '6246', 'Closing'),
(@GoblinMask, @DruidMask, '6247', 'Opening'),
(@GoblinMask, @DruidMask, '6477', 'Opening'),
(@GoblinMask, @DruidMask, '6478', 'Opening'),
(@GoblinMask, @DruidMask, '6603', 'Attack'),
(@GoblinMask, @DruidMask, '7266', 'Duel'),
(@GoblinMask, @DruidMask, '7267', 'Grovel'),
(@GoblinMask, @DruidMask, '7355', 'Stuck'),
(@GoblinMask, @DruidMask, '8386', 'Attacking'),
(@GoblinMask, @DruidMask, '9077', 'Leather'),
(@GoblinMask, @DruidMask, '9078', 'Cloth'),
(@GoblinMask, @DruidMask, '9125', 'Generic'),
(@GoblinMask, @DruidMask, '9635', 'Dire Bear Form(Passive)'),
(@GoblinMask, @DruidMask, '21178', 'Bear Form(Passive2)'),
(@GoblinMask, @DruidMask, '21651', 'Opening'),
(@GoblinMask, @DruidMask, '21652', 'Closing'),
(@GoblinMask, @DruidMask, '22027', 'Remove Insignia'),
(@GoblinMask, @DruidMask, '22810', 'Opening - No Text'),
(@GoblinMask, @DruidMask, '24905', 'Moonkin Form(Passive)'),
(@GoblinMask, @DruidMask, '27764', 'Fetish'),
(@GoblinMask, @DruidMask, '33948', 'Flight Form(Passive)'),
(@GoblinMask, @DruidMask, '34123', 'Tree of Life(Passive)'),
(@GoblinMask, @DruidMask, '40121', 'Swift Flight Form(Passive)'),
(@GoblinMask, @DruidMask, '26979', 'Healing Touch'),
(@GoblinMask, @DruidMask, '26990', 'Mark of the Wild'),
(@GoblinMask, @DruidMask, '26985', 'Wrath'),
(@GoblinMask, @DruidMask, '26988', 'Moonfire'),
(@GoblinMask, @DruidMask, '26982', 'Rejuvenation'),
(@GoblinMask, @DruidMask, '26992', 'Thorns'),
(@GoblinMask, @DruidMask, '26989', 'Entangling Roots'),
(@GoblinMask, @DruidMask, '26998', 'Demoralizing Roar'),
(@GoblinMask, @DruidMask, '6795', 'Growl'),
(@GoblinMask, @DruidMask, '26996', 'Maul'),
(@GoblinMask, @DruidMask, '18960', 'Teleport: Moonglade'),
(@GoblinMask, @DruidMask, '9634', 'Dire Bear Form'),
(@GoblinMask, @DruidMask, '768', 'Cat Form'),
(@GoblinMask, @DruidMask, '783', 'Travel Form'),
(@GoblinMask, @DruidMask, '1066', 'Aquatic Form'),
(@GoblinMask, @DruidMask, '40120', 'Swift Flight Form'),
(@GoblinMask, @DruidMask, '5229', 'Enrage'),
(@GoblinMask, @DruidMask, '26980', 'Regrowth'),
(@GoblinMask, @DruidMask, '8983', 'Bash'),
(@GoblinMask, @DruidMask, '8946', 'Cure Poison'),
(@GoblinMask, @DruidMask, '26997', 'Swipe (Bear)'),
-- (@GoblinMask, @DruidMask, '26993', 'Faerie Fire'), -- Removed?
(@GoblinMask, @DruidMask, '18658', 'Hibernate'),
(@GoblinMask, @DruidMask, '27000', 'Claw'),
(@GoblinMask, @DruidMask, '9913', 'Prowl'),
(@GoblinMask, @DruidMask, '26994', 'Rebirth'),
(@GoblinMask, @DruidMask, '27008', 'Rip'),
(@GoblinMask, @DruidMask, '26986', 'Starfire'),
(@GoblinMask, @DruidMask, '27002', 'Shred'),
(@GoblinMask, @DruidMask, '26995', 'Soothe Animal'),
(@GoblinMask, @DruidMask, '27003', 'Rake'),
(@GoblinMask, @DruidMask, '2782', 'Remove Curse'),
(@GoblinMask, @DruidMask, '9846', 'Tigers Fury'),
(@GoblinMask, @DruidMask, '2893', 'Abolish Poison'),
(@GoblinMask, @DruidMask, '33357', 'Dash'),
(@GoblinMask, @DruidMask, '5209', 'Challenging Roar'),
(@GoblinMask, @DruidMask, '27004', 'Cower'),
(@GoblinMask, @DruidMask, '26983', 'Tranquility'),
(@GoblinMask, @DruidMask, '24248', 'Ferocious Bite'),
(@GoblinMask, @DruidMask, '27005', 'Ravage'),
(@GoblinMask, @DruidMask, '5225', 'Track Humanoids'),
-- (@GoblinMask, @DruidMask, '26999', 'Frenzied Regeneration'), -- Removed?
(@GoblinMask, @DruidMask, '27012', 'Hurricane'),
(@GoblinMask, @DruidMask, '27006', 'Pounce'),
(@GoblinMask, @DruidMask, '29166', 'Innervate'),
(@GoblinMask, @DruidMask, '22812', 'Bark Skin'),
(@GoblinMask, @DruidMask, '26991', 'Gift of the Wild'),
(@GoblinMask, @DruidMask, '22570', 'Maim'),
(@GoblinMask, @DruidMask, '33763', 'Lifebloom'),
(@GoblinMask, @DruidMask, '33745', 'Lacerate'),
(@GoblinMask, @DruidMask, '33786', 'Cyclone'),
(@GoblinMask, @DruidMask, '20719', 'Feline Grace');
