-- charhairgeosets: 62 inserts, 0 updates, 6 deletes

-- New entries
SET @CharHairGeosetsID = (SELECT COALESCE(MAX(id), 0) FROM `dbc`.`charhairgeosets`);

-- DELETE FROM `charhairgeosets` WHERE `id` BETWEEN 500 AND 534; -- 535 is absent for some reason
-- DELETE FROM `charhairgeosets` WHERE `id` BETWEEN 536 AND 562; -- probably not important, but just in case
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 0, 19, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 1, 2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 0, 2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 1, 3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 2, 3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 3, 4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 4, 5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 2, 4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 3, 5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 4, 6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 5, 7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 6, 8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 7, 9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 8, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 9, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 10, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 11, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 12, 14, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 13, 15, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 14, 16, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 15, 17, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Female, 16, 18, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 5, 6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 6, 7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 7, 8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 9, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 10, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 8, 9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 11, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 12, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 13, 14, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 14, 15, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 15, 16, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 16, 17, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Goblin, @Male, 17, 18, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 2, 4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 0, 2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 1, 3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 3, 5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 6, 8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 4, 6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 5, 7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 9, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 7, 9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 8, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 10, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Male, 11, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 1, 2, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 2, 3, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 3, 4, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 4, 5, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 5, 6, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 6, 7, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 7, 8, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 8, 9, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 9, 10, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 10, 11, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 11, 12, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 12, 13, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 13, 14, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 14, 15, 0),
(@CharHairGeosetsID := @CharHairGeosetsID +1, @Worgen, @Female, 15, 16, 0);
