-- chrclasses: 0 inserts, 10 updates, 0 deletes

-- Changed values
UPDATE `chrclasses` SET `name_kokr` = '전사', `name_frfr` = 'Guerrier', `name_dede` = 'Krieger', `name_zhcn` = '战士', `name_zhtw` = '戰士', `name_eses` = 'Guerrero', `name_esmx` = 'Guerrero', `name_ruru` = 'Воин', `name_female_frfr` = 'Guerrière', `name_female_dede` = 'Kriegerin', `name_female_eses` = 'Guerrera', `name_female_esmx` = 'Guerrera', `name_male_frfr` = 'Guerrier', `name_male_dede` = 'Krieger', `name_male_eses` = 'Guerrero', `name_male_esmx` = 'Guerrero', `name_male_ruru` = 'Воин' WHERE `id` = 1;
UPDATE `chrclasses` SET `name_kokr` = '성기사', `name_frfr` = 'Paladin', `name_dede` = 'Paladin', `name_zhcn` = '圣骑士', `name_zhtw` = '聖騎士', `name_eses` = 'Paladín', `name_esmx` = 'Paladín', `name_ruru` = 'Паладин', `name_female_eses` = 'Paladín', `name_female_esmx` = 'Paladín', `name_male_frfr` = 'Paladin', `name_male_dede` = 'Paladin', `name_male_eses` = 'Paladín', `name_male_esmx` = 'Paladín', `name_male_ruru` = 'Паладин' WHERE `id` = 2;
UPDATE `chrclasses` SET `name_kokr` = '사냥꾼', `name_frfr` = 'Chasseur', `name_dede` = 'Jäger', `name_zhcn` = '猎人', `name_zhtw` = '獵人', `name_eses` = 'Cazador', `name_esmx` = 'Cazador', `name_ruru` = 'Охотник', `name_female_frfr` = 'Chasseresse', `name_female_dede` = 'Jägerin', `name_female_eses` = 'Cazadora', `name_female_esmx` = 'Cazadora', `name_female_ruru` = 'Охотница', `name_male_frfr` = 'Chasseur', `name_male_dede` = 'Jäger', `name_male_eses` = 'Cazador', `name_male_esmx` = 'Cazador', `name_male_ruru` = 'Охотник' WHERE `id` = 3;
UPDATE `chrclasses` SET `name_kokr` = '도적', `name_frfr` = 'Voleur', `name_dede` = 'Schurke', `name_zhcn` = '潜行者', `name_zhtw` = '盜賊', `name_eses` = 'Pícaro', `name_esmx` = 'Pícaro', `name_ruru` = 'Разбойник', `name_female_frfr` = 'Voleuse', `name_female_dede` = 'Schurkin', `name_female_eses` = 'Pícara', `name_female_esmx` = 'Pícara', `name_female_ruru` = 'Разбойница', `name_male_frfr` = 'Voleur', `name_male_dede` = 'Schurke', `name_male_eses` = 'Pícaro', `name_male_esmx` = 'Pícaro', `name_male_ruru` = 'Разбойник' WHERE `id` = 4;
UPDATE `chrclasses` SET `name_kokr` = '사제', `name_frfr` = 'Prêtre', `name_dede` = 'Priester', `name_zhcn` = '牧师', `name_zhtw` = '牧師', `name_eses` = 'Sacerdote', `name_esmx` = 'Sacerdote', `name_ruru` = 'Жрец', `name_female_frfr` = 'Prêtresse', `name_female_dede` = 'Priesterin', `name_female_eses` = 'Sacerdotisa', `name_female_esmx` = 'Sacerdotisa', `name_female_ruru` = 'Жрица', `name_male_frfr` = 'Prêtre', `name_male_dede` = 'Priester', `name_male_eses` = 'Sacerdote', `name_male_esmx` = 'Sacerdote', `name_male_ruru` = 'Жрец' WHERE `id` = 5;
UPDATE `chrclasses` SET `name_kokr` = '죽음의 기사', `name_frfr` = 'Chevalier de la mort', `name_dede` = 'Todesritter', `name_zhcn` = '死亡骑士', `name_zhtw` = '死亡騎士', `name_eses` = 'Caballero de la Muerte', `name_esmx` = 'Caballero de la Muerte', `name_ruru` = 'Рыцарь смерти', `name_female_eses` = 'Caballero de la Muerte', `name_female_esmx` = 'Caballero de la Muerte', `name_male_frfr` = 'Chevalier de la mort', `name_male_dede` = 'Todesritter', `name_male_eses` = 'Caballero de la Muerte', `name_male_esmx` = 'Caballero de la Muerte', `name_male_ruru` = 'Рыцарь смерти' WHERE `id` = 6;
UPDATE `chrclasses` SET `name_kokr` = '주술사', `name_frfr` = 'Chaman', `name_dede` = 'Schamane', `name_zhcn` = '萨满祭司', `name_zhtw` = '薩滿', `name_eses` = 'Chamán', `name_esmx` = 'Chamán', `name_ruru` = 'Шаман', `name_female_frfr` = 'Chamane', `name_female_dede` = 'Schamanin', `name_female_eses` = 'Chamán', `name_female_esmx` = 'Chamán', `name_female_ruru` = 'Шаманка', `name_male_frfr` = 'Chaman', `name_male_dede` = 'Schamane', `name_male_eses` = 'Chamán', `name_male_esmx` = 'Chamán', `name_male_ruru` = 'Шаман' WHERE `id` = 7;
UPDATE `chrclasses` SET `name_kokr` = '마법사', `name_frfr` = 'Mage', `name_dede` = 'Magier', `name_zhcn` = '法师', `name_zhtw` = '法師', `name_eses` = 'Mago', `name_esmx` = 'Mago', `name_ruru` = 'Маг', `name_female_frfr` = 'Mage', `name_female_dede` = 'Magierin', `name_female_eses` = 'Maga', `name_female_esmx` = 'Maga', `name_male_frfr` = 'Mage', `name_male_dede` = 'Magier', `name_male_eses` = 'Mago', `name_male_esmx` = 'Mago', `name_male_ruru` = 'Маг' WHERE `id` = 8;
UPDATE `chrclasses` SET `name_kokr` = '흑마법사', `name_frfr` = 'Démoniste', `name_dede` = 'Hexenmeister', `name_zhcn` = '术士', `name_zhtw` = '術士', `name_eses` = 'Brujo', `name_esmx` = 'Brujo', `name_ruru` = 'Чернокнижник', `name_female_frfr` = 'Démoniste', `name_female_dede` = 'Hexenmeisterin', `name_female_eses` = 'Bruja', `name_female_esmx` = 'Bruja', `name_female_ruru` = 'Чернокнижница', `name_male_frfr` = 'Démoniste', `name_male_dede` = 'Hexenmeister', `name_male_eses` = 'Brujo', `name_male_esmx` = 'Brujo', `name_male_ruru` = 'Чернокнижник' WHERE `id` = 9;
UPDATE `chrclasses` SET `name_kokr` = '드루이드', `name_frfr` = 'Druide', `name_dede` = 'Druide', `name_zhcn` = '德鲁伊', `name_zhtw` = '德魯伊', `name_eses` = 'Druida', `name_esmx` = 'Druida', `name_ruru` = 'Друид', `name_female_frfr` = 'Druidesse', `name_female_dede` = 'Druidin', `name_female_eses` = 'Druida', `name_female_esmx` = 'Druida', `name_male_frfr` = 'Druide', `name_male_dede` = 'Druide', `name_male_eses` = 'Druida', `name_male_esmx` = 'Druida', `name_male_ruru` = 'Друид' WHERE `id` = 11;
