-- battlemasterlist: 0 inserts, 13 updates, 0 deletes

-- Changed values
UPDATE `battlemasterlist` SET `name_kokr` = '알터랙 계곡', `name_frfr` = 'Vallée d\'Alterac', `name_dede` = 'Alteractal', `name_zhcn` = '奥特兰克山谷', `name_zhtw` = '奧特蘭克山谷', `name_eses` = 'Valle de Alterac', `name_esmx` = 'Valle de Alterac', `name_ruru` = 'Альтеракская долина' WHERE `id` = 1;
UPDATE `battlemasterlist` SET `name_kokr` = '전쟁노래 협곡', `name_frfr` = 'Goulet des Chanteguerres', `name_dede` = 'Kriegshymnenschlucht', `name_zhcn` = '战歌峡谷', `name_zhtw` = '戰歌峽谷', `name_eses` = 'Garganta Grito de Guerra', `name_esmx` = 'Garganta Grito de Guerra', `name_ruru` = 'Ущелье Песни Войны' WHERE `id` = 2;
UPDATE `battlemasterlist` SET `name_kokr` = '아라시 분지', `name_frfr` = 'Bassin d\'Arathi', `name_dede` = 'Arathibecken', `name_zhcn` = '阿拉希盆地', `name_zhtw` = '阿拉希盆地', `name_eses` = 'Cuenca de Arathi', `name_esmx` = 'Cuenca de Arathi', `name_ruru` = 'Низина Арати' WHERE `id` = 3;
UPDATE `battlemasterlist` SET `name_kokr` = '나그란드 투기장', `name_frfr` = 'Arène de Nagrand', `name_dede` = 'Arena von Nagrand', `name_zhcn` = '纳格兰竞技场', `name_zhtw` = '納葛蘭競技場', `name_eses` = 'Arena de Nagrand', `name_esmx` = 'Arena de Nagrand', `name_ruru` = 'Арена Награнда' WHERE `id` = 4;
UPDATE `battlemasterlist` SET `name_kokr` = '칼날 산맥 투기장', `name_frfr` = 'Arène des Tranchantes', `name_dede` = 'Arena des Schergrats', `name_zhcn` = '刀锋竞技场', `name_zhtw` = '劍刃競技場', `name_eses` = 'Arena Filospada', `name_esmx` = 'Arena Filospada', `name_ruru` = 'Арена Острогорья' WHERE `id` = 5;
UPDATE `battlemasterlist` SET `name_kokr` = '모든 투기장', `name_frfr` = 'Toutes les arènes', `name_dede` = 'Alle Arenen', `name_zhcn` = '所有竞技场', `name_zhtw` = '所有競技場', `name_eses` = 'Todas las arenas', `name_esmx` = 'Todas las arenas', `name_ruru` = 'Все арены' WHERE `id` = 6;
UPDATE `battlemasterlist` SET `name_kokr` = '폭풍의 눈', `name_frfr` = 'L\'Œil du cyclone', `name_dede` = 'Auge des Sturms', `name_zhcn` = '风暴之眼', `name_zhtw` = '暴風之眼', `name_eses` = 'Ojo de la Tormenta', `name_esmx` = 'Ojo de la Tormenta', `name_ruru` = 'Око Бури' WHERE `id` = 7;
UPDATE `battlemasterlist` SET `name_kokr` = '로데론의 폐허', `name_frfr` = 'Ruines de Lordaeron', `name_dede` = 'Ruinen von Lordaeron', `name_zhcn` = '洛丹伦废墟', `name_zhtw` = '羅德隆廢墟', `name_eses` = 'Ruinas de Lordaeron', `name_esmx` = 'Ruinas de Lordaeron', `name_ruru` = 'Руины Лордерона' WHERE `id` = 8;
UPDATE `battlemasterlist` SET `name_kokr` = '고대의 해안', `name_frfr` = 'Rivage des Anciens', `name_dede` = 'Strand der Uralten', `name_zhcn` = '远古海滩', `name_zhtw` = '遠祖灘頭', `name_eses` = 'Playa de los Ancestros', `name_esmx` = 'Playa de los Ancestros', `name_ruru` = 'Берег Древних' WHERE `id` = 9;
UPDATE `battlemasterlist` SET `name_kokr` = '달라란 투기장', `name_frfr` = 'Egouts de Dalaran', `name_dede` = 'Abwasserkanäle von Dalaran', `name_zhcn` = '达拉然下水道', `name_zhtw` = '達拉然下水道', `name_eses` = 'Cloacas de Dalaran', `name_esmx` = 'Cloacas de Dalaran', `name_ruru` = 'Стоки Даларана' WHERE `id` = 10;
UPDATE `battlemasterlist` SET `name_kokr` = '용맹의 투기장', `name_frfr` = 'L\'arène des valeureux', `name_dede` = 'Der Ring der Ehre', `name_zhcn` = '勇气竞技场', `name_zhtw` = '勇武之環', `name_eses` = 'El Círculo del Valor', `name_esmx` = 'El Círculo del Valor', `name_ruru` = 'Арена Доблести' WHERE `id` = 11;
UPDATE `battlemasterlist` SET `name_kokr` = '정복의 섬', `name_frfr` = 'Île des Conquérants', `name_dede` = 'Insel der Eroberung', `name_zhcn` = '征服之岛', `name_zhtw` = '征服之島', `name_eses` = 'Isla de la Conquista', `name_esmx` = 'Isla de la Conquista', `name_ruru` = 'Остров Завоеваний' WHERE `id` = 30;
UPDATE `battlemasterlist` SET `name_kokr` = '무작위 전장', `name_frfr` = 'Champ de bataille aléatoire', `name_dede` = 'Zufälliges Schlachtfeld', `name_zhcn` = '随机战场', `name_zhtw` = '隨機戰場', `name_eses` = 'Campo de batalla aleatorio', `name_esmx` = 'Campo de batalla aleatorio', `name_ruru` = 'Случайное поле боя' WHERE `id` = 32;
