-- auctionhouse: 0 inserts, 7 updates, 0 deletes

-- Changed values
UPDATE `auctionhouse` SET `name_kokr` = '스톰윈드 경매장', `name_frfr` = 'Hôtel des ventes de Hurlevent', `name_dede` = 'Auktionshaus von Sturmwind', `name_zhcn` = '暴风城拍卖行', `name_zhtw` = '暴風城拍賣場', `name_eses` = 'Casa de subastas: Ventormenta', `name_esmx` = 'Casa de subastas: Ventormenta', `name_ruru` = 'Аукционный дом Штормграда' WHERE `id` = 1;
UPDATE `auctionhouse` SET `name_kokr` = '얼라이언스 경매장', `name_frfr` = 'Hôtel des ventes de l\'Alliance', `name_dede` = 'Auktionshaus der Allianz', `name_zhcn` = '联盟拍卖行', `name_zhtw` = '聯盟拍賣場', `name_eses` = 'Casa de subastas: Alianza', `name_esmx` = 'Casa de subastas: Alianza', `name_ruru` = 'Аукционный дом Альянса' WHERE `id` = 2;
UPDATE `auctionhouse` SET `name_kokr` = '다르나서스 경매장', `name_frfr` = 'Hôtel des ventes de Darnassus', `name_dede` = 'Auktionshaus von Darnassus', `name_zhcn` = '达纳苏斯拍卖行', `name_zhtw` = '達納蘇斯拍賣場', `name_eses` = 'Casa de subastas: Darnassus', `name_esmx` = 'Casa de subastas: Darnassus', `name_ruru` = 'Аукционный дом Дарнаса' WHERE `id` = 3;
UPDATE `auctionhouse` SET `name_kokr` = '언더시티 경매장', `name_frfr` = 'Hôtel des ventes de Fossoyeuse', `name_dede` = 'Auktionshaus von Unterstadt', `name_zhcn` = '幽暗城拍卖行', `name_zhtw` = '幽暗城拍賣場', `name_eses` = 'Casa de subastas: Entrañas', `name_esmx` = 'Casa de subastas: Entrañas', `name_ruru` = 'Аукционный дом Подгорода' WHERE `id` = 4;
UPDATE `auctionhouse` SET `name_kokr` = '썬더 블러프 경매장', `name_frfr` = 'Hôtel des ventes des Pitons du Tonnerre', `name_dede` = 'Auktionshaus von Donnerfels', `name_zhcn` = '雷霆崖拍卖行', `name_zhtw` = '雷霆崖拍賣場', `name_eses` = 'Casa de subastas: Cima del Trueno', `name_esmx` = 'Casa de subastas: Cima del Trueno', `name_ruru` = 'Аукционный дом Громового Утеса' WHERE `id` = 5;
UPDATE `auctionhouse` SET `name_kokr` = '호드 경매장', `name_frfr` = 'Hôtel des ventes de la Horde', `name_dede` = 'Auktionshaus der Horde', `name_zhcn` = '部落拍卖行', `name_zhtw` = '部落拍賣場', `name_eses` = 'Casa de subastas: Horda', `name_esmx` = 'Casa de subastas: Horda', `name_ruru` = 'Аукционный дом Орды' WHERE `id` = 6;
UPDATE `auctionhouse` SET `name_kokr` = '검은바다 경매장', `name_frfr` = 'Hôtel des ventes des Flots noirs', `name_dede` = 'Auktionshaus der Schwarzmeerräuber', `name_zhcn` = '黑水拍卖行', `name_zhtw` = '黑水灣拍賣場', `name_eses` = 'Casa de subastas: Aguasnegras', `name_esmx` = 'Casa de subastas: Aguasnegras', `name_ruru` = 'Аукционный дом Черноводья' WHERE `id` = 7;
