-- spellmechanic: 0 inserts, 31 updates, 0 deletes

-- Changed values
UPDATE `spellmechanic` SET `name_kokr` = '지배', `name_frfr` = 'charmé(e)', `name_dede` = 'Ihr bezaubert seid.', `name_zhcn` = '被魅惑', `name_zhtw` = '魅惑', `name_eses` = 'embelesado', `name_esmx` = 'embelesado', `name_ruru` = 'подчинение' WHERE `id` = 1;
UPDATE `spellmechanic` SET `name_kokr` = '방향 감각 상실', `name_frfr` = 'désorienté(e)', `name_dede` = 'Ihr desorientiert seid.', `name_zhcn` = '迷惑', `name_zhtw` = '困惑', `name_eses` = 'desorientado', `name_esmx` = 'desorientado', `name_ruru` = 'дезориентация' WHERE `id` = 2;
UPDATE `spellmechanic` SET `name_kokr` = '무장 해제', `name_frfr` = 'désarmé(e)', `name_dede` = 'Ihr entwaffnet seid.', `name_zhcn` = '被缴械', `name_zhtw` = '繳械', `name_eses` = 'desarmado', `name_esmx` = 'desarmado', `name_ruru` = 'без оружия' WHERE `id` = 3;
UPDATE `spellmechanic` SET `name_kokr` = '혼란', `name_frfr` = 'distrait(e)', `name_dede` = 'Ihr abgelenkt seid.', `name_zhcn` = '被吸引', `name_zhtw` = '轉移', `name_eses` = 'distraído', `name_esmx` = 'distraído', `name_ruru` = 'отвлечение' WHERE `id` = 4;
UPDATE `spellmechanic` SET `name_kokr` = '도망', `name_frfr` = 'en fuite', `name_dede` = 'Ihr flüchtet.', `name_zhcn` = '逃跑', `name_zhtw` = '逃跑', `name_eses` = 'huyendo', `name_esmx` = 'huyendo', `name_ruru` = 'паника' WHERE `id` = 5;
UPDATE `spellmechanic` SET `name_kokr` = '붙잡힘', `name_frfr` = 'maladroit(e)', `name_dede` = 'Ergriffen', `name_zhcn` = '笨拙', `name_zhtw` = '控制', `name_eses` = 'agarrado', `name_esmx` = 'agarrado', `name_ruru` = 'неуклюжесть' WHERE `id` = 6;
UPDATE `spellmechanic` SET `name_kokr` = '이동 불가', `name_frfr` = 'immobilisé(e)', `name_dede` = 'Ihr unbeweglich seid.', `name_zhcn` = '被定身', `name_zhtw` = '定身', `name_eses` = 'enraizado', `name_esmx` = 'enraizado', `name_ruru` = 'оплетение' WHERE `id` = 7;
UPDATE `spellmechanic` SET `name_kokr` = '감속', `name_frfr` = 'ralenti(e)', `name_dede` = 'Ihr verlangsamt wurdet.', `name_zhcn` = '平静', `name_zhtw` = '緩速', `name_eses` = 'pacificado', `name_esmx` = 'pacificado', `name_ruru` = 'покой' WHERE `id` = 8;
UPDATE `spellmechanic` SET `name_kokr` = '침묵', `name_frfr` = 'réduit(e) au silence', `name_dede` = 'Ihr zum Schweigen gebracht wurdet.', `name_zhcn` = '沉默', `name_zhtw` = '沉默', `name_eses` = 'silenciado', `name_esmx` = 'silenciado', `name_ruru` = 'немота' WHERE `id` = 9;
UPDATE `spellmechanic` SET `name_kokr` = '수면', `name_frfr` = 'endormi(e)', `name_dede` = 'Ihr schlaft.', `name_zhcn` = '沉睡', `name_zhtw` = '沉睡', `name_eses` = 'dormido', `name_esmx` = 'dormido', `name_ruru` = 'сон' WHERE `id` = 10;
UPDATE `spellmechanic` SET `name_kokr` = '감속', `name_frfr` = 'piégé(e)', `name_dede` = 'Verlangsamt', `name_zhcn` = '诱捕', `name_zhtw` = '緩速', `name_eses` = 'frenado', `name_esmx` = 'frenado', `name_ruru` = 'сковывание' WHERE `id` = 11;
UPDATE `spellmechanic` SET `name_kokr` = '기절', `name_frfr` = 'étourdi(e)', `name_dede` = 'Ihr betäubt seid.', `name_zhcn` = '昏迷', `name_zhtw` = '昏迷', `name_eses` = 'aturdido', `name_esmx` = 'aturdido', `name_ruru` = 'оглушение' WHERE `id` = 12;
UPDATE `spellmechanic` SET `name_kokr` = '얼어 붙음', `name_frfr` = 'gelé(e)', `name_dede` = 'Ihr eingefroren seid.', `name_zhcn` = '冻结', `name_zhtw` = '冰凍', `name_eses` = 'congelado', `name_esmx` = 'congelado', `name_ruru` = 'заморозка' WHERE `id` = 13;
UPDATE `spellmechanic` SET `name_kokr` = '행동 불가', `name_frfr` = 'stupéfié(e)', `name_dede` = 'Ihr handlungsunfähig seid.', `name_zhcn` = '瘫痪', `name_zhtw` = '癱瘓', `name_eses` = 'incapacitado', `name_esmx` = 'incapacitado', `name_ruru` = 'паралич' WHERE `id` = 14;
UPDATE `spellmechanic` SET `name_kokr` = '출혈', `name_frfr` = 'sanguinolent(e)', `name_dede` = 'Ihr blutet.', `name_zhcn` = '流血', `name_zhtw` = '流血', `name_eses` = 'sangrando', `name_esmx` = 'sangrando', `name_ruru` = 'кровотечение' WHERE `id` = 15;
UPDATE `spellmechanic` SET `name_kokr` = '치유', `name_frfr` = 'en soin', `name_dede` = 'Ihr heilt.', `name_zhcn` = '治疗', `name_zhtw` = '治療', `name_eses` = 'sanando', `name_esmx` = 'sanando', `name_ruru` = 'лечение' WHERE `id` = 16;
UPDATE `spellmechanic` SET `name_kokr` = '변이', `name_frfr` = 'métamorphosé(e)', `name_dede` = 'Ihr verwandelt seid.', `name_zhcn` = '被变形', `name_zhtw` = '變形', `name_eses` = 'polimorfado', `name_esmx` = 'polimorfado', `name_ruru` = 'превращение' WHERE `id` = 17;
UPDATE `spellmechanic` SET `name_kokr` = '소멸', `name_frfr` = 'banni(e)', `name_dede` = 'Ihr gebannt seid.', `name_zhcn` = '被放逐', `name_zhtw` = '放逐', `name_eses` = 'desterrado', `name_esmx` = 'desterrado', `name_ruru` = 'изгнание' WHERE `id` = 18;
UPDATE `spellmechanic` SET `name_kokr` = '방패 막기', `name_frfr` = 'protégé(e)', `name_dede` = 'Ihr abgeschirmt seid.', `name_zhcn` = '被防护', `name_zhtw` = '防護', `name_eses` = 'protegido', `name_esmx` = 'protegido', `name_ruru` = 'защита' WHERE `id` = 19;
UPDATE `spellmechanic` SET `name_kokr` = '속박됨', `name_frfr` = 'entravé(e)', `name_dede` = 'Ihr gefesselt seid.', `name_zhcn` = '被禁锢', `name_zhtw` = '禁錮', `name_eses` = 'aprisionado', `name_esmx` = 'aprisionado', `name_ruru` = 'оковы' WHERE `id` = 20;
UPDATE `spellmechanic` SET `name_kokr` = '탈것에 탐', `name_frfr` = 'monté(e)', `name_dede` = 'Ihr reitet.', `name_zhcn` = '骑乘', `name_zhtw` = '騎乘', `name_eses` = 'montado', `name_esmx` = 'montado', `name_ruru` = 'верхом' WHERE `id` = 21;
UPDATE `spellmechanic` SET `name_kokr` = '감염됨', `name_frfr` = 'séduit(e)', `name_dede` = 'Infiziert', `name_zhcn` = '被诱惑', `name_zhtw` = '傳染', `name_eses` = 'infectado', `name_esmx` = 'infectado', `name_ruru` = 'заражение' WHERE `id` = 22;
UPDATE `spellmechanic` SET `name_kokr` = '퇴치당함', `name_frfr` = 'repoussé(e)', `name_dede` = 'Ihr vertrieben werdet.', `name_zhcn` = '转向', `name_zhtw` = '轉向', `name_eses` = 'girado', `name_esmx` = 'girado', `name_ruru` = 'обращение' WHERE `id` = 23;
UPDATE `spellmechanic` SET `name_kokr` = '극심한 공포', `name_frfr` = 'horrifié(e)', `name_dede` = 'Ihr von Entsetzen erfüllt seid.', `name_zhcn` = '惊骇', `name_zhtw` = '恐懼', `name_eses` = 'horrorizado', `name_esmx` = 'horrorizado', `name_ruru` = 'ужас' WHERE `id` = 24;
UPDATE `spellmechanic` SET `name_kokr` = '무적', `name_frfr` = 'invulnérable', `name_dede` = 'Ihr unverwundbar seid.', `name_zhcn` = '无敌', `name_zhtw` = '免傷', `name_eses` = 'invulnerable', `name_esmx` = 'invulnerable', `name_ruru` = 'неуязвимость' WHERE `id` = 25;
UPDATE `spellmechanic` SET `name_kokr` = '방해 받음', `name_frfr` = 'interrompu(e)', `name_dede` = 'Ihr unterbrochen wurdet.', `name_zhcn` = '被打断', `name_zhtw` = '中斷', `name_eses` = 'interrumpido', `name_esmx` = 'interrumpido', `name_ruru` = 'прерывание' WHERE `id` = 26;
UPDATE `spellmechanic` SET `name_kokr` = '멍해짐', `name_frfr` = 'hébété(e)', `name_dede` = 'Ihr benommen seid.', `name_zhcn` = '眩晕', `name_zhtw` = '暈眩', `name_eses` = 'atontado', `name_esmx` = 'atontado', `name_ruru` = 'головокружение' WHERE `id` = 27;
UPDATE `spellmechanic` SET `name_kokr` = '발견', `name_frfr` = 'découverte', `name_dede` = 'Ihr eine Entdeckung macht.', `name_zhcn` = '被发现', `name_zhtw` = '發覺', `name_eses` = 'descubriendo', `name_esmx` = 'descubriendo', `name_ruru` = 'открытие' WHERE `id` = 28;
UPDATE `spellmechanic` SET `name_kokr` = '무적', `name_frfr` = 'invulnérable', `name_dede` = 'Ihr unverwundbar seid.', `name_zhcn` = '无敌', `name_zhtw` = '免傷', `name_eses` = 'invulnerable', `name_esmx` = 'invulnerable', `name_ruru` = 'неуязвимость' WHERE `id` = 29;
UPDATE `spellmechanic` SET `name_kokr` = '의식 불명', `name_frfr` = 'assommé(e)', `name_dede` = 'Ihr von einer Kopfnuss betäubt seid.', `name_zhcn` = '被闷棍', `name_zhtw` = '悶棍', `name_eses` = 'aporreado', `name_esmx` = 'aporreado', `name_ruru` = 'ошеломление' WHERE `id` = 30;
UPDATE `spellmechanic` SET `name_kokr` = '광포해짐', `name_frfr` = 'enragé(e)', `name_dede` = 'Wütend', `name_zhcn` = '激怒', `name_zhtw` = '激怒', `name_eses` = 'iracundo', `name_esmx` = 'iracundo', `name_ruru` = 'исступление' WHERE `id` = 31;
