-- spellshapeshiftform: 0 inserts, 30 updates, 0 deletes

-- Changed values
UPDATE `spellshapeshiftform` SET `name_kokr` = '표범 변신', `name_frfr` = 'Forme de félin', `name_dede` = 'Katzengestalt', `name_zhcn` = '猎豹形态', `name_zhtw` = '獵豹形態', `name_eses` = 'Forma felina', `name_esmx` = 'Forma felina', `name_ruru` = 'Облик кошки' WHERE `id` = 1;
UPDATE `spellshapeshiftform` SET `name_kokr` = '생명의 나무 변신', `name_frfr` = 'Forme d\'arbre de vie', `name_dede` = 'Baum des Lebens', `name_zhcn` = '生命之树形态', `name_zhtw` = '樹形', `name_eses` = 'Forma de árbol de vida', `name_esmx` = 'Forma de árbol de vida', `name_ruru` = 'Облик Древа жизни' WHERE `id` = 2;
UPDATE `spellshapeshiftform` SET `name_kokr` = '치타 변신', `name_frfr` = 'Forme de voyage', `name_dede` = 'Reisegestalt', `name_zhcn` = '旅行形态', `name_zhtw` = '旅行形態', `name_eses` = 'Forma de viaje', `name_esmx` = 'Forma de viaje', `name_ruru` = 'Походный облик' WHERE `id` = 3;
UPDATE `spellshapeshiftform` SET `name_kokr` = '바다표범 변신', `name_frfr` = 'Forme aquatique', `name_dede` = 'Wassergestalt', `name_zhcn` = '水生形态', `name_zhtw` = '水棲形態', `name_eses` = 'Forma acuática', `name_esmx` = 'Forma acuática', `name_ruru` = 'Водный облик' WHERE `id` = 4;
UPDATE `spellshapeshiftform` SET `name_kokr` = '곰 변신', `name_frfr` = 'Forme d’ours', `name_dede` = 'Bärengestalt', `name_zhcn` = '熊形态', `name_zhtw` = '熊形態', `name_eses` = 'Forma de oso', `name_esmx` = 'Forma de oso', `name_ruru` = 'Облик медведя' WHERE `id` = 5;
UPDATE `spellshapeshiftform` SET `name_kokr` = '동물', `name_frfr` = 'Ambiant', `name_dede` = 'Umgebung', `name_zhcn` = '小动物', `name_zhtw` = '小動物', `name_eses` = 'Ambiente', `name_esmx` = 'Ambiente', `name_ruru` = 'Фауна' WHERE `id` = 6;
UPDATE `spellshapeshiftform` SET `name_kokr` = '구울', `name_frfr` = 'Goule', `name_dede` = 'Ghul', `name_zhcn` = '食尸鬼', `name_zhtw` = '食屍鬼', `name_eses` = 'Necrófago', `name_esmx` = 'Necrófago', `name_ruru` = 'Вурдалак' WHERE `id` = 7;
UPDATE `spellshapeshiftform` SET `name_kokr` = '광포한 곰 변신', `name_frfr` = 'Forme d’ours redoutable', `name_dede` = 'Terrorbärengestalt', `name_zhcn` = '巨熊形态', `name_zhtw` = '巨熊形態', `name_eses` = 'Forma de oso temible', `name_esmx` = 'Forma de oso temible', `name_ruru` = 'Облик лютого медведя' WHERE `id` = 8;
UPDATE `spellshapeshiftform` SET `name_kokr` = '스티브 구울', `name_frfr` = 'Goule de Steve', `name_dede` = 'Steves Ghul', `name_zhcn` = '斯蒂文的食尸鬼', `name_zhtw` = '史蒂芬的食屍鬼', `name_eses` = 'Steve\'s Ghoul', `name_esmx` = 'Steve\'s Ghoul', `name_ruru` = 'Вурдалак Стива' WHERE `id` = 9;
UPDATE `spellshapeshiftform` SET `name_kokr` = '타론자 해골', `name_frfr` = 'Squelette de Tharon\'ja', `name_dede` = 'Skelett von Tharon\'ja', `name_zhcn` = '萨隆亚的骷髅', `name_zhtw` = '薩隆杰骷髏', `name_eses` = 'Esqueleto Tharon\'ja', `name_esmx` = 'Esqueleto Tharon\'ja', `name_ruru` = 'Скелет Тарон\'джа' WHERE `id` = 10;
UPDATE `spellshapeshiftform` SET `name_kokr` = '다크문 - 용기의 시험', `name_frfr` = 'Sombrelune - épreuve de force', `name_dede` = 'Dunkelmond-Test der Stärke', `name_zhcn` = 'Darkmoon - Test of Strength', `name_zhtw` = '暗月 - 力量試煉', `name_eses` = 'Luna Negra - Prueba de fuerza', `name_esmx` = 'Luna Negra - Prueba de fuerza', `name_ruru` = 'Ярмарка Новолуния - испытание силы' WHERE `id` = 11;
UPDATE `spellshapeshiftform` SET `name_kokr` = 'BLB 플레이어', `name_frfr` = 'Joueur BLB', `name_dede` = 'BLB Spieler', `name_zhcn` = 'BLB Player', `name_zhtw` = 'BLB玩家', `name_eses` = 'BLB Player', `name_esmx` = 'BLB Player', `name_ruru` = 'BLB Player' WHERE `id` = 12;
UPDATE `spellshapeshiftform` SET `name_kokr` = '어둠의 춤', `name_frfr` = 'Danse de l\'ombre', `name_dede` = 'Schattentanz', `name_zhcn` = '暗影之舞', `name_zhtw` = '暗影之舞', `name_eses` = 'Danza de las Sombras', `name_esmx` = 'Danza de las Sombras', `name_ruru` = 'Танец теней' WHERE `id` = 13;
UPDATE `spellshapeshiftform` SET `name_kokr` = '곰', `name_frfr` = 'Créature - Ours', `name_dede` = 'Kreatur - Bär', `name_zhcn` = 'Creature - Bear', `name_zhtw` = '生物 - 熊', `name_eses` = 'Criatura: oso', `name_esmx` = 'Criatura: oso', `name_ruru` = 'Существо: медведь' WHERE `id` = 14;
UPDATE `spellshapeshiftform` SET `name_kokr` = '살쾡이', `name_frfr` = 'Créature - Félin', `name_dede` = 'Kreatur - Katze', `name_zhcn` = 'Creature - Cat', `name_zhtw` = '生物 - 豹', `name_eses` = 'Criatura: felino', `name_esmx` = 'Criatura: felino', `name_ruru` = 'Существо: кошка' WHERE `id` = 15;
UPDATE `spellshapeshiftform` SET `name_kokr` = '늑대 정령', `name_frfr` = 'Loup fantôme', `name_dede` = 'Geisterwolf', `name_zhcn` = '幽魂之狼', `name_zhtw` = '鬼魂之狼', `name_eses` = 'Lobo fantasmal', `name_esmx` = 'Lobo fantasmal', `name_ruru` = 'Призрачный волк' WHERE `id` = 16;
UPDATE `spellshapeshiftform` SET `name_kokr` = '전투 태세', `name_frfr` = 'Posture de combat', `name_dede` = 'Kampfhaltung', `name_zhcn` = '战斗姿态', `name_zhtw` = '戰鬥姿態', `name_eses` = 'Actitud de batalla', `name_esmx` = 'Actitud de batalla', `name_ruru` = 'Боевая стойка' WHERE `id` = 17;
UPDATE `spellshapeshiftform` SET `name_kokr` = '방어 태세', `name_frfr` = 'Posture défensive', `name_dede` = 'Verteidigungshaltung', `name_zhcn` = '防御姿态', `name_zhtw` = '防禦姿態', `name_eses` = 'Actitud defensiva', `name_esmx` = 'Actitud defensiva', `name_ruru` = 'Оборонительная стойка' WHERE `id` = 18;
UPDATE `spellshapeshiftform` SET `name_kokr` = '광폭 태세', `name_frfr` = 'Posture berserker', `name_dede` = 'Berserkerhaltung', `name_zhcn` = '狂暴姿态', `name_zhtw` = '狂暴姿態', `name_eses` = 'Actitud rabiosa', `name_esmx` = 'Actitud rabiosa', `name_ruru` = 'Стойка берсерка' WHERE `id` = 19;
UPDATE `spellshapeshiftform` SET `name_kokr` = '시험용', `name_frfr` = 'Test', `name_dede` = 'Test', `name_zhcn` = '测试', `name_zhtw` = '測試', `name_eses` = 'Test', `name_esmx` = 'Test', `name_ruru` = 'Тест' WHERE `id` = 20;
UPDATE `spellshapeshiftform` SET `name_kokr` = '좀비', `name_frfr` = 'Zombie', `name_dede` = 'Zombie', `name_zhcn` = '僵尸', `name_zhtw` = '殭屍', `name_eses` = 'Zombi', `name_esmx` = 'Zombi', `name_ruru` = 'Зомби' WHERE `id` = 21;
UPDATE `spellshapeshiftform` SET `name_kokr` = '탈태', `name_frfr` = 'Métamorphose', `name_dede` = 'Metamorphose', `name_zhcn` = '恶魔变身', `name_zhtw` = '變形形態', `name_eses` = 'Metamorfosis', `name_esmx` = 'Metamorfosis', `name_ruru` = 'Метаморфоза' WHERE `id` = 22;
UPDATE `spellshapeshiftform` SET `name_kokr` = '언데드', `name_frfr` = 'Mort-vivant', `name_dede` = 'Untotes Wesen', `name_zhcn` = '亡灵', `name_zhtw` = '不死生物', `name_eses` = 'No-muerto', `name_esmx` = 'No-muerto', `name_ruru` = 'Нежить' WHERE `id` = 25;
UPDATE `spellshapeshiftform` SET `name_kokr` = '광란', `name_frfr` = 'Frénésie', `name_dede` = 'Raserei', `name_zhcn` = '狂乱', `name_zhtw` = '狂亂', `name_eses` = 'Furia', `name_esmx` = 'Furia', `name_ruru` = 'Бешенство' WHERE `id` = 26;
UPDATE `spellshapeshiftform` SET `name_kokr` = '폭풍까마귀 변신 (영웅)', `name_frfr` = 'Forme de vol, épique', `name_dede` = 'Epische Fluggestalt', `name_zhcn` = '史诗飞行形态', `name_zhtw` = '飛行形態，史詩', `name_eses` = 'Forma voladora, épica', `name_esmx` = 'Forma voladora, épica', `name_ruru` = 'Облик стремительной птицы' WHERE `id` = 27;
UPDATE `spellshapeshiftform` SET `name_kokr` = '어둠의 형상', `name_frfr` = 'Forme d\'ombre', `name_dede` = 'Schattengestalt', `name_zhcn` = '暗影形态', `name_zhtw` = '暗影形態', `name_eses` = 'Forma de las Sombras', `name_esmx` = 'Forma de las Sombras', `name_ruru` = 'Облик Тьмы' WHERE `id` = 28;
UPDATE `spellshapeshiftform` SET `name_kokr` = '폭풍까마귀 변신', `name_frfr` = 'Forme de vol', `name_dede` = 'Fluggestalt', `name_zhcn` = '飞行形态', `name_zhtw` = '飛行形態', `name_eses` = 'Forma de vuelo', `name_esmx` = 'Forma de vuelo', `name_ruru` = 'Облик птицы' WHERE `id` = 29;
UPDATE `spellshapeshiftform` SET `name_kokr` = '은신', `name_frfr` = 'Camouflage', `name_dede` = 'Verstohlenheit', `name_zhcn` = '潜行', `name_zhtw` = '潛行', `name_eses` = 'Sigilo', `name_esmx` = 'Sigilo', `name_ruru` = 'Незаметность' WHERE `id` = 30;
UPDATE `spellshapeshiftform` SET `name_kokr` = '달빛야수 변신', `name_frfr` = 'Forme de sélénien', `name_dede` = 'Mondkingestalt', `name_zhcn` = '枭兽形态', `name_zhtw` = '梟獸形態', `name_eses` = 'Forma de lechúcico lunar', `name_esmx` = 'Forma de lechúcico lunar', `name_ruru` = 'Облик лунного совуха' WHERE `id` = 31;
UPDATE `spellshapeshiftform` SET `name_kokr` = '구원의 영혼', `name_frfr` = 'Esprit de rédemption', `name_dede` = 'Geist der Erlösung', `name_zhcn` = '救赎之魂', `name_zhtw` = '救贖之靈', `name_eses` = 'Espíritu redentor', `name_esmx` = 'Espíritu redentor', `name_ruru` = 'Дух воздаяния' WHERE `id` = 32;
