-- holidaynames: 0 inserts, 26 updates, 0 deletes

-- Changed values
UPDATE `holidaynames` SET `name_kokr` = '다크문 축제', `name_frfr` = 'Foire de Sombrelune', `name_dede` = 'Dunkelmond-Jahrmarkt', `name_zhcn` = '暗月马戏团', `name_zhtw` = '暗月馬戲團', `name_eses` = 'Feria de la Luna Negra', `name_esmx` = 'Feria de la Luna Negra', `name_ruru` = 'Ярмарка Новолуния' WHERE `id` = 1;
UPDATE `holidaynames` SET `name_kokr` = '새해맞이 축제', `name_frfr` = 'Fêtes des artifices', `name_dede` = 'Feuerwerksfestival', `name_zhcn` = '烟花庆典', `name_zhtw` = '煙火慶典', `name_eses` = 'Celebración de Fuegos artificiales', `name_esmx` = 'Celebración de Fuegos artificiales', `name_ruru` = 'Празднество фейерверков' WHERE `id` = 5;
UPDATE `holidaynames` SET `name_kokr` = '가시덤불 골짜기 낚시왕 선발대회', `name_frfr` = 'Concours de pêche de Strangleronce', `name_dede` = 'Anglerwettbewerb im Schlingendorntal', `name_zhcn` = '荆棘谷钓鱼大赛', `name_zhtw` = '荊棘谷釣魚大賽', `name_eses` = 'Gran espectáculo de pesca de Tuercespina', `name_esmx` = 'Gran espectáculo de pesca de Tuercespina', `name_ruru` = 'Рыбомания Тернистой долины' WHERE `id` = 6;
UPDATE `holidaynames` SET `name_kokr` = '가을 축제', `name_frfr` = 'Fête des Brasseurs', `name_dede` = 'Braufest', `name_zhcn` = '美酒节', `name_zhtw` = '啤酒節', `name_eses` = 'Fiesta de la cerveza', `name_esmx` = 'Fiesta de la cerveza', `name_ruru` = 'Хмельной фестиваль' WHERE `id` = 7;
UPDATE `holidaynames` SET `name_kokr` = '온누리에 사랑을', `name_frfr` = 'De l\'amour dans l\'air', `name_dede` = 'Liebe liegt in der Luft', `name_zhcn` = '情人节', `name_zhtw` = '愛就在身邊', `name_eses` = 'Amor en el aire', `name_esmx` = 'Amor en el aire', `name_ruru` = 'Любовная лихорадка' WHERE `id` = 9;
UPDATE `holidaynames` SET `name_kokr` = '한여름 불꽃축제', `name_frfr` = 'Fête du Feu du solstice d\'été', `name_dede` = 'Sonnenwendfest', `name_zhcn` = '仲夏火焰节', `name_zhtw` = '仲夏火焰節慶', `name_eses` = 'Festival de Fuego del Solsticio de Verano', `name_esmx` = 'Festival de Fuego del Solsticio de Verano', `name_ruru` = 'Огненный солнцеворот' WHERE `id` = 11;
UPDATE `holidaynames` SET `name_kokr` = '화려한 불꽃놀이', `name_frfr` = 'Féerie des artifices', `name_dede` = 'Feuerwerksspektakel', `name_zhcn` = '焰火表演', `name_zhtw` = '壯麗的煙火大會', `name_eses` = 'Espectáculo de fuegos artificiales', `name_esmx` = 'Espectáculo de fuegos artificiales', `name_ruru` = 'Праздник фейерверков' WHERE `id` = 12;
UPDATE `holidaynames` SET `name_kokr` = '어린이 주간', `name_frfr` = 'Semaine des enfants', `name_dede` = 'Kinderwoche', `name_zhcn` = '儿童周', `name_zhtw` = '兒童週', `name_eses` = 'Semana de los Niños', `name_esmx` = 'Semana de los Niños', `name_ruru` = 'Детская неделя' WHERE `id` = 13;
UPDATE `holidaynames` SET `name_kokr` = '겨울맞이 축제', `name_frfr` = 'Voile d\'hiver', `name_dede` = 'Winterhauchfest', `name_zhcn` = '冬幕节', `name_zhtw` = '冬幕節', `name_eses` = 'El festín del Festival de Invierno', `name_esmx` = 'El festín del Festival de Invierno', `name_ruru` = 'Зимний Покров' WHERE `id` = 14;
UPDATE `holidaynames` SET `name_kokr` = '귀족의 정원', `name_frfr` = 'Le Jardin des nobles', `name_dede` = 'Nobelgartenfest', `name_zhcn` = '复活节', `name_zhtw` = '貴族花園', `name_eses` = 'Jardín Noble', `name_esmx` = 'Jardín Noble', `name_ruru` = 'Сад чудес' WHERE `id` = 15;
UPDATE `holidaynames` SET `name_kokr` = '할로윈 축제', `name_frfr` = 'Sanssaint', `name_dede` = 'Schlotternächte', `name_zhcn` = '万圣节', `name_zhtw` = '萬鬼節', `name_eses` = 'Halloween', `name_esmx` = 'Halloween', `name_ruru` = 'Тыквовин' WHERE `id` = 16;
UPDATE `holidaynames` SET `name_kokr` = '추수절', `name_frfr` = 'Fête des moissons', `name_dede` = 'Erntedankfest', `name_zhcn` = '收获节', `name_zhtw` = '收穫節', `name_eses` = 'Festival de la Cosecha', `name_esmx` = 'Festival de la Cosecha', `name_ruru` = 'Неделя урожая' WHERE `id` = 17;
UPDATE `holidaynames` SET `name_kokr` = '달의 축제', `name_frfr` = 'Fête lunaire', `name_dede` = 'Mondfest', `name_zhcn` = '春节', `name_zhtw` = '新年慶典', `name_eses` = 'Festival Lunar', `name_esmx` = 'Festival Lunar', `name_ruru` = 'Лунный фестиваль' WHERE `id` = 18;
UPDATE `holidaynames` SET `name_kokr` = '가을 축제', `name_frfr` = 'Fête des Brasseurs', `name_dede` = 'Braufest', `name_zhcn` = '美酒节', `name_zhtw` = '啤酒節', `name_eses` = 'Fiesta de la cerveza', `name_esmx` = 'Fiesta de la cerveza', `name_ruru` = 'Хмельной фестиваль' WHERE `id` = 19;
UPDATE `holidaynames` SET `name_kokr` = '해적의 날', `name_frfr` = 'Jour des pirates', `name_dede` = 'Piratentag', `name_zhcn` = '海盗日', `name_zhtw` = '海賊日', `name_eses` = 'Día de los Piratas', `name_esmx` = 'Día de los Piratas', `name_ruru` = 'День пирата' WHERE `id` = 21;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 알터랙 계곡', `name_frfr` = 'Appel aux armes : vallée d\'Alterac', `name_dede` = 'Zu den Waffen: Alteractal', `name_zhcn` = '战斗的召唤：奥特兰克山谷', `name_zhtw` = '戰鬥的號角:奧特蘭克山谷', `name_eses` = 'Llamamiento a las armas: Valle de Alterac', `name_esmx` = 'Llamamiento a las armas: Valle de Alterac', `name_ruru` = 'К оружию! Альтеракская долина' WHERE `id` = 22;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 아라시 분지', `name_frfr` = 'Appel aux armes : bassin d\'Arathi', `name_dede` = 'Zu den Waffen: Arathibecken', `name_zhcn` = '战斗的召唤：阿拉希盆地', `name_zhtw` = '戰鬥的號角:阿拉希盆地', `name_eses` = 'Llamamiento a las armas: Cuenca de Arathi', `name_esmx` = 'Llamamiento a las armas: Cuenca de Arathi', `name_ruru` = 'К оружию! Низина Арати' WHERE `id` = 23;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 폭풍의 눈', `name_frfr` = 'Appel aux armes : Œil du cyclone', `name_dede` = 'Zu den Waffen: Auge des Sturms', `name_zhcn` = '战斗的召唤：风暴之眼', `name_zhtw` = '戰鬥的號角:暴風之眼', `name_eses` = 'Llamamiento a las armas: Ojo de la Tormenta', `name_esmx` = 'Llamamiento a las armas: Ojo de la Tormenta', `name_ruru` = 'К оружию! Око Бури' WHERE `id` = 24;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 전쟁노래 협곡', `name_frfr` = 'Appel aux armes : goulet des Chanteguerres', `name_dede` = 'Zu den Waffen: Kriegshymnenschlucht', `name_zhcn` = '战斗的召唤：战歌峡谷', `name_zhtw` = '戰鬥的號角:戰歌峽谷', `name_eses` = 'Llamamiento a las armas: Garganta Grito de Guerra', `name_esmx` = 'Llamamiento a las armas: Garganta Grito de Guerra', `name_ruru` = 'К оружию! Ущелье Песни Войны' WHERE `id` = 25;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 고대의 해안', `name_frfr` = 'Appel aux armes : rivage des Anciens', `name_dede` = 'Zu den Waffen: Strand der Uralten', `name_zhcn` = '战斗的召唤：远古海滩', `name_zhtw` = '戰鬥的號角:遠祖灘頭', `name_eses` = 'Llamamiento a las armas: Playa de los Ancestros', `name_esmx` = 'Llamamiento a las armas: Playa de los Ancestros', `name_ruru` = 'К оружию! Берег Древних' WHERE `id` = 41;
UPDATE `holidaynames` SET `name_kokr` = '리치 왕의 분노 시작', `name_frfr` = 'Lancement de Wrath of the Lich King', `name_dede` = 'Start von Wrath of the Lich King', `name_zhcn` = '巫妖王之怒上线', `name_zhtw` = '巫妖王之怒發行日', `name_eses` = 'Lanzamiento de Wrath of the Lich King', `name_esmx` = 'Lanzamiento de Wrath of the Lich King', `name_ruru` = 'Wrath of the Lich King' WHERE `id` = 61;
UPDATE `holidaynames` SET `name_kokr` = '망자의 날', `name_frfr` = 'Jour des morts', `name_dede` = 'Tag der Toten', `name_zhcn` = '悼念日', `name_zhtw` = '亡者節', `name_eses` = 'Festividad de los Muertos', `name_esmx` = 'Festividad de los Muertos', `name_ruru` = 'День мертвых' WHERE `id` = 81;
UPDATE `holidaynames` SET `name_kokr` = '순례자의 감사절', `name_frfr` = 'Les Bienfaits du pèlerin', `name_dede` = 'Pilgerfreudenfest', `name_zhcn` = '感恩节', `name_zhtw` = '旅人豐年祭', `name_eses` = 'Generosidad del Peregrino', `name_esmx` = 'Generosidad del Peregrino', `name_ruru` = 'Пиршество странников' WHERE `id` = 101;
UPDATE `holidaynames` SET `name_kokr` = '전장으로: 정복의 섬', `name_frfr` = 'Appel aux armes : île des Conquérants', `name_dede` = 'Zu den Waffen: Insel der Eroberung', `name_zhcn` = '战斗的召唤：征服之岛', `name_zhtw` = '戰鬥的號角:征服之島', `name_eses` = 'Llamamiento a las armas: Isla de la Conquista', `name_esmx` = 'Llamamiento a las armas: Isla de la Conquista', `name_ruru` = 'К оружию! Остров Завоеваний' WHERE `id` = 121;
UPDATE `holidaynames` SET `name_kokr` = '모호크 이벤트', `name_frfr` = 'Promotion Punk', `name_dede` = 'Nachtelfirokesen-Promotion', `name_zhcn` = '暗夜精灵莫霍克促销活动', `name_zhtw` = '怪頭活動', `name_eses` = 'Promoción mohicano', `name_esmx` = 'Promoción mohicano', `name_ruru` = 'Реклама ирокеза' WHERE `id` = 141;
UPDATE `holidaynames` SET `name_kokr` = '칼루아크 낚시 대회', `name_frfr` = 'Tournoi de pêche kalu\'ak', `name_dede` = 'Angelwettstreit der Kalu\'ak', `name_zhcn` = '卡鲁亚克钓鱼大赛', `name_zhtw` = '卡魯耶克釣魚大賽', `name_eses` = 'Competición de pesca Kalu\'ak', `name_esmx` = 'Competición de pesca Kalu\'ak', `name_ruru` = 'Калуакское рыбоборье' WHERE `id` = 161;
