-- lfgdungeongroup: 0 inserts, 10 updates, 0 deletes

-- Changed values
UPDATE `lfgdungeongroup` SET `name_kokr` = '오리지널 던전', `name_frfr` = 'Donjons classiques', `name_dede` = 'Dungeons (Classic)', `name_zhcn` = '经典地下城', `name_zhtw` = '艾澤拉斯地城', `name_eses` = 'Mazmorra clásica', `name_esmx` = 'Mazmorra clásica', `name_ruru` = 'Классические подземелья' WHERE `id` = 1;
UPDATE `lfgdungeongroup` SET `name_kokr` = '불타는 성전 (일반)', `name_frfr` = 'The Burning Crusade - mode normal', `name_dede` = 'Normale Dungeons (Burning Crusade)', `name_zhcn` = '燃烧的远征（普通）', `name_zhtw` = '燃燒的遠征普通', `name_eses` = 'Burning Crusade normal', `name_esmx` = 'Burning Crusade normal', `name_ruru` = 'Burning Crusade (обычный режим)' WHERE `id` = 2;
UPDATE `lfgdungeongroup` SET `name_kokr` = '불타는 성전 (영웅)', `name_frfr` = 'The Burning Crusade - mode héroïque', `name_dede` = 'Heroische Dungeons (Burning Crusade)', `name_zhcn` = '燃烧的远征（英雄）', `name_zhtw` = '燃燒的遠征英雄', `name_eses` = 'Burning Crusade heroica', `name_esmx` = 'Burning Crusade heroica', `name_ruru` = 'Burning Crusade (героический режим)' WHERE `id` = 3;
UPDATE `lfgdungeongroup` SET `name_kokr` = '리치 왕의 분노 (일반)', `name_frfr` = 'Wrath of the Lich King  - mode normal', `name_dede` = 'Normale Dungeons (Wrath of the Lich King)', `name_zhcn` = '巫妖王之怒（普通）', `name_zhtw` = '巫妖王之怒普通', `name_eses` = 'Wrath of the Lich King normal', `name_esmx` = 'Wrath of the Lich King normal', `name_ruru` = 'Wrath of the Lich King (обычный режим)' WHERE `id` = 4;
UPDATE `lfgdungeongroup` SET `name_kokr` = '리치 왕의 분노 (영웅)', `name_frfr` = 'Wrath of the Lich King  - mode héroïque', `name_dede` = 'Heroische Dungeons (Wrath of the Lich King)', `name_zhcn` = '巫妖王之怒（英雄）', `name_zhtw` = '巫妖王之怒英雄', `name_eses` = 'Wrath of the Lich King heroica', `name_esmx` = 'Wrath of the Lich King heroica', `name_ruru` = 'Wrath of the Lich King (героический режим)' WHERE `id` = 5;
UPDATE `lfgdungeongroup` SET `name_kokr` = '오리지널 공격대', `name_frfr` = 'Raids classiques', `name_dede` = 'Schlachtzüge (Classic)', `name_zhcn` = '经典团队副本', `name_zhtw` = '艾澤拉斯團隊', `name_eses` = 'Banda clásica', `name_esmx` = 'Banda clásica', `name_ruru` = 'Классические рейды' WHERE `id` = 6;
UPDATE `lfgdungeongroup` SET `name_kokr` = '불타는 성전 공격대', `name_frfr` = 'Raid de The Burning Crusade', `name_dede` = 'Schlachtzüge (Burning Crusade)', `name_zhcn` = '燃烧的远征团队副本', `name_zhtw` = '燃燒的遠征團隊', `name_eses` = 'Banda de Burning Crusade', `name_esmx` = 'Banda de Burning Crusade', `name_ruru` = 'Рейды Burning Crusade' WHERE `id` = 7;
UPDATE `lfgdungeongroup` SET `name_kokr` = '리치 왕의 분노 공격대 (10인)', `name_frfr` = 'Raid de Wrath of the Lich King (10)', `name_dede` = 'Schlachtzüge: 10 (Wrath of the Lich King)', `name_zhcn` = '巫妖王之怒团队副本（10人）', `name_zhtw` = '巫妖王之怒團隊 (10)', `name_eses` = 'Banda de Wrath of the Lich King (10)', `name_esmx` = 'Banda de Wrath of the Lich King (10)', `name_ruru` = 'Рейды Wrath of the Lich King (10)' WHERE `id` = 8;
UPDATE `lfgdungeongroup` SET `name_kokr` = '리치 왕의 분노 공격대 (25인)', `name_frfr` = 'Raid de Wrath of the Lich King (25)', `name_dede` = 'Schlachtzüge: 25 (Wrath of the Lich King)', `name_zhcn` = '巫妖王之怒团队副本（25人）', `name_zhtw` = '巫妖王之怒團隊 (25)', `name_eses` = 'Banda de Wrath of the Lich King (25)', `name_esmx` = 'Banda de Wrath of the Lich King (25)', `name_ruru` = 'Рейды Wrath of the Lich King (25)' WHERE `id` = 9;
UPDATE `lfgdungeongroup` SET `name_kokr` = '월드 이벤트', `name_frfr` = 'Évènements mondiaux', `name_dede` = 'Weltevents', `name_zhcn` = '世界事件', `name_zhtw` = '世界事件', `name_eses` = 'Eventos del mundo', `name_esmx` = 'Eventos del mundo', `name_ruru` = 'Игровые события' WHERE `id` = 11;
