-- totemcategory: 0 inserts, 32 updates, 0 deletes

-- Changed values
UPDATE `totemcategory` SET `name_kokr` = '무두질용 손칼', `name_frfr` = 'Couteau à dépecer (OLD)', `name_dede` = 'Kürschnermesser (alt)', `name_zhcn` = '剥皮刀', `name_zhtw` = '剝皮小刀 (OLD)', `name_eses` = 'Cuchillo para desollar', `name_esmx` = 'Cuchillo para desollar', `name_ruru` = 'Нож для снятия шкур' WHERE `id` = 1;
UPDATE `totemcategory` SET `name_kokr` = '대지의 토템', `name_frfr` = 'Totem de terre', `name_dede` = 'Erdtotem', `name_zhcn` = '大地图腾', `name_zhtw` = '大地圖騰', `name_eses` = 'Tótem de tierra', `name_esmx` = 'Tótem de tierra', `name_ruru` = 'Тотем земли' WHERE `id` = 2;
UPDATE `totemcategory` SET `name_kokr` = '바람의 토템', `name_frfr` = 'Totem d\'air', `name_dede` = 'Lufttotem', `name_zhcn` = '空气图腾', `name_zhtw` = '風之圖騰', `name_eses` = 'Tótem de aire', `name_esmx` = 'Tótem de aire', `name_ruru` = 'Тотем воздуха' WHERE `id` = 3;
UPDATE `totemcategory` SET `name_kokr` = '불의 토템', `name_frfr` = 'Totem de feu', `name_dede` = 'Feuertotem', `name_zhcn` = '火焰图腾', `name_zhtw` = '火焰圖騰', `name_eses` = 'Tótem de fuego', `name_esmx` = 'Tótem de fuego', `name_ruru` = 'Тотем огня' WHERE `id` = 4;
UPDATE `totemcategory` SET `name_kokr` = '물의 토템', `name_frfr` = 'Totem d\'eau', `name_dede` = 'Wassertotem', `name_zhcn` = '水之图腾', `name_zhtw` = '水之圖騰', `name_eses` = 'Tótem de agua', `name_esmx` = 'Tótem de agua', `name_ruru` = 'Тотем воды' WHERE `id` = 5;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 구리마법막대', `name_frfr` = 'Bâtonnet runique en cuivre', `name_dede` = 'Runenverzierte Kupferrute', `name_zhcn` = '符文铜棒', `name_zhtw` = '符文銅棒', `name_eses` = 'Vara rúnica de cobre', `name_esmx` = 'Vara rúnica de cobre', `name_ruru` = 'Рунический медный жезл' WHERE `id` = 6;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 은마법막대', `name_frfr` = 'Bâtonnet runique en argent', `name_dede` = 'Runenverzierte Silberrute', `name_zhcn` = '符文银棒', `name_zhtw` = '符文銀棒', `name_eses` = 'Vara rúnica de plata', `name_esmx` = 'Vara rúnica de plata', `name_ruru` = 'Рунический серебряный жезл' WHERE `id` = 7;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 금마법막대', `name_frfr` = 'Bâtonnet runique en or', `name_dede` = 'Runenverzierte Goldrute', `name_zhcn` = '符文金棒', `name_zhtw` = '符文金棒', `name_eses` = 'Vara rúnica de oro', `name_esmx` = 'Vara rúnica de oro', `name_ruru` = 'Рунический золотой жезл' WHERE `id` = 8;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 진은마법막대', `name_frfr` = 'Bâtonnet runique en vrai-argent', `name_dede` = 'Runenverzierte Echtsilberrute', `name_zhcn` = '符文真银棒', `name_zhtw` = '符文真銀棒', `name_eses` = 'Vara rúnica de veraplata', `name_esmx` = 'Vara rúnica de veraplata', `name_ruru` = 'Рунический жезл истинного серебра' WHERE `id` = 9;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 아케이나이트 마법막대', `name_frfr` = 'Bâtonnet runique en arcanite', `name_dede` = 'Runenverzierte Arkanitrute', `name_zhcn` = '符文奥金棒', `name_zhtw` = '符文奧金棒', `name_eses` = 'Vara rúnica de arcanita', `name_esmx` = 'Vara rúnica de arcanita', `name_ruru` = 'Рунический арканитовый жезл' WHERE `id` = 10;
UPDATE `totemcategory` SET `name_kokr` = '채광용 곡괭이', `name_frfr` = 'Pioche de mineur (OLD)', `name_dede` = 'Spitzhacke (alt)', `name_zhcn` = '矿工锄', `name_zhtw` = '礦工鋤 (OLD)', `name_eses` = 'Pico de minería', `name_esmx` = 'Pico de minería', `name_ruru` = 'Шахтерская кирка' WHERE `id` = 11;
UPDATE `totemcategory` SET `name_kokr` = '현자의 돌', `name_frfr` = 'Pierre philosophale', `name_dede` = 'Stein der Weisen', `name_zhcn` = '点金石', `name_zhtw` = '點金石', `name_eses` = 'Piedra filosofal', `name_esmx` = 'Piedra filosofal', `name_ruru` = 'Философский камень' WHERE `id` = 12;
UPDATE `totemcategory` SET `name_kokr` = '대장장이 망치', `name_frfr` = 'Marteau de forgeron (VIEUX)', `name_dede` = 'Schmiedehammer', `name_zhcn` = '铁匠锤', `name_zhtw` = '鐵匠之錘 (OLD)', `name_eses` = 'Martillo de herrero', `name_esmx` = 'Martillo de herrero', `name_ruru` = 'Кузнечный молот' WHERE `id` = 13;
UPDATE `totemcategory` SET `name_kokr` = '만능 스패너', `name_frfr` = 'Clé plate', `name_dede` = 'Bogenlichtschraubenschlüssel', `name_zhcn` = '扳手', `name_zhtw` = '扳手', `name_eses` = 'Llave de tuerca arcoluz', `name_esmx` = 'Llave de tuerca arcoluz', `name_ruru` = 'Тангенциальный вращатель' WHERE `id` = 14;
UPDATE `totemcategory` SET `name_kokr` = '자동회전 초정밀조율기', `name_frfr` = 'Micro-ajusteur gyromatique', `name_dede` = 'Gyromatischer Mikroregler', `name_zhcn` = '侏儒微调器', `name_zhtw` = '地精微調器', `name_eses` = 'Microajustador giromático', `name_esmx` = 'Microajustador giromático', `name_ruru` = 'Шлицевой гироинструмент' WHERE `id` = 15;
UPDATE `totemcategory` SET `name_kokr` = '만물의 토템', `name_frfr` = 'Totem maître', `name_dede` = 'Meistertotem', `name_zhcn` = '大师图腾', `name_zhtw` = '大師圖騰', `name_eses` = 'Tótem maestro', `name_esmx` = 'Tótem maestro', `name_ruru` = 'Тотем власти' WHERE `id` = 21;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 지옥무쇠 마법막대', `name_frfr` = 'Bâtonnet runique en gangrefer', `name_dede` = 'Runenverzierte Teufelseisenrute', `name_zhcn` = '符文魔铁棒', `name_zhtw` = '符文魔鐵棒', `name_eses` = 'Vara rúnica de hierro vil', `name_esmx` = 'Vara rúnica de hierro vil', `name_ruru` = 'Рунический жезл оскверненного железа' WHERE `id` = 41;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 아다만타이트 마법막대', `name_frfr` = 'Bâtonnet runique en adamantite', `name_dede` = 'Runenverzierte Adamantitrute', `name_zhcn` = '符文精金棒', `name_zhtw` = '符文堅鋼棒', `name_eses` = 'Vara rúnica de adamantita', `name_esmx` = 'Vara rúnica de adamantita', `name_ruru` = 'Рунический адамантитовый жезл' WHERE `id` = 62;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 이터늄 마법막대', `name_frfr` = 'Bâtonnet runique en éternium', `name_dede` = 'Runenverzierte Eterniumrute', `name_zhcn` = '符文恒金棒', `name_zhtw` = '符文恆金棒', `name_eses` = 'Vara rúnica de eternio', `name_esmx` = 'Vara rúnica de eternio', `name_ruru` = 'Рунический этерниевый жезл' WHERE `id` = 63;
UPDATE `totemcategory` SET `name_kokr` = '빈 깃대', `name_frfr` = 'Plume creuse', `name_dede` = 'Hohler Federkiel', `name_zhcn` = '羽毛笔', `name_zhtw` = '中空羽毛筆', `name_eses` = 'Pluma hueca', `name_esmx` = 'Pluma hueca', `name_ruru` = 'Священное перо' WHERE `id` = 81;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 아주라이트 마법막대', `name_frfr` = 'Bâtonnet runique en azurite', `name_dede` = 'Runenverzierte Azuritrute', `name_zhcn` = '符文蓝铜棒', `name_zhtw` = '符文藍銅棒', `name_eses` = 'Vara rúnica de azurita', `name_esmx` = 'Vara rúnica de azurita', `name_ruru` = 'Рунический азуритовый жезл' WHERE `id` = 101;
UPDATE `totemcategory` SET `name_kokr` = '숙련자의 필기구', `name_frfr` = 'Coffret de calligraphie de virtuose', `name_dede` = 'Schreibzeug des Virtuosen', `name_zhcn` = '学者的书写工具', `name_zhtw` = '行家書寫工具組', `name_eses` = 'Juego de caligrafía de virtuoso', `name_esmx` = 'Juego de caligrafía de virtuoso', `name_ruru` = 'Набор виртуозного начертателя' WHERE `id` = 121;
UPDATE `totemcategory` SET `name_kokr` = '북소리', `name_frfr` = 'Tambours', `name_dede` = 'Trommeln', `name_zhcn` = '战鼓', `name_zhtw` = '鼓', `name_eses` = 'Tambores', `name_esmx` = 'Tambores', `name_ruru` = 'Барабаны' WHERE `id` = 141;
UPDATE `totemcategory` SET `name_kokr` = '노움 군용칼', `name_frfr` = 'Couteau de l\'armée gnome', `name_dede` = 'Gnomisches Armeemesser', `name_zhcn` = '侏儒军刀', `name_zhtw` = '地精軍用小刀', `name_eses` = 'Navaja gnómica', `name_esmx` = 'Navaja gnómica', `name_ruru` = 'Гномский армейский нож' WHERE `id` = 161;
UPDATE `totemcategory` SET `name_kokr` = '대장장이 망치', `name_frfr` = 'Marteau de forgeron', `name_dede` = 'Schmiedehammer', `name_zhcn` = '铁匠锤', `name_zhtw` = '鐵匠之錘', `name_eses` = 'Martillo de herrero', `name_esmx` = 'Martillo de herrero', `name_ruru` = 'Кузнечный молот' WHERE `id` = 162;
UPDATE `totemcategory` SET `name_kokr` = '채광용 곡괭이', `name_frfr` = 'Pioche de mineur', `name_dede` = 'Spitzhacke', `name_zhcn` = '矿工锄', `name_zhtw` = '挖礦鎬', `name_eses` = 'Pico de minería', `name_esmx` = 'Pico de minería', `name_ruru` = 'Шахтерская кирка' WHERE `id` = 165;
UPDATE `totemcategory` SET `name_kokr` = '무두질용 손칼', `name_frfr` = 'Couteau à dépecer', `name_dede` = 'Kürschnermesser', `name_zhcn` = '剥皮刀', `name_zhtw` = '剝皮小刀', `name_eses` = 'Cuchillo para desollar', `name_esmx` = 'Cuchillo para desollar', `name_ruru` = 'Нож для снятия шкур' WHERE `id` = 166;
UPDATE `totemcategory` SET `name_kokr` = '망치 곡괭이', `name_frfr` = 'Pioche-marteau', `name_dede` = 'Spitzhammer', `name_zhcn` = '锤头锄', `name_zhtw` = '錘鎬', `name_eses` = 'Martillo pico', `name_esmx` = 'Martillo pico', `name_ruru` = 'Тяжелая кирка' WHERE `id` = 167;
UPDATE `totemcategory` SET `name_kokr` = '칼날 곡괭이', `name_frfr` = 'Pioche à lame', `name_dede` = 'Klingenhacke', `name_zhcn` = '锋刃锄', `name_zhtw` = '刃鎬', `name_eses` = 'Hacha pico afilada', `name_esmx` = 'Hacha pico afilada', `name_ruru` = 'Острая мотыга' WHERE `id` = 168;
UPDATE `totemcategory` SET `name_kokr` = '부싯돌과 불쏘시개', `name_frfr` = 'Silex et amadou', `name_dede` = 'Feuerstein und Zunder', `name_zhcn` = '燧石和火绒', `name_zhtw` = '燧石和火絨', `name_eses` = 'Sílex y yesca', `name_esmx` = 'Sílex y yesca', `name_ruru` = 'Кремень и трут' WHERE `id` = 169;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 코발트 마법막대 (미사용)', `name_frfr` = 'Bâtonnet runique en cobalt (NE PAS UTILISER)', `name_dede` = 'Runenverzierte Kobaltrute', `name_zhcn` = 'Runed Cobalt Rod (DO NOT USE)', `name_zhtw` = '符文鈷藍棒 (不要使用)', `name_eses` = 'Vara rúnica de cobalto (DO NOT USE)', `name_esmx` = 'Vara rúnica de cobalto (DO NOT USE)', `name_ruru` = 'Рунический кобальтовый жезл (DO NOT USE)' WHERE `id` = 189;
UPDATE `totemcategory` SET `name_kokr` = '룬문자 티타늄 마법막대', `name_frfr` = 'Bâtonnet runique en titane', `name_dede` = 'Runenverzierte Titanrute', `name_zhcn` = '符文泰坦神铁棒', `name_zhtw` = '符文泰坦鋼棒', `name_eses` = 'Vara rúnica de titanio', `name_esmx` = 'Vara rúnica de titanio', `name_ruru` = 'Рунический титановый жезл' WHERE `id` = 190;
