-- chatchannels: 0 inserts, 6 updates, 0 deletes

-- Changed values
UPDATE `chatchannels` SET `name_kokr` = '공개 - %s', `name_frfr` = 'Général - %s', `name_dede` = 'Allgemein - %s', `name_zhcn` = '综合 - %s', `name_zhtw` = '綜合 - %s', `name_eses` = 'General: %s', `name_esmx` = 'General: %s', `name_ruru` = 'Общий: %s', `shortcut_kokr` = '공개', `shortcut_frfr` = 'Général', `shortcut_dede` = 'Allgemein', `shortcut_zhcn` = '综合', `shortcut_zhtw` = '綜合', `shortcut_eses` = 'General', `shortcut_esmx` = 'General', `shortcut_ruru` = 'Общий' WHERE `id` = 1;
UPDATE `chatchannels` SET `name_kokr` = '거래 - %s', `name_frfr` = 'Commerce - %s', `name_dede` = 'Handel - %s', `name_zhcn` = '交易 - %s', `name_zhtw` = '交易 - %s', `name_eses` = 'Comercio: %s', `name_esmx` = 'Comercio: %s', `name_ruru` = 'Торговля: %s', `shortcut_kokr` = '거래', `shortcut_frfr` = 'Commerce', `shortcut_dede` = 'Handel', `shortcut_zhcn` = '交易', `shortcut_zhtw` = '交易', `shortcut_eses` = 'Comercio', `shortcut_esmx` = 'Comercio', `shortcut_ruru` = 'Торговля' WHERE `id` = 2;
UPDATE `chatchannels` SET `name_kokr` = '수비 - %s', `name_frfr` = 'DéfenseLocale - %s', `name_dede` = 'LokaleVerteidigung - %s', `name_zhcn` = '本地防务 - %s', `name_zhtw` = '本地防務 - %s', `name_eses` = 'Defensa local: %s', `name_esmx` = 'Defensa local: %s', `name_ruru` = 'Оборона: %s', `shortcut_kokr` = '수비', `shortcut_frfr` = 'DéfenseLocale', `shortcut_dede` = 'LokaleVerteidigung', `shortcut_zhcn` = '本地防务', `shortcut_zhtw` = '本地防務', `shortcut_eses` = 'DefensaLocal', `shortcut_esmx` = 'DefensaLocal', `shortcut_ruru` = 'ОборонаЛокальный' WHERE `id` = 22;
UPDATE `chatchannels` SET `name_kokr` = '전쟁', `name_frfr` = 'DéfenseUniverselle', `name_dede` = 'WeltVerteidigung', `name_zhcn` = '世界防务', `name_zhtw` = '世界防務', `name_eses` = 'Defensa general', `name_esmx` = 'Defensa general', `name_ruru` = 'Оборона: глобальный', `shortcut_kokr` = '전쟁', `shortcut_frfr` = 'DéfenseUniverselle', `shortcut_dede` = 'WeltVerteidigung', `shortcut_zhcn` = '世界防务', `shortcut_zhtw` = '世界防務', `shortcut_eses` = 'DefensaGeneral', `shortcut_esmx` = 'DefensaGeneral', `shortcut_ruru` = 'ОборонаГлобальный' WHERE `id` = 23;
UPDATE `chatchannels` SET `name_kokr` = '길드모집 - %s', `name_frfr` = 'RecrutementDeGuilde - %s', `name_dede` = 'Gildenrekrutierung - %s', `name_zhcn` = '公会招募 - %s', `name_zhtw` = '公會招募 - %s', `name_eses` = 'BuscaHermandad: %s', `name_esmx` = 'BuscaHermandad: %s', `name_ruru` = 'Гильдии: %s', `shortcut_kokr` = '길드모집', `shortcut_frfr` = 'RecrutementDeGuilde', `shortcut_dede` = 'Gildenrekrutierung', `shortcut_zhcn` = '公会招募', `shortcut_zhtw` = '公會招募', `shortcut_eses` = 'BuscaHermandad', `shortcut_esmx` = 'BuscaHermandad', `shortcut_ruru` = 'Гильдии' WHERE `id` = 25;
UPDATE `chatchannels` SET `name_kokr` = '파티찾기', `name_frfr` = 'RechercheDeGroupe', `name_dede` = 'SucheNachGruppe', `name_zhcn` = '寻求组队', `name_zhtw` = '尋求組隊', `name_eses` = 'BuscarGrupo', `name_esmx` = 'BuscarGrupo', `name_ruru` = 'Поиск спутников', `shortcut_kokr` = '파티찾기', `shortcut_frfr` = 'RechercheDeGroupe', `shortcut_dede` = 'SucheNachGruppe', `shortcut_zhcn` = '寻求组队', `shortcut_zhtw` = '尋求組隊', `shortcut_eses` = 'BuscarGrupo', `shortcut_esmx` = 'BuscarGrupo', `shortcut_ruru` = 'ПоискСпутников' WHERE `id` = 26;
