-- [F-032] mod-maghar: namegen: 7143 inserts, 0 updates, 0 deletes

-- New entries
SET @NameGenID = (SELECT COALESCE(MAX(id), 0) FROM `dbc`.`namegen`);

-- DELETE FROM `namegen` WHERE `id` BETWEEN 18994 AND 19053;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES
(@NameGenID := @NameGenID +1, 'Durak', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Gorvash', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Zagdush', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Marokh', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Urgan', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Drogath', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Karguk', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Thurgan', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Morkha', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Ruggak', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Dargul', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Sharguk', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Volrath', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Grulkar', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Odgrim', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Tharzuk', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Belgor', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Hargal', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Zundak', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Morgum', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Drakgar', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Urzul', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Skarvyn', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Golmash', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Vorgak', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Hulgar', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Ragmesh', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Turgok', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Wargash', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Grombul', @MagharOrc, @Male),
(@NameGenID := @NameGenID +1, 'Grezha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Morka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Zulrah', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Kasha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Durna', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Velka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Shagra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Tergha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Mokra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Vashka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Ruga', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Zarga', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Helka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Durgha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Nagra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Shelgra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Vorka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Ashra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Gruna', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Melgha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Torka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Ulgra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Zhenra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Karga', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Drenka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Halgra', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Murgha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Selka', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Wragha', @MagharOrc, @Female),
(@NameGenID := @NameGenID +1, 'Onaka', @MagharOrc, @Female);
